// kitchen-sink/vue/src/pages/buttons.vue
<template>
  <f7-page>
    <f7-navbar title="Buttons" back-link="Back"></f7-navbar>

    <f7-block-title>Usual Buttons</f7-block-title>
    <f7-block>
      <f7-row>
        <f7-col>
          <f7-button>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button round>Round</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Fill Buttons</f7-block-title>
    <f7-block>
      <f7-row>
        <f7-col>
          <f7-button fill>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill round>Round</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Outline Buttons (MD-theme only)</f7-block-title>
    <f7-block>
      <f7-row>
        <f7-col>
          <f7-button outline>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button outline>Button</f7-button>
        </f7-col>
        <f7-col>
          <f7-button outline round>Round</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Raised Buttons (MD-theme only)</f7-block-title>
    <f7-block>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button raised>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised fill>Fill</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised outline>Outline</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button raised round>Round</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised fill round>Fill</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button raised outline round>Outline</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Segmented</f7-block-title>
    <f7-block>
      <f7-segmented raised tag="p">
        <f7-button>Button</f7-button>
        <f7-button>Button</f7-button>
        <f7-button active>Active</f7-button>
      </f7-segmented>
      <f7-segmented raised tag="p">
        <f7-button outline>Outline</f7-button>
        <f7-button outline>Outline</f7-button>
        <f7-button outline active>Active</f7-button>
      </f7-segmented>
      <f7-segmented raised round tag="p">
        <f7-button round>Button</f7-button>
        <f7-button round>Button</f7-button>
        <f7-button round active>Active</f7-button>
      </f7-segmented>
      <f7-segmented raised round tag="p">
        <f7-button round outline>Outline</f7-button>
        <f7-button round outline>Outline</f7-button>
        <f7-button round outline active>Active</f7-button>
      </f7-segmented>
    </f7-block>

    <f7-block-title>Big Buttons</f7-block-title>
    <f7-block>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button big>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button big raised>Raised</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big raised fill>Raised Fill</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Small Buttons</f7-block-title>
    <f7-block>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button big small>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big small outline>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big small fill>Fill</f7-button>
        </f7-col>
      </f7-row>
      <f7-row tag="p">
        <f7-col tag="span">
          <f7-button big small round>Button</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big small outline round>Outline</f7-button>
        </f7-col>
        <f7-col tag="span">
          <f7-button big small fill round>Fill</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Color Buttons</f7-block-title>
    <f7-block>
      <f7-row>
        <f7-col>
          <f7-button color="red">Red</f7-button>
        </f7-col>
        <f7-col>
          <f7-button color="green">Green</f7-button>
        </f7-col>
        <f7-col>
          <f7-button color="blue">Blue</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>Color Fill Buttons</f7-block-title>
    <f7-block>
      <f7-row>
        <f7-col>
          <f7-button fill color="red">Red</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill color="green">Green</f7-button>
        </f7-col>
        <f7-col>
          <f7-button fill color="blue">Blue</f7-button>
        </f7-col>
      </f7-row>
    </f7-block>

    <f7-block-title>List-Block Buttons</f7-block-title>
    <f7-list inset>
      <f7-list-button title="List Button 1"></f7-list-button>
      <f7-list-button title="List Button 2"></f7-list-button>
      <f7-list-button title="List Button 3"></f7-list-button>
    </f7-list>
    <f7-list inset>
      <f7-list-button title="Big Red Button" color="red"></f7-list-button>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7BlockTitle, f7Block, f7List, f7Row, f7Col, f7ListButton, f7Button, f7Segmented } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
      f7BlockTitle,
      f7Block,
      f7List,
      f7Row,
      f7Col,
      f7ListButton,
      f7Button,
      f7Segmented,
    }
  }
</script>

// react/kitchen-sink/src/pages/buttons.jsx
import React from 'react';
import { Navbar, Page, BlockTitle, Block, List, Row, Col, ListButton, Button, Segmented } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Buttons" backLink="Back" />

    <BlockTitle>Usual Buttons</BlockTitle>
    <Block>
      <Row>
        <Col>
          <Button>Button</Button>
        </Col>
        <Col>
          <Button>Button</Button>
        </Col>
        <Col>
          <Button round>Round</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Fill Buttons</BlockTitle>
    <Block>
      <Row>
        <Col>
          <Button fill>Button</Button>
        </Col>
        <Col>
          <Button fill>Button</Button>
        </Col>
        <Col>
          <Button fill round>Round</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Outline Buttons (MD-theme only)</BlockTitle>
    <Block>
      <Row>
        <Col>
          <Button outline>Button</Button>
        </Col>
        <Col>
          <Button outline>Button</Button>
        </Col>
        <Col>
          <Button outline round>Round</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Raised Buttons (MD-theme only)</BlockTitle>
    <Block>
      <Row tag="p">
        <Col>
          <Button raised>Button</Button>
        </Col>
        <Col>
          <Button raised fill>Fill</Button>
        </Col>
        <Col>
          <Button raised outline>Outline</Button>
        </Col>
      </Row>
      <Row tag="p">
        <Col>
          <Button raised round>Round</Button>
        </Col>
        <Col>
          <Button raised fill round>Fill</Button>
        </Col>
        <Col>
          <Button raised outline round>Outline</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Segmented</BlockTitle>
    <Block>
      <Segmented raised tag="p">
        <Button>Button</Button>
        <Button>Button</Button>
        <Button active>Active</Button>
      </Segmented>
      <Segmented raised tag="p">
        <Button outline>Outline</Button>
        <Button outline>Outline</Button>
        <Button outline active>Active</Button>
      </Segmented>
      <Segmented raised round tag="p">
        <Button round>Button</Button>
        <Button round>Button</Button>
        <Button round active>Active</Button>
      </Segmented>
      <Segmented round round tag="p">
        <Button round outline>Outline</Button>
        <Button round outline>Outline</Button>
        <Button round outline active>Active</Button>
      </Segmented>
    </Block>

    <BlockTitle>Big Buttons</BlockTitle>
    <Block>
      <Row tag="p">
        <Col>
          <Button big>Button</Button>
        </Col>
        <Col>
          <Button big fill>Fill</Button>
        </Col>
      </Row>
      <Row tag="p">
        <Col>
          <Button big raised>Raised</Button>
        </Col>
        <Col>
          <Button big raised fill>Raised Fill</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Small Buttons</BlockTitle>
    <Block>
      <Row tag="p">
        <Col>
          <Button big small>Button</Button>
        </Col>
        <Col>
          <Button big small outline>Outline</Button>
        </Col>
        <Col>
          <Button big small fill>Fill</Button>
        </Col>
      </Row>
      <Row tag="p">
        <Col>
          <Button big small round>Button</Button>
        </Col>
        <Col>
          <Button big small outline round>Outline</Button>
        </Col>
        <Col>
          <Button big small fill round>Fill</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Color Buttons</BlockTitle>
    <Block>
      <Row>
        <Col>
          <Button color="red">Red</Button>
        </Col>
        <Col>
          <Button color="green">Green</Button>
        </Col>
        <Col>
          <Button color="blue">Blue</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>Color Fill Buttons</BlockTitle>
    <Block>
      <Row>
        <Col>
          <Button fill color="red">Red</Button>
        </Col>
        <Col>
          <Button fill color="green">Green</Button>
        </Col>
        <Col>
          <Button fill color="blue">Blue</Button>
        </Col>
      </Row>
    </Block>

    <BlockTitle>List-Block Buttons</BlockTitle>
    <List inset>
      <ListButton title="List Button 1"></ListButton>
      <ListButton title="List Button 2"></ListButton>
      <ListButton title="List Button 3"></ListButton>
    </List>
    <List inset>
      <ListButton title="Big Red Button" color="red"></ListButton>
    </List>
  </Page>
);
