// kitchen-sink/react/src/pages/calendar-page.jsx
import React from 'react';
import { Navbar, Page, NavTitle, List, ListItem, Block } from 'framework7-react';

export default class extends React.Component {
  constructor(props) {
    super(props);

    const date = new Date();
    const year = date.getFullYear();
    const month = date.getMonth();
    const day = date.getDate();

    this.state = {
      today: new Date(year, month, day),
      events: [
        {
          date: new Date(year, month, day),
          hours: 12,
          minutes: 30,
          title: 'Meeting with Vladimir',
          color: '#2196f3',
        },
        {
          date: new Date(year, month, day),
          hours: 18,
          minutes: 0,
          title: 'Shopping',
          color: '#4caf50',
        },
        {
          date: new Date(year, month, day),
          hours: 21,
          minutes: 0,
          title: 'Gym',
          color: '#e91e63',
        },
        {
          date: new Date(year, month, day + 2),
          hours: 16,
          minutes: 0,
          title: 'Pay loan',
          color: '#2196f3',
        },
        {
          date: new Date(year, month, day + 2),
          hours: 21,
          minutes: 0,
          title: 'Gym',
          color: '#ff9800',
        },
      ],
      eventItems: [],
    }
  }
  render() {
    return (
      <Page onPageInit={this.onPageInit.bind(this)} onPageBeforeRemove={this.onPageBeforeRemove.bind(this)}>
        <Navbar backLink="Back">
          <NavTitle className="navbar-calendar-title"></NavTitle>
        </Navbar>
        <Block
          id="calendar"
          strong
          className="no-padding no-margin no-hairline-top"
        ></Block>
        <List
          id="calendar-events"
          noHairlines
          className="no-margin no-ios-left-edge"
        >
          {this.state.eventItems.map((item, index) => (
            <ListItem
              key={index}
              title={item.title}
              after={item.time}
            >
              <div class="event-color" style={{'background-color': item.color}} slot="root-start"></div>
            </ListItem>
          ))}
          {this.state.eventItems.length === 0 && (
            <ListItem>
              <span className="text-color-gray" slot="title">No events for this day</span>
            </ListItem>
          )}
        </List>
      </Page>
    );
  }
  renderEvents(calendar) {
    const self = this;
    const currentDate = calendar.value[0];
    const currentEvents = self.state.events
      .filter(event => (
        event.date.getTime() >= currentDate.getTime() &&
        event.date.getTime() < currentDate.getTime() + 24 * 60 * 60 * 1000
      ));

    const eventItems = [];
    if (currentEvents.length) {
      currentEvents.forEach((event) => {
        const hours = event.date.getHours();
        let minutes = event.date.getMinutes();
        if (minutes < 10) minutes = `0${minutes}`;
        eventItems.push({
          title: event.title,
          time: `${hours}:${minutes}`,
          color: event.color,
        });
      });
    }
    self.setState({
      eventItems,
    });
  }
  onPageInit(e, page) {
    const self = this;
    const app = self.$f7;
    const $ = self.$$;
    const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
    self.calendar = app.calendar.create({
      containerEl: '#calendar',
      toolbar: false,
      value: [self.state.today],
      events: self.state.events,
      on: {
        init(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          app.navbar.size(page.navbarEl);
          calendar.$el.addClass('no-ios-right-edge');
          self.renderEvents(calendar);
        },
        monthYearChangeStart(calendar) {
          $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
          app.navbar.size(page.navbarEl);
        },
        change(calendar) {
          self.renderEvents(calendar);
        },
      },
    });
  }
  onPageBeforeRemove() {
    const self = this;
    self.calendar.destroy();
  }
};

// react/kitchen-sink/src/pages/calendar-page.vue
<template>
  <Page page-content={false}>
    <Navbar backLink="Back">
      <NavTitle class="navbar-calendar-title"></NavTitle>
    </Navbar>
    <div class="page-content">
      <div id="calendar" class="block block-strong no-padding no-margin no-hairline-top"></div>
      <div id="calendar-events" class="list no-margin no-hairlines no-ios-left-edge">
        <ul></ul>
      </div>
    </div>
  </Page>
</template>
<script>
  import React from 'react';
  import { Navbar, Page, NavTitle } from 'framework7-react';

  export default {
    components: {
      Navbar,
      Page,
      NavTitle,
    },
    data() {
      const date = new Date();
      const year = date.getFullYear();
      const month = date.getMonth();
      const day = date.getDate();
      return {
        today: new Date(year, month, day),
        events: [
          {
            date: new Date(year, month, day, 12, 30),
            title: 'Meeting with Vladimir',
          },
          {
            date: new Date(year, month, day, 18, 0),
            title: 'Shopping',
          },
          {
            date: new Date(year, month, day, 21, 0),
            title: 'Gym',
          },
          {
            date: new Date(year, month, day + 2, 16, 0),
            title: 'Pay loan',
          },
          {
            date: new Date(year, month, day + 2, 21, 0),
            title: 'Gym',
          },
        ],
      };
    },
    methods: {
      renderEvents(calendar) {
        const self = this;
        const currentDate = calendar.value[0];
        const currentEvents = self.events
          .filter(event => (
            event.date.getTime() >= currentDate.getTime() &&
        event.date.getTime() < currentDate.getTime() + 24 * 60 * 60 * 1000
          ));
        let eventsHtml = '';
        if (currentEvents.length) {
          eventsHtml = currentEvents
            .map((event) => {
              const hours = event.date.getHours();
              let minutes = event.date.getMinutes();
              if (minutes < 10) minutes = `0${minutes}`;
              return `${'<li class="item-content">' +
                '<div class="item-inner">' +
                  '<div class="item-title">'}${event.title}</div>` +
                  `<div class="item-after">${hours}:${minutes}</div>` +
                '</div>' +
              '</li>';
            })
            .join('');
        } else {
          eventsHtml = '<li class="item-content">' +
                      '<div class="item-inner">' +
                        '<div class="item-title text-color-gray">No events for this day</div>' +
                      '</div>' +
                    '</li>';
        }

        self.$el.querySelector('.list ul').innerHTML = eventsHtml;
      },
    },
    on: {
      pageInit(e, page) {
        const self = this;
        const app = self.$f7;
        const $ = self.$$;
        const monthNames = ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December'];
        self.calendar = app.calendar.create({
          containerEl: '#calendar',
          toolbar: false,
          value: [self.today],
          events: self.events.map(event => new Date(event.date.getFullYear(), event.date.getMonth(), event.date.getDate())),
          on: {
            init(calendar) {
              $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
              app.navbar.size(page.navbarEl);
              calendar.$el.addClass('no-ios-right-edge');
              self.renderEvents(calendar);
            },
            monthYearChangeStart(calendar) {
              $('.navbar-calendar-title').text(`${monthNames[calendar.currentMonth]}, ${calendar.currentYear}`);
              app.navbar.size(page.navbarEl);
            },
            change(calendar) {
              self.renderEvents(calendar);
            },
          },
        });
      },
      pageBeforeRemove() {
        const self = this;
        self.calendar.destroy();
      },
    },
  };
</script>
