// kitchen-sink/react/src/pages/chips.jsx
import React from 'react';
import { Navbar, Page, BlockTitle, Chip, Block, Icon } from 'framework7-react';

export default class extends React.Component {
  constructor() {
    super();
    this.deleteChipBound = this.deleteChip.bind(this);
  }
  render() {
    return (
      <Page>
        <Navbar title="Chips" backLink="Back"></Navbar>
        <BlockTitle>Chips With Text</BlockTitle>
        <Block strong>
          <Chip text="Example Chip" />
          <Chip text="Another Chip" />
          <Chip text="One More Chip" />
          <Chip text="Fourth Chip" />
          <Chip text="Last One" />
        </Block>
        <BlockTitle>Icon Chips</BlockTitle>
        <Block strong>
          <Chip text="Add Contact" mediaBgColor={this.$theme.md ? 'blue' : undefined}>
            <Icon slot="media" ios="f7:add_round" md="material:add_circle"></Icon>
          </Chip>
          <Chip text="London" mediaBgColor={this.$theme.md ? 'green' : undefined}>
            <Icon slot="media" ios="f7:compass" md="material:location_on"></Icon>
          </Chip>
          <Chip text="John Doe" mediaBgColor={this.$theme.md ? 'red' : undefined}>
            <Icon slot="media" ios="f7:person" md="material:person"></Icon>
          </Chip>
        </Block>
        <BlockTitle>Contact Chips</BlockTitle>
        <Block strong>
          <Chip text="Jane Doe">
            <img slot="media" src="http://lorempixel.com/100/100/people/9/" />
          </Chip>
          <Chip text="John Doe">
            <img slot="media" src="http://lorempixel.com/100/100/people/3/" />
          </Chip>
          <Chip text="Adam Smith">
            <img slot="media" src="http://lorempixel.com/100/100/people/7/" />
          </Chip>
          <Chip text="Jennifer" mediaBgColor="pink" media="J" />
          <Chip text="Chris" mediaBgColor="yellow" mediaTextColor="black" media="C" />
          <Chip text="Kate" mediaBgColor="red" media="K" />
        </Block>
        <BlockTitle>Deletable Chips / Tags</BlockTitle>
        <Block strong>
          <Chip text="Example Chip" deleteable onClick={ this.deleteChipBound } />
          <Chip text="Chris" media="C" mediaBgColor="orange" textColor="black" deleteable onClick={ this.deleteChipBound } />
          <Chip text="Jane Doe" deleteable onClick={ this.deleteChipBound }>
            <img slot="media" src="http://lorempixel.com/100/100/people/9/"/>
          </Chip>
          <Chip text="One More Chip" deleteable onClick={ this.deleteChipBound } />
          <Chip text="Jennifer" mediaBgColor="pink" media="J" deleteable onClick={ this.deleteChipBound } />
          <Chip text="Adam Smith" deleteable onClick={ this.deleteChipBound }>
            <img slot="media" src="http://lorempixel.com/100/100/people/7/"/>
          </Chip>
        </Block>
        <BlockTitle>Color Chips</BlockTitle>
        <Block strong>
          <Chip text="Red Chip" color="red" />
          <Chip text="Green Chip" color="green" />
          <Chip text="Blue Chip" color="blue" />
          <Chip text="Orange Chip" color="orange" />
          <Chip text="Pink Chip" color="pink" />
        </Block>
      </Page>
    )
  }
  deleteChip(e) {
    const $$ = this.$$;
    const app = this.$f7;
    const target = e.target;
    app.dialog.confirm('Do you want to delete this tiny demo Chip?', () => {
      $$(target).parents('.chip').remove();
    });
  }
}

// react/kitchen-sink/src/pages/chips.vue
import { Navbar, Page, BlockTitle, Chip, Block, Icon } from 'framework7-react';

export default () => (
  <f7-page>
    <f7-navbar title="Chips" back-link="Back"></f7-navbar>
    <f7-block-title>Chips With Text</f7-block-title>
    <f7-block strong>
      <f7-chip text="Example Chip"></f7-chip>
      <f7-chip text="Another Chip"></f7-chip>
      <f7-chip text="One More Chip"></f7-chip>
      <f7-chip text="Fourth Chip"></f7-chip>
      <f7-chip text="Last One"></f7-chip>
    </f7-block>
    <f7-block-title>Icon Chips</f7-block-title>
    <f7-block strong>
      <f7-chip text="Add Contact" :media-bg-color="$theme.md ? 'blue' : undefined">
        <f7-icon slot="media" if-ios="f7:add_round" if-md="material:add_circle"></f7-icon>
      </f7-chip>
      <f7-chip text="London" :media-bg-color="$theme.md ? 'green' : undefined">
        <f7-icon slot="media" if-ios="f7:compass" if-md="material:location_on"></f7-icon>
      </f7-chip>
      <f7-chip text="John Doe" :media-bg-color="$theme.md ? 'red' : undefined">
        <f7-icon slot="media" if-ios="f7:person" if-md="material:person"></f7-icon>
      </f7-chip>
    </f7-block>
    <f7-block-title>Contact Chips</f7-block-title>
    <f7-block strong>
      <f7-chip text="Jane Doe">
        <img slot="media" src="http://lorempixel.com/100/100/people/9/"/>
      </f7-chip>
      <f7-chip text="John Doe">
        <img slot="media" src="http://lorempixel.com/100/100/people/3/"/>
      </f7-chip>
      <f7-chip text="Adam Smith">
        <img slot="media" src="http://lorempixel.com/100/100/people/7/"/>
      </f7-chip>
      <f7-chip text="Jennifer" media-bg-color="pink" media="J"></f7-chip>
      <f7-chip text="Chris" media-bg-color="yellow" media-text-color="black" media="C"></f7-chip>
      <f7-chip text="Kate" media-bg-color="red" media="K"></f7-chip>
    </f7-block>
    <f7-block-title>Deletable Chips / Tags</f7-block-title>
    <f7-block strong>
      <f7-chip text="Example Chip" deleteable @click="deleteChip"></f7-chip>
      <f7-chip text="Chris" media="C" media-bg-color="orange" text-color="black" deleteable @click="deleteChip"></f7-chip>
      <f7-chip text="Jane Doe" deleteable @click="deleteChip">
        <img slot="media" src="http://lorempixel.com/100/100/people/9/"/>
      </f7-chip>
      <f7-chip text="One More Chip" deleteable @click="deleteChip"></f7-chip>
      <f7-chip text="Jennifer" media-bg-color="pink" media="J" deleteable @click="deleteChip"></f7-chip>
      <f7-chip text="Adam Smith" deleteable @click="deleteChip">
        <img slot="media" src="http://lorempixel.com/100/100/people/7/"/>
      </f7-chip>
    </f7-block>
    <f7-block-title>Color Chips</f7-block-title>
    <f7-block strong>
      <f7-chip text="Red Chip" color="red"></f7-chip>
      <f7-chip text="Green Chip" color="green"></f7-chip>
      <f7-chip text="Blue Chip" color="blue"></f7-chip>
      <f7-chip text="Orange Chip" color="orange"></f7-chip>
      <f7-chip text="Pink Chip" color="pink"></f7-chip>
    </f7-block>
  </f7-page>
);

<script>


  export default {
    components: {
      f7Navbar,
      f7Page,
      f7BlockTitle,
      f7Chip,
      f7Block,
      f7Icon,
    },
    methods: {
      deleteChip(e) {
        const $$ = this.$$;
        const app = this.$f7;
        app.dialog.confirm('Do you want to delete this tiny demo Chip?', () => {
          $$(e.target).parents('.chip').remove();
        });
      },
    },
  };
</script>
