// react/kitchen-sink/src/pages/fab-morph.jsx
import React from 'react';
import { Navbar, Page, BlockTitle, Block, Fab, Link, Toolbar, Icon } from 'framework7-react';

export default () => (
  <Page pageContent={false}>
    <Navbar title="Floating Action Button Morph" backLink="Back"></Navbar>
    <Toolbar tabbar labels bottomMd className="fab-morph-target">
      <Link tabLink tabLinkActive iconIfIos="f7:email_fill" iconIfMd="material:email" text="Inbox"/>
      <Link tabLink iconIfIos="f7:today" iconIfMd="material:today" text="Calendar"/>
      <Link tabLink iconIfIos="f7:cloud" iconIfMd="material:file_upload" text="Upload"/>
    </Toolbar>
    <Fab position="right-bottom" morphTo=".toolbar.fab-morph-target">
      <Icon ifIos="f7:add" ifMd="material:add"></Icon>
    </Fab>
    <Fab position="left-bottom" morphTo=".demo-fab-sheet.fab-morph-target">
      <Icon ifIos="f7:add" ifMd="material:add"></Icon>
    </Fab>
    <Fab position="center-bottom" morphTo=".demo-fab-fullscreen-sheet.fab-morph-target">
      <Icon ifIos="f7:add" ifMd="material:add"></Icon>
    </Fab>
    <div className="list links-list demo-fab-sheet fab-morph-target">
      <ul>
        <li><a href="#" className="fab-close">Link 1</a></li>
        <li><a href="#" className="fab-close">Link 2</a></li>
        <li><a href="#" className="fab-close">Link 3</a></li>
        <li><a href="#" className="fab-close">Link 4</a></li>
      </ul>
    </div>
    <div className="demo-fab-fullscreen-sheet fab-morph-target">
      <BlockTitle>Choose Something</BlockTitle>
      <div className="list links-list">
        <ul>
          <li><a href="#" className="fab-close">Link 1</a></li>
          <li><a href="#" className="fab-close">Link 2</a></li>
          <li><a href="#" className="fab-close">Link 3</a></li>
          <li><a href="#" className="fab-close">Link 4</a></li>
        </ul>
      </div>
    </div>
    <div className="page-content">
      <Block>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, quo rem beatae, delectus eligendi est saepe molestias perferendis suscipit, commodi labore ipsa non quasi eum magnam neque ducimus! Quasi, numquam.</p>
        <p>Maiores culpa, itaque! Eaque natus ab cum ipsam numquam blanditiis a, quia, molestiae aut laudantium recusandae ipsa. Ad iste ex asperiores ipsa, mollitia perferendis consectetur quam eaque, voluptate laboriosam unde.</p>
        <p>Sed odit quis aperiam temporibus vitae necessitatibus, laboriosam, exercitationem dolores odio sapiente provident. Accusantium id, itaque aliquam libero ipsum eos fugiat distinctio laboriosam exercitationem sequi facere quas quidem magnam reprehenderit.</p>
        <p>Pariatur corporis illo, amet doloremque. Ab veritatis sunt nisi consectetur error modi, nam illo et nostrum quia aliquam ipsam vitae facere voluptates atque similique odit mollitia, rerum placeat nobis est.</p>
        <p>Et impedit soluta minus a autem adipisci cupiditate eius dignissimos nihil officia dolore voluptatibus aperiam reprehenderit esse facilis labore qui, officiis consectetur. Ipsa obcaecati aspernatur odio assumenda veniam, ipsum alias.</p>
      </Block>
      <Block>
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa ipsa debitis sed nihil eaque dolore cum iste quibusdam, accusamus doloribus, tempora quia quos voluptatibus corporis officia at quas dolorem earum!</p>
        <p>Quod soluta eos inventore magnam suscipit enim at hic in maiores temporibus pariatur tempora minima blanditiis vero autem est perspiciatis totam dolorum, itaque repellat? Nobis necessitatibus aut odit aliquam adipisci.</p>
        <p>Tenetur delectus perspiciatis ex numquam, unde corrupti velit! Quam aperiam, animi fuga veritatis consectetur, voluptatibus atque consequuntur dignissimos itaque, sint impedit cum cumque at. Adipisci sint, iusto blanditiis ullam? Vel?</p>
        <p>Dignissimos velit officia quibusdam! Eveniet beatae, aut, omnis temporibus consequatur expedita eaque aliquid quos accusamus fugiat id iusto autem obcaecati repellat fugit cupiditate suscipit natus quas doloribus? Temporibus necessitatibus, libero.</p>
        <p>Architecto quisquam ipsa fugit facere, repudiandae asperiores vitae obcaecati possimus, labore excepturi reprehenderit consectetur perferendis, ullam quidem hic, repellat fugiat eaque fuga. Consectetur in eveniet, deleniti recusandae omnis eum quas?</p>
        <p>Quos nulla consequatur quo, officia quaerat. Nulla voluptatum, assumenda quibusdam, placeat cum aut illo deleniti dolores commodi odio ipsam, recusandae est pariatur veniam repudiandae blanditiis. Voluptas unde deleniti quisquam, nobis?</p>
        <p>Atque qui quaerat quasi officia molestiae, molestias totam incidunt reprehenderit laboriosam facilis veritatis, non iusto! Dolore ipsam obcaecati voluptates minima maxime minus qui mollitia facere. Nostrum esse recusandae voluptatibus eligendi.</p>
      </Block>
    </div>
  </Page>
);

// react/kitchen-sink/src/pages/fab-morph.vue
<template>
  <Page pageContent={false}>
    <Navbar title="Floating Action Button Morph" backLink="Back"></Navbar>
    <div className="toolbar tabbar tabbar-labels toolbar-bottom-md fab-morph-target">
      <div className="toolbar-inner">
        <a className="tab-link tabLinkActive">
          <i className="icon f7-icons ios-only">email</i>
          <i className="icon icon-fill f7-icons ios-only">email_fill</i>
          <i className="icon material-icons md-only">email</i>
          <span className="tabbar-label">Inbox</span>
        </a>
        <a className="tab-link">
          <i className="icon f7-icons ios-only">today</i>
          <i className="icon icon-fill f7-icons ios-only">today_fill</i>
          <i className="icon material-icons md-only">today</i>
          <span className="tabbar-label">Calendar</span>
        </a>
        <a className="tab-link">
          <i className="icon f7-icons ios-only">cloud</i>
          <i className="icon icon-fill f7-icons ios-only">cloud_fill</i>
          <i className="icon material-icons md-only">file_upload</i>
          <span className="tabbar-label">Upload</span>
        </a>
      </div>
    </div>
    <div className="fab fab-right-bottom fab-morph" data-morph-to=".toolbar.fab-morph-target">
      <a href="#">
        <i className="icon f7-icons ios-only">add</i>
        <i className="icon material-icons md-only">add</i>
      </a>
    </div>
    <div className="fab fab-left-bottom fab-morph" data-morph-to=".demo-fab-sheet.fab-morph-target">
      <a href="#">
        <i className="icon f7-icons ios-only">add</i>
        <i className="icon material-icons md-only">add</i>
      </a>
    </div>
    <div className="fab fab-center-bottom fab-morph" data-morph-to=".demo-fab-fullscreen-sheet.fab-morph-target">
      <a href="#">
        <i className="icon f7-icons ios-only">add</i>
        <i className="icon material-icons md-only">add</i>
      </a>
    </div>
    <div className="list links-list demo-fab-sheet fab-morph-target">
      <ul>
        <li><a href="#" className="fab-close">Link 1</a></li>
        <li><a href="#" className="fab-close">Link 2</a></li>
        <li><a href="#" className="fab-close">Link 3</a></li>
        <li><a href="#" className="fab-close">Link 4</a></li>
      </ul>
    </div>
    <div className="demo-fab-fullscreen-sheet fab-morph-target">
      <BlockTitle>Choose Something</BlockTitle>
      <div className="list links-list">
        <ul>
          <li><a href="#" className="fab-close">Link 1</a></li>
          <li><a href="#" className="fab-close">Link 2</a></li>
          <li><a href="#" className="fab-close">Link 3</a></li>
          <li><a href="#" className="fab-close">Link 4</a></li>
        </ul>
      </div>
    </div>
    <div className="page-content">
      <div className="block">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quia, quo rem beatae, delectus eligendi est saepe molestias perferendis suscipit, commodi labore ipsa non quasi eum magnam neque ducimus! Quasi, numquam.</p>
        <p>Maiores culpa, itaque! Eaque natus ab cum ipsam numquam blanditiis a, quia, molestiae aut laudantium recusandae ipsa. Ad iste ex asperiores ipsa, mollitia perferendis consectetur quam eaque, voluptate laboriosam unde.</p>
        <p>Sed odit quis aperiam temporibus vitae necessitatibus, laboriosam, exercitationem dolores odio sapiente provident. Accusantium id, itaque aliquam libero ipsum eos fugiat distinctio laboriosam exercitationem sequi facere quas quidem magnam reprehenderit.</p>
        <p>Pariatur corporis illo, amet doloremque. Ab veritatis sunt nisi consectetur error modi, nam illo et nostrum quia aliquam ipsam vitae facere voluptates atque similique odit mollitia, rerum placeat nobis est.</p>
        <p>Et impedit soluta minus a autem adipisci cupiditate eius dignissimos nihil officia dolore voluptatibus aperiam reprehenderit esse facilis labore qui, officiis consectetur. Ipsa obcaecati aspernatur odio assumenda veniam, ipsum alias.</p>
      </div>
      <div className="block">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Culpa ipsa debitis sed nihil eaque dolore cum iste quibusdam, accusamus doloribus, tempora quia quos voluptatibus corporis officia at quas dolorem earum!</p>
        <p>Quod soluta eos inventore magnam suscipit enim at hic in maiores temporibus pariatur tempora minima blanditiis vero autem est perspiciatis totam dolorum, itaque repellat? Nobis necessitatibus aut odit aliquam adipisci.</p>
        <p>Tenetur delectus perspiciatis ex numquam, unde corrupti velit! Quam aperiam, animi fuga veritatis consectetur, voluptatibus atque consequuntur dignissimos itaque, sint impedit cum cumque at. Adipisci sint, iusto blanditiis ullam? Vel?</p>
        <p>Dignissimos velit officia quibusdam! Eveniet beatae, aut, omnis temporibus consequatur expedita eaque aliquid quos accusamus fugiat id iusto autem obcaecati repellat fugit cupiditate suscipit natus quas doloribus? Temporibus necessitatibus, libero.</p>
        <p>Architecto quisquam ipsa fugit facere, repudiandae asperiores vitae obcaecati possimus, labore excepturi reprehenderit consectetur perferendis, ullam quidem hic, repellat fugiat eaque fuga. Consectetur in eveniet, deleniti recusandae omnis eum quas?</p>
        <p>Quos nulla consequatur quo, officia quaerat. Nulla voluptatum, assumenda quibusdam, placeat cum aut illo deleniti dolores commodi odio ipsam, recusandae est pariatur veniam repudiandae blanditiis. Voluptas unde deleniti quisquam, nobis?</p>
        <p>Atque qui quaerat quasi officia molestiae, molestias totam incidunt reprehenderit laboriosam facilis veritatis, non iusto! Dolore ipsam obcaecati voluptates minima maxime minus qui mollitia facere. Nostrum esse recusandae voluptatibus eligendi.</p>
      </div>
    </div>
  </Page>
</template>
<script>
  import React from 'react';
  import { Navbar, Page, BlockTitle } from 'framework7-react';

  export default {
    components: {
      Navbar,
      Page,
      BlockTitle,
    },
  };
</script>
