// src/react/shared/router-open-in.jsx
import React from 'react';
import Popup from '../components/popup.js';
import View from '../components/view.js';
import LoginScreen from '../components/login-screen.js';
import Sheet from '../components/sheet.js';
import Popover from '../components/popover.js';
import Panel from '../components/panel.js';

export const routerOpenIn = (router, url, options) => {
  const navigateOptions = {
    url,
    route: {
      path: url,
      options: {
        ...options,
        openIn: undefined,
      },
    },
  };
  const params = {
    ...options,
  };

  if (options.openIn === 'popup') {
    params.component = function DynamicPopup() {
      return (
        <Popup className="popup-router-open-in" data-url={url}>
          <View linksView={router.view.selector} url={url} ignoreOpenIn />
        </Popup>
      );
    };
    navigateOptions.route.popup = params;
  }
  if (options.openIn === 'loginScreen') {
    params.component = function DynamicPopover() {
      return (
        <LoginScreen className="login-screen-router-open-in" data-url={url}>
          <View linksView={router.view.selector} url={url} ignoreOpenIn />
        </LoginScreen>
      );
    };
    navigateOptions.route.loginScreen = params;
  }
  if (options.openIn === 'sheet') {
    params.component = function DynamicSheet() {
      return (
        <Sheet className="sheet-modal-router-open-in" data-url={url}>
          <View linksView={router.view.selector} url={url} ignoreOpenIn />
        </Sheet>
      );
    };
    navigateOptions.route.sheet = params;
  }
  if (options.openIn === 'popover') {
    params.targetEl = options.clickedEl || options.targetEl;
    params.component = function DynamicPopover() {
      return (
        <Popover
          className="popover-router-open-in"
          targetEl={options.clickedEl || options.targetEl}
          data-url={url}
        >
          <View linksView={router.view.selector} url={url} ignoreOpenIn />
        </Popover>
      );
    };
    navigateOptions.route.popover = params;
  }
  if (options.openIn.indexOf('panel') >= 0) {
    const parts = options.openIn.split(':');
    const side = parts[1] || 'left';
    const effect = parts[2] || 'cover';
    params.component = function DynamicPanel() {
      return (
        <Panel side={side} effect={effect} className="panel-router-open-in" data-url={url}>
          <View linksView={router.view.selector} url={url} ignoreOpenIn />
        </Panel>
      );
    };
    navigateOptions.route.panel = params;
  }
  return router.navigate(navigateOptions);
};

// src/svelte/shared/router-open-in-component.svelte
<script>
  import Popup from '../components/popup.svelte';
  import View from '../components/view.svelte';
  import LoginScreen from '../components/login-screen.svelte';
  import Sheet from '../components/sheet.svelte';
  import Popover from '../components/popover.svelte';
  import Panel from '../components/panel.svelte';

  export let openIn;
  export let url;
  export let viewSelector;
  export let targetEl;
  export let side;
  export let effect;
</script>

{#if openIn === 'popup'}
  <Popup className="popup-router-open-in" data-url={url}>
    <View linksView={viewSelector} {url} ignoreOpenIn />
  </Popup>
{/if}
{#if openIn === 'loginScreen'}
  <LoginScreen className="login-screen-router-open-in" data-url={url}>
    <View linksView={viewSelector} {url} ignoreOpenIn />
  </LoginScreen>
{/if}
{#if openIn === 'sheet'}
  <Sheet className="sheet-modal-router-open-in" data-url={url}>
    <View linksView={viewSelector} {url} ignoreOpenIn />
  </Sheet>
{/if}
{#if openIn === 'popover'}
  <Popover className="popover-router-open-in" {targetEl} data-url={url}>
    <View linksView={viewSelector} {url} ignoreOpenIn />
  </Popover>
{/if}
{#if openIn.indexOf('panel') === 0}
  <Panel {side} {effect} className="panel-router-open-in" data-url={url}>
    <View linksView={viewSelector} {url} ignoreOpenIn />
  </Panel>
{/if}
