// src/phenome/components/accordion.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  props: Mixins.colorProps,
  name: 'f7-accordion',
  render() {
    const classes = Utils.classNames(
      this.props.className,
      {
        'accordion-list': true,
      },
      Mixins.colorClasses(this),
    );
    return (
      <div id={this.props.id} style={this.props.style} className={classes}>
        <slot />
      </div>
    );
  },
};

// src/vue/components/accordion.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-accordion',
  props: {
    accordionOpposite: Boolean,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'accordion-list',
        props.accordionOpposite && 'accordion-opposite',
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>
