// src/phenome/components/accordion-content.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  props: Mixins.colorProps,
  name: 'f7-accordion-content',
  render() {
    const classes = Utils.classNames(
      this.props.className,
      {
        'accordion-item-content': true,
      },
      Mixins.colorClasses(this),
    );
    return (
      <div id={this.props.id} style={this.props.style} className={classes}>
        <slot />
      </div>
    );
  },
};

// src/vue/components/accordion-content.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-accordion-content',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('accordion-item-content', colorClasses(props)));
    return { classes };
  },
};
</script>
