// src/svelte/components/actions-label.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  import { colorClasses } from '../shared/mixins.js';
  import { classNames, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let bold = false;

  $: classes = classNames(
    className,
    'actions-label',
    {
      'actions-button-bold': bold,
    },
    colorClasses($$props),
  );

  function onClick() {
    emit('click');
  }
</script>

<div class={classes} on:click={onClick} {...restProps($$restProps)}>
  <slot />
</div>

// src/vue/components/actions-label.vue
<template>
  <div :class="classes" @click="onClick">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-actions-label',
  props: {
    bold: Boolean,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const onClick = (e) => {
      emit('click', e);
    };
    const classes = computed(() =>
      classNames(
        'actions-label',
        {
          'actions-button-bold': props.bold,
        },
        colorClasses(props),
      ),
    );
    return { classes, onClick };
  },
};
</script>
