// packages/svelte/components/appbar.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let noShadow = undefined;
  export let noHairline = undefined;
  export let inner = true;
  export let innerClass = undefined;
  export let innerClassName = undefined;

  $: classes = Utils.classNames(
    className,
    'appbar',
    {
      'no-shadow': noShadow,
      'no-hairline': noHairline,
    },
    Mixins.colorClasses($$props),
  );

  $: innerClasses = Utils.classNames(
    'appbar-inner',
    innerClass,
    innerClassName,
  );
</script>

<div
  id={id}
  style={style}
  class={classes}
>
  <slot name="before-inner" />
  {#if inner}
    <div class={innerClasses}>
      <slot />
    </div>
  {:else}
    <slot />
  {/if}
  <slot name="after-inner" />
</div>

// src/vue/components/appbar.vue
<template>
  <div :class="classes">
    <slot name="before-inner" />
    <div v-if="inner" :class="innerClasses">
      <slot />
    </div>
    <slot v-else />
    <slot name="after-inner" />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-appbar',
  props: {
    noShadow: Boolean,
    noHairline: Boolean,
    inner: {
      type: Boolean,
      default: true,
    },
    innerClass: String,
    innerClassName: String,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'appbar',
        {
          'no-shadow': props.noShadow,
          'no-hairline': props.noHairline,
        },
        colorClasses(props),
      ),
    );
    const innerClasses = computed(() =>
      classNames('appbar-inner', props.innerClass, props.innerClassName),
    );
    return { classes, innerClasses };
  },
};
</script>
