// packages/svelte/components/block-title.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;
  export let large = false;
  export let medium = false;

  let className = undefined;
  export { className as class };

  $: classes = Utils.classNames(
    className,
    'block-title',
    {
      'block-title-large': large,
      'block-title-medium': medium,
    },
    Mixins.colorClasses($$props),
  );
</script>

<div
  id={id}
  style={style}
  class={classes}
>
  <slot />
</div>

// src/vue/components/block-title.vue
<template>
  <div :class="classes" :medium="medium">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-block-title',
  props: {
    large: Boolean,
    medium: Boolean,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => {
      const { large, medium } = props;
      return classNames(
        'block-title',
        {
          'block-title-large': large,
          'block-title-medium': medium,
        },
        colorClasses(props),
      );
    });

    return {
      classes,
    };
  },
};
</script>
