// src/phenome/components/block-title.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-block-title',
  props: Mixins.colorProps,
  render() {
    const classes = Utils.classNames(
      this.props.className,
      'block-title',
      Mixins.colorClasses(this),
    );
    return (<div id={this.props.id} style={this.props.style} className={classes}><slot /></div>);
  },
};

// src/vue/components/block-title.vue
<template>
  <div :class="classes" :medium="medium">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-block-title',
  props: {
    large: Boolean,
    medium: Boolean,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => {
      const { large, medium } = props;
      return classNames(
        'block-title',
        {
          'block-title-large': large,
          'block-title-medium': medium,
        },
        colorClasses(props),
      );
    });

    return {
      classes,
    };
  },
};
</script>
