// src/phenome/components/card-content.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-card-content',
  props: {
    padding: {
      type: Boolean,
      default: true,
    },
    ...Mixins.colorProps,
  },
  render() {
    const {
      id,
      className,
      style,
      padding,
    } = this.props;

    const classes = Utils.classNames(
      className,
      {
        'card-content': true,
        'card-content-padding': padding,
      },
      Mixins.colorClasses(this),
    );

    return (<div id={id} style={style} className={classes}><slot /></div>);
  },
};

// src/vue/components/card-content.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-card-content',
  props: {
    padding: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'card-content',
        {
          'card-content-padding': props.padding,
        },
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>
