// packages/svelte/components/fab-backdrop.svelte
<script>
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';

  let className = undefined;
  export { className as class };

  export let f7Slot = 'fixed';

  $: classes = Utils.classNames(
    className,
    'fab-backdrop',
  );
</script>

<div
  class={classes}
  data-f7-slot={f7Slot}
  {...restProps($$restProps)}
></div>

// src/vue/components/fab-backdrop.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-fab-backdrop',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('fab-backdrop', colorClasses(props)));
    return { classes };
  },
};
</script>
