// src/react/components/fab.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getDataAttrs, getSlots, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';
import { useTooltip } from '../shared/use-tooltip';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  morphTo? : string;
  href? : boolean | string;
  target? : string;
  text? : string;
  position? : string;
  tooltip? : string;
  tooltipTrigger? : string;
  onClick? : (event?: any) => void;
  COLOR_PROPS
*/

const Fab = forwardRef((props, ref) => {
  const { className, id, style, morphTo, href, target, text, position = 'right-bottom' } = props;
  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);
  const linkElRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useTooltip(elRef, props);

  let hrefComputed = href;
  if (hrefComputed === true) hrefComputed = '#';
  if (hrefComputed === false) hrefComputed = undefined; // no href attribute

  const linkChildren = [];
  const rootChildren = [];

  const { link: linkSlots, default: defaultSlots, root: rootSlots, text: textSlots } = getSlots(
    props,
  );

  if (defaultSlots) {
    for (let i = 0; i < defaultSlots.length; i += 1) {
      const child = defaultSlots[i];
      let isRoot;
      const tag = child.type && (child.type.displayName || child.type.name);
      if (tag === 'FabButtons' || tag === 'f7-fab-buttons') isRoot = true;
      if (isRoot) rootChildren.push(child);
      else linkChildren.push(child);
    }
  }
  let textEl;
  if (text || (textSlots && textSlots.length)) {
    textEl = <div className="fab-text">{text || textSlots}</div>;
  }
  let linkEl;
  if (linkChildren.length || (linkSlots && linkSlots.length) || textEl) {
    linkEl = (
      <a ref={linkElRef} target={target} href={hrefComputed} onClick={onClick}>
        {linkChildren}
        {textEl}
        {linkSlots}
      </a>
    );
  }

  const classes = classNames(
    className,
    'fab',
    `fab-${position}`,
    {
      'fab-morph': morphTo,
      'fab-extended': typeof textEl !== 'undefined',
    },
    colorClasses(props),
  );

  return (
    <div
      id={id}
      style={style}
      className={classes}
      data-morph-to={morphTo}
      ref={elRef}
      {...dataAttrs}
    >
      {linkEl}
      {rootChildren}
      {rootSlots}
    </div>
  );
});

Fab.displayName = 'f7-fab';

export default Fab;

// src/vue/components/fab.vue
<script>
import { h, computed, ref } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';

export default {
  name: 'f7-fab',
  props: {
    morphTo: String,
    href: [Boolean, String],
    target: String,
    text: String,
    position: {
      type: String,
      default: 'right-bottom',
    },
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit, slots }) {
    const elRef = ref(null);

    const onClick = (e) => {
      emit('click', e);
    };

    useTooltip(elRef, props);

    const hrefComputed = computed(() => {
      let href = props.href;
      if (href === true) href = '#';
      if (href === false) href = undefined; // no href attribute
      return href;
    });

    return () => {
      const linkChildren = [];
      const rootChildren = [];
      let textEl;
      let linkEl;

      const { link: linkSlots, default: defaultSlots, root: rootSlots, text: textSlots } = slots;

      if (defaultSlots) {
        defaultSlots().forEach((vnode) => {
          if (typeof vnode === 'undefined') return;
          const tag = vnode.type && vnode.type.name ? vnode.type.name : vnode.type;
          if (tag === 'FabButtons' || tag === 'f7-fab-buttons') rootChildren.push(vnode);
          else linkChildren.push(vnode);
        });
      }
      if (props.text || textSlots) {
        textEl = h('div', { class: 'fab-text' }, [props.text, textSlots && textSlots()]);
      }
      if (linkChildren.length || linkSlots || textEl) {
        linkEl = h('a', { target: props.target, href: hrefComputed.value, onClick }, [
          linkChildren,
          textEl,
          linkSlots && linkSlots(),
        ]);
      }
      const classes = classNames(
        'fab',
        `fab-${props.position}`,
        {
          'fab-morph': props.morphTo,
          'fab-extended': typeof textEl !== 'undefined',
        },
        colorClasses(props),
      );
      return h(
        'div',
        {
          class: classes,
          'data-morph-to': props.morphTo,
          ref: elRef,
        },
        [linkEl, rootChildren, rootSlots && rootSlots()],
      );
    };
  },
};
</script>
