// src/svelte/components/list-button.svelte
<script>
  import {
    colorClasses,
    routerAttrs,
    routerClasses,
    actionsAttrs,
    actionsClasses,
  } from '../shared/mixins.js';
  import { classNames, extend, isStringProp } from '../shared/utils.js';
  import { useTooltip } from '../shared/use-tooltip.js';
  import { useRouteProps } from '../shared/use-route-props.js';

  let {
    class: className,
    title = undefined,
    text = undefined,
    tabLink = undefined,
    tabLinkActive = false,
    link = undefined,
    href = undefined,
    target = undefined,
    tooltip = undefined,
    tooltipTrigger = undefined,
    routeProps = undefined,
    children,
    ...restProps
  } = $props();

  let el = $state(null);

  const hrefComputed = $derived(
    typeof link === 'boolean' && typeof href === 'boolean' ? '#' : link || href,
  );

  const attrs = $derived(
    extend(
      {
        href: hrefComputed,
        target,
        'data-tab': (isStringProp(tabLink) && tabLink) || undefined,
      },
      routerAttrs(restProps),
      actionsAttrs(restProps),
    ),
  );

  const classes = $derived(
    classNames(
      {
        'list-button': true,
        'tab-link': tabLink || tabLink === '',
        'tab-link-active': tabLinkActive,
      },
      colorClasses(restProps),
      routerClasses(restProps),
      actionsClasses(restProps),
    ),
  );

  function onClick() {
    restProps.onClick?.();
    restProps.onclick?.();
  }
</script>

<li
  class={className}
  {...restProps}
  bind:this={el}
  use:useRouteProps={routeProps}
  use:useTooltip={{ tooltip, tooltipTrigger }}
>
  <a class={classes} {...attrs} onclick={onClick}>
    {#if typeof title === 'function'}
      {@render title?.()}
    {:else if typeof title !== 'undefined'}
      {title}
    {/if}
    {#if typeof text === 'function'}
      {@render text?.()}
    {:else if typeof text !== 'undefined'}
      {text}
    {/if}
    {@render children?.()}
  </a>
</li>

// src/vue/components/list-button.vue
<template>
  <li>
    <a ref="linkElRef" :class="linkClasses" v-bind="linkAttrs" @click="onClick">
      {{ title }}
      {{ text }}
      <slot />
    </a>
  </li>
</template>
<script>
import { computed, ref } from 'vue';
import { classNames, isStringProp } from '../shared/utils.js';
import {
  colorClasses,
  colorProps,
  actionsAttrs,
  actionsClasses,
  actionsProps,
  routerAttrs,
  routerClasses,
  routerProps,
} from '../shared/mixins.js';
import { useTooltip } from '../shared/use-tooltip.js';
import { useRouteProps } from '../shared/use-route-props.js';

export default {
  name: 'f7-list-button',
  props: {
    title: [String, Number],
    text: [String, Number],
    tabLink: [Boolean, String],
    tabLinkActive: Boolean,
    link: [Boolean, String],
    href: [Boolean, String],
    target: String,
    tooltip: String,
    tooltipTrigger: String,
    ...colorProps,
    ...actionsProps,
    ...routerProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const linkElRef = ref(null);

    const onClick = (e) => {
      emit('click', e);
    };
    useTooltip(linkElRef, props);

    useRouteProps(linkElRef, props);

    const linkAttrs = computed(() => {
      return {
        href:
          typeof props.link === 'boolean' && typeof props.href === 'boolean'
            ? '#'
            : props.link || props.href,
        target: props.target,
        'data-tab': isStringProp(props.tabLink) && props.tabLink,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    const linkClasses = computed(() => {
      return classNames({
        'list-button': true,
        'tab-link': props.tabLink || props.tabLink === '',
        'tab-link-active': props.tabLinkActive,
        ...colorClasses(props),
        ...routerClasses(props),
        ...actionsClasses(props),
      });
    });

    return { linkAttrs, linkClasses, onClick, linkElRef };
  },
};
</script>
