// src/phenome/components/list-group.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-list-group',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    mediaList: Boolean,
    sortable: Boolean,
    sortableTapHold: Boolean,
    sortableMoveElements: {
      type: Boolean,
      default: undefined,
    },
    ...Mixins.colorProps,
  },
  render() {
    const self = this;
    const props = self.props;
    const {
      className,
      id,
      style,
      mediaList,
      sortable,
      sortableMoveElements,
    } = props;

    const classes = Utils.classNames(
      className,
      'list-group',
      {
        'media-list': mediaList,
        sortable,
        'sortable-tap-hold': sortableTapHold,
      },
      Mixins.colorClasses(props),
    );

    return (
      <div id={id} style={style} className={classes} data-sortable-move-elements={typeof sortableMoveElements !== 'undefined' ? sortableMoveElements.toString() : undefined}>
        <ul>
          <slot />
        </ul>
      </div>
    );
  },
};

// src/vue/components/list-group.vue
<template>
  <div
    :class="classes"
    :data-sortable-move-elements="
      typeof sortableMoveElements !== 'undefined' ? sortableMoveElements.toString() : undefined
    "
  >
    <ul>
      <slot />
    </ul>
  </div>
</template>
<script>
import { computed, provide, inject } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-list-group',
  props: {
    mediaList: Boolean,
    sortable: Boolean,
    sortableOpposite: Boolean,
    sortableTapHold: Boolean,
    sortableMoveElements: {
      type: Boolean,
      default: undefined,
    },
    ...colorProps,
  },
  setup(props) {
    const ListContext = inject('ListContext', {
      listIsMedia: props.mediaList,
      listIsSimple: props.simpleList,
      listIsSortable: props.sortable,
      listIsSortableOpposite: props.sortableOpposite,
    });

    provide('ListContext', {
      listIsMedia: props.mediaList || ListContext.listIsMedia,
      listIsSimple: props.simpleList || ListContext.listIsSimple,
      listIsSortable: props.sortable || ListContext.listIsSortable,
      listIsSortableOpposite: props.sortableOpposite || ListContext.listIsSortableOpposite,
    });

    const classes = computed(() =>
      classNames(
        'list-group',
        {
          'media-list': props.mediaList,
          sortable: props.sortable,
          'sortable-tap-hold': props.sortableTapHold,
          'sortable-opposite': props.sortableOpposite,
        },
        colorClasses(props),
      ),
    );

    return { classes };
  },
};
</script>
