// src/svelte/components/login-screen-title.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  $: classes = classNames(className, 'login-screen-title', colorClasses($$props));
</script>

<div class={classes} {...restProps($$restProps)}>
  <slot />
</div>

// src/vue/components/login-screen-title.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-login-screen-title',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('login-screen-title', colorClasses(props)));
    return { classes };
  },
};
</script>
