// src/svelte/components/menu.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  $: classes = classNames(className, 'menu', colorClasses($$props));
</script>

<div class={classes} {...restProps($$restProps)}>
  <div class="menu-inner">
    <slot />
  </div>
</div>

// src/vue/components/menu.vue
<template>
  <div :class="classes">
    <div class="menu-inner">
      <slot />
    </div>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-menu',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('menu', colorClasses(props)));
    return { classes };
  },
};
</script>
