// src/react/components/_old/messagebar-sheet.jsx
import Utils from '../shared/utils';
import Mixins from '../shared/mixins';

export default {
  name: 'f7-messagebar-sheet',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    ...Mixins.colorProps,
  },
  render() {
    const props = this.props;
    const {
      className,
      id,
      style,
    } = props;

    const classes = Utils.classNames(
      className,
      'messagebar-sheet',
      Mixins.colorClasses(props),
    );
    return (<div id={id} style={style} className={classes}><slot /></div>);
  },
};

// src/vue/components/messagebar-sheet.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-messagebar-sheet',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = classNames('messagebar-sheet', colorClasses(props));
    return { classes };
  },
};
</script>
