// src/phenome/components/messagebar-attachments.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-messagebar-attachments',
  props: Mixins.colorProps,
  render() {
    const classes = Utils.classNames(
      this.props.className,
      'messagebar-attachments',
      Mixins.colorClasses(this),
    );
    return (<div id={this.props.id} style={this.props.style} className={classes}><slot /></div>);
  },
};

// src/vue/components/messagebar-attachments.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-messagebar-attachments',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = classNames('messagebar-attachments', colorClasses(props));
    return { classes };
  },
};
</script>
