// src/svelte/components/messagebar-sheet-image.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { colorClasses } from '../shared/mixins';
  import { classNames, createEmitter } from '../shared/utils';
  import { restProps } from '../shared/rest-props';

  const emit = createEmitter(createEventDispatcher, $$props);

  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let image = undefined;
  export let checked = false;

  $: classes = classNames(className, 'messagebar-sheet-image', 'checkbox', colorClasses($$props));

  $: styles = `${image ? `background-image: url(${image});` : ''}${style || ''}`;

  function onChange(event) {
    if (event.target.checked) emit('checked', [event]);
    else emit('unchecked', [event]);
    emit('change', [event]);
    checked = event.target.checked;
  }
</script>

<label class={classes} style={styles} {...restProps($$restProps)}>
  <input type="checkbox" {checked} on:change={onChange} />
  <i class="icon icon-checkbox" />
  <slot />
</label>

// src/vue/components/messagebar-sheet-image.vue
<template>
  <label :class="classes" :style="styles">
    <input type="checkbox" :checked="checked" @change="onChange" />
    <i class="icon icon-checkbox" />
    <slot />
  </label>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-messagebar-sheet-image',
  props: {
    image: String,
    checked: Boolean,
    ...colorProps,
  },
  emits: ['checked', 'unchecked', 'change', 'update:checked'],
  setup(props, { emit }) {
    const onChange = (event) => {
      if (event.target.checked) emit('checked', event);
      else emit('unchecked', event);
      emit('update:checked', event.target.checked);
      emit('change', event);
    };
    const classes = computed(() =>
      classNames('messagebar-sheet-image', 'checkbox', colorClasses(props)),
    );
    const styles = computed(() => ({
      backgroundImage: props.image && `url(${props.image})`,
    }));
    return { classes, styles, onChange };
  },
};
</script>
