// src/react/components/message.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getDataAttrs, getSlots, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  text? : string
  name? : string
  avatar? : string
  type? : string
  image? : string
  header? : string
  footer? : string
  textHeader? : string
  textFooter? : string
  first? : boolean
  last? : boolean
  tail? : boolean
  sameName? : boolean
  sameHeader? : boolean
  sameFooter? : boolean
  sameAvatar? : boolean
  typing? : boolean
  COLOR_PROPS
  onClick? : (event?: any) => void
  onClickName? : (event?: any) => void
  onClickText? : (event?: any) => void
  onClickAvatar? : (event?: any) => void
  onClickHeader? : (event?: any) => void
  onClickFooter? : (event?: any) => void
  onClickBubble? : (event?: any) => void
*/

const Message = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    text,
    name,
    avatar,
    type = 'sent',
    image,
    header,
    footer,
    textHeader,
    textFooter,
    first,
    last,
    tail,
    sameName,
    sameHeader,
    sameFooter,
    sameAvatar,
    typing,
  } = props;
  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'click', event);
  };
  const onNameClick = (event) => {
    emit(props, 'click:name clickName', event);
  };
  const onTextClick = (event) => {
    emit(props, 'click:text clickText', event);
  };
  const onAvatarClick = (event) => {
    emit(props, 'click:avatar clickAvatar', event);
  };
  const onHeaderClick = (event) => {
    emit(props, 'click:header clickHeader', event);
  };
  const onFooterClick = (event) => {
    emit(props, 'click:footer clickFooter', event);
  };
  const onBubbleClick = (event) => {
    emit(props, 'click:bubble clickBubble', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const slots = getSlots(props);

  const classes = classNames(
    className,
    'message',
    {
      'message-sent': type === 'sent',
      'message-received': type === 'received',
      'message-typing': typing,
      'message-first': first,
      'message-last': last,
      'message-tail': tail,
      'message-same-name': sameName,
      'message-same-header': sameHeader,
      'message-same-footer': sameFooter,
      'message-same-avatar': sameAvatar,
    },
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...dataAttrs} onClick={onClick}>
      {slots.start}
      {(avatar || slots.avatar) && (
        <div
          className="message-avatar"
          style={{ backgroundImage: avatar && `url(${avatar})` }}
          onClick={onAvatarClick}
        >
          {slots.avatar}
        </div>
      )}
      <div className="message-content">
        {slots['content-start']}
        {(slots.name || name) && (
          <div className="message-name" onClick={onNameClick}>
            {slots.name || name}
          </div>
        )}
        {(slots.header || header) && (
          <div className="message-header" onClick={onHeaderClick}>
            {slots.header || header}
          </div>
        )}
        <div className="message-bubble" onClick={onBubbleClick}>
          {slots['bubble-start']}
          {(slots.image || image) && (
            <div className="message-image">{slots.image || <img src={image} />}</div>
          )}
          {(slots['text-header'] || textHeader) && (
            <div className="message-text-header">{slots['text-header'] || textHeader}</div>
          )}
          {(slots.text || text || typing) && (
            <div className="message-text" onClick={onTextClick}>
              {slots.text || text}
              {typing && (
                <div className="message-typing-indicator">
                  <div />
                  <div />
                  <div />
                </div>
              )}
            </div>
          )}
          {(slots['text-footer'] || textFooter) && (
            <div className="message-text-footer">{slots['text-footer'] || textFooter}</div>
          )}
          {slots['bubble-end']}
          {slots.default}
        </div>
        {(slots.footer || footer) && (
          <div className="message-footer" onClick={onFooterClick}>
            {slots.footer || footer}
          </div>
        )}
        {slots['content-end']}
      </div>
      {slots.end}
    </div>
  );
});

Message.displayName = 'f7-message';

export default Message;

// src/vue/components/message.vue
<template>
  <div :class="classes" @click="onClick">
    <slot name="start" />
    <div
      v-if="hasAvatar"
      class="message-avatar"
      :style="{ backgroundImage: avatar && `url(${avatar})` }"
      @click="onAvatarClick"
    >
      <slot name="avatar" />
    </div>
    <div class="message-content">
      <slot name="content-start" />
      <div v-if="hasName" class="message-name" @click="onNameClick">
        {{ name }}
        <slot name="name" />
      </div>
      <div v-if="hasHeader" class="message-header" @click="onHeaderClick">
        {header}
        <slot name="header" />
      </div>
      <div class="message-bubble" @click="onBubbleClick">
        <slot name="bubble-start" />
        <div v-if="hasImage" class="message-image">
          <slot name="image">
            <img :src="image" />
          </slot>
        </div>
        <div v-if="hasTextHeader" class="message-text-header">
          {{ textHeader }}
          <slot name="text-header" />
        </div>
        <div v-if="hasText" class="message-text" @click="onTextClick">
          {text}
          <slot name="text" />
          <div v-if="typing" class="message-typing-indicator">
            <div />
            <div />
            <div />
          </div>
        </div>
        <div v-if="hasTextFooter" class="message-text-footer">
          {{ textFooter }}
          <slot name="text-footer" />
        </div>
        <slot name="bubble-end" />
        <slot />
      </div>
      <div v-if="hasFooter" class="message-footer" @click="onFooterClick">
        {{ footer }}
        <slot name="footer" />
      </div>
      <slot name="content-end" />
    </div>
    <slot name="end" />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-message',
  props: {
    text: String,
    name: String,
    avatar: String,
    type: {
      type: String,
      default: 'sent',
    },
    image: String,
    header: String,
    footer: String,
    textHeader: String,
    textFooter: String,
    first: Boolean,
    last: Boolean,
    tail: Boolean,
    sameName: Boolean,
    sameHeader: Boolean,
    sameFooter: Boolean,
    sameAvatar: Boolean,
    typing: Boolean,
    ...colorProps,
  },
  emits: [
    'click',
    'click:name',
    'click:text',
    'click:avatar',
    'click:header',
    'click:footer',
    'click:bubble',
  ],
  setup(props, { emit, slots }) {
    const onClick = (event) => {
      emit('click', event);
    };
    const onNameClick = (event) => {
      emit('click:name', event);
    };
    const onTextClick = (event) => {
      emit('click:text', event);
    };
    const onAvatarClick = (event) => {
      emit('click:avatar', event);
    };
    const onHeaderClick = (event) => {
      emit('click:header', event);
    };
    const onFooterClick = (event) => {
      emit('click:footer', event);
    };
    const onBubbleClick = (event) => {
      emit('click:bubble', event);
    };
    const classes = computed(() =>
      classNames(
        'message',
        {
          'message-sent': props.type === 'sent',
          'message-received': props.type === 'received',
          'message-typing': props.typing,
          'message-first': props.first,
          'message-last': props.last,
          'message-tail': props.tail,
          'message-same-name': props.sameName,
          'message-same-header': props.sameHeader,
          'message-same-footer': props.sameFooter,
          'message-same-avatar': props.sameAvatar,
        },
        colorClasses(props),
      ),
    );
    const hasAvatar = computed(() => slots.avatar || props.avatar);
    const hasName = computed(() => slots.name || props.name);
    const hasHeader = computed(() => slots.header || props.header);
    const hasImage = computed(() => slots.image || props.image);
    const hasTextHeader = computed(() => slots['text-header'] || props.textHeader);
    const hasText = computed(() => slots.text || props.text || props.typing);
    const hasTextFooter = computed(() => slots['text-footer'] || props.textFooter);
    const hasFooter = computed(() => slots.footer || props.footer);

    return {
      classes,
      onClick,
      onNameClick,
      onTextClick,
      onAvatarClick,
      onHeaderClick,
      onFooterClick,
      onBubbleClick,
      hasAvatar,
      hasName,
      hasHeader,
      hasImage,
      hasTextHeader,
      hasText,
      hasTextFooter,
      hasFooter,
    };
  },
};
</script>
