// src/svelte/components/popup.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import { colorClasses } from '../shared/mixins';
  import { classNames, createEmitter } from '../shared/utils';
  import { restProps } from '../shared/rest-props';
  import { app, f7ready } from '../shared/f7';
  import { modalStateClasses } from '../shared/modal-state-classes';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let tabletFullscreen = undefined;
  export let opened = undefined;
  export let animate = undefined;
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let closeByBackdropClick = undefined;
  export let closeOnEscape = undefined;
  export let swipeToClose = false;
  export let swipeHandler = undefined;
  export let push = undefined;
  export let containerEl = undefined;

  let el;
  let f7Popup;

  const state = {
    isOpened: opened,
    isClosing: false,
  };

  export function instance() {
    return f7Popup;
  }

  $: classes = classNames(
    className,
    'popup',
    {
      'popup-tablet-fullscreen': tabletFullscreen,
      'popup-push': push,
    },
    modalStateClasses(state),
    colorClasses($$props),
  );

  function onSwipeStart(instance) {
    emit('popupSwipeStart', [instance]);
  }
  function onSwipeMove(instance) {
    emit('popupSwipeMove', [instance]);
  }
  function onSwipeEnd(instance) {
    emit('popupSwipeEnd', [instance]);
  }
  function onSwipeClose(instance) {
    emit('popupSwipeClose', [instance]);
  }

  function onOpen(instance) {
    Object.assign(state, {
      isOpened: true,
      isClosing: false,
    });
    emit('popupOpen', [instance]);
    opened = true;
  }
  function onOpened(instance) {
    emit('popupOpened', [instance]);
  }
  function onClose(instance) {
    Object.assign(state, {
      isOpened: false,
      isClosing: true,
    });
    emit('popupClose', [instance]);
  }
  function onClosed(instance) {
    Object.assign(state, {
      isClosing: false,
    });
    emit('popupClosed', [instance]);
    opened = false;
  }

  let initialWatched = false;
  function watchOpened(openedPassed) {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (!f7Popup) return;
    if (openedPassed) f7Popup.open();
    else f7Popup.close();
  }

  $: watchOpened(opened);

  onMount(() => {
    const popupParams = {
      el,
      on: {
        swipeStart: onSwipeStart,
        swipeMove: onSwipeMove,
        swipeEnd: onSwipeEnd,
        swipeClose: onSwipeClose,
        open: onOpen,
        opened: onOpened,
        close: onClose,
        closed: onClosed,
      },
    };
    if (typeof closeByBackdropClick !== 'undefined')
      popupParams.closeByBackdropClick = closeByBackdropClick;
    if (typeof closeOnEscape !== 'undefined') popupParams.closeOnEscape = closeOnEscape;
    if (typeof animate !== 'undefined') popupParams.animate = animate;
    if (typeof backdrop !== 'undefined') popupParams.backdrop = backdrop;
    if (typeof backdropEl !== 'undefined') popupParams.backdropEl = backdropEl;
    if (typeof swipeToClose !== 'undefined') popupParams.swipeToClose = swipeToClose;
    if (typeof swipeHandler !== 'undefined') popupParams.swipeHandler = swipeHandler;
    if (typeof containerEl !== 'undefined') popupParams.containerEl = containerEl;

    f7ready(() => {
      f7Popup = app.f7.popup.create(popupParams);
      if (opened) {
        f7Popup.open(false);
      }
    });
  });
  onDestroy(() => {
    if (f7Popup) f7Popup.destroy();
    f7Popup = null;
  });
</script>

<div class={classes} bind:this={el} {...restProps($$restProps)}>
  <slot />
</div>

// src/vue/components/popup.vue
<template>
  <div ref="elRef" :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed, ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';
import { f7ready, f7 } from '../shared/f7';
import { modalStateClasses } from '../shared/modal-state-classes';

export default {
  name: 'f7-popup',
  props: {
    tabletFullscreen: Boolean,
    opened: Boolean,
    animate: {
      type: Boolean,
      default: undefined,
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    backdropEl: {
      type: [String, Object],
      default: undefined,
    },
    closeByBackdropClick: {
      type: Boolean,
      default: undefined,
    },
    closeOnEscape: {
      type: Boolean,
      default: undefined,
    },
    swipeToClose: {
      type: [Boolean, String],
      default: false,
    },
    swipeHandler: {
      type: [String, Object],
      default: undefined,
    },
    push: Boolean,
    ...colorProps,
  },
  emits: [
    'popup:swipestart',
    'popup:swipemove',
    'popup:swipeend',
    'popup:swipeclose',
    'popup:open',
    'popup:opened',
    'popup:close',
    'popup:closed',
    'update:opened',
  ],
  setup(props, { emit }) {
    const f7Popup = ref(null);
    const isOpened = ref(props.opened);
    const isClosing = ref(false);
    const elRef = ref(null);

    const onSwipeStart = (instance) => {
      emit('popup:swipestart', instance);
    };
    const onSwipeMove = (instance) => {
      emit('popup:swipemove', instance);
    };
    const onSwipeEnd = (instance) => {
      emit('popup:swipeend', instance);
    };
    const onSwipeClose = (instance) => {
      emit('popup:swipeclose', instance);
    };
    const onOpen = (instance) => {
      isOpened.value = true;
      isClosing.value = false;
      emit('popup:open', instance);
      emit('update:opened', true);
    };
    const onOpened = (instance) => {
      emit('popup:opened', instance);
    };
    const onClose = (instance) => {
      isOpened.value = false;
      isClosing.value = true;
      emit('popup:close', instance);
    };
    const onClosed = (instance) => {
      isClosing.value = false;
      emit('popup:closed', instance);
      emit('update:opened', false);
    };
    const open = (anim) => {
      if (!f7Popup.value) return undefined;
      return f7Popup.value.open(anim);
    };
    const close = (anim) => {
      if (!f7Popup.value) return undefined;
      return f7Popup.value.close(anim);
    };

    watch(
      () => props.opened,
      (value) => {
        if (!f7Popup.value) return;
        if (value) {
          f7Popup.value.open();
        } else {
          f7Popup.value.close();
        }
      },
    );

    onMounted(() => {
      if (!elRef.value) return;
      const popupParams = {
        el: elRef.value,
        on: {
          swipeStart: onSwipeStart,
          swipeMove: onSwipeMove,
          swipeEnd: onSwipeEnd,
          swipeClose: onSwipeClose,
          open: onOpen,
          opened: onOpened,
          close: onClose,
          closed: onClosed,
        },
      };
      const {
        closeByBackdropClick,
        closeOnEscape,
        animate,
        backdrop,
        backdropEl,
        swipeToClose,
        swipeHandler,
      } = props;

      if (typeof closeByBackdropClick !== 'undefined')
        popupParams.closeByBackdropClick = closeByBackdropClick;
      if (typeof closeOnEscape !== 'undefined') popupParams.closeOnEscape = closeOnEscape;
      if (typeof animate !== 'undefined') popupParams.animate = animate;
      if (typeof backdrop !== 'undefined') popupParams.backdrop = backdrop;
      if (typeof backdropEl !== 'undefined') popupParams.backdropEl = backdropEl;
      if (typeof swipeToClose !== 'undefined') popupParams.swipeToClose = swipeToClose;
      if (typeof swipeHandler !== 'undefined') popupParams.swipeHandler = swipeHandler;

      f7ready(() => {
        f7Popup.value = f7.popup.create(popupParams);
        if (props.opened) {
          f7Popup.value.open(false);
        }
      });
    });

    onBeforeUnmount(() => {
      if (f7Popup.value) {
        f7Popup.value.destroy();
      }
      f7Popup.value = null;
    });

    const classes = computed(() =>
      classNames(
        'popup',
        {
          'popup-tablet-fullscreen': props.tabletFullscreen,
          'popup-push': props.push,
        },
        modalStateClasses({ isOpened, isClosing }),
        colorClasses(props),
      ),
    );

    return {
      open,
      close,
      elRef,
      classes,
    };
  },
};
</script>
