// src/phenome/components/preloader.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-preloader',
  props: {
    id: [String, Number],
    size: [Number, String],
    ...Mixins.colorProps,
  },
  render() {
    const { classes, sizeComputed } = this;
    const { id, style } = this.props;

    const preloaderStyle = {};
    if (sizeComputed) {
      preloaderStyle.width = `${sizeComputed}px`;
      preloaderStyle.height = `${sizeComputed}px`;
    }
    if (style) Utils.extend(preloaderStyle, style || {});

    let innerEl;
    if (this.$theme.md) {
      innerEl = (
        <span className="preloader-inner">
          <span className="preloader-inner-gap" />
          <span className="preloader-inner-left">
            <span className="preloader-inner-half-circle" />
          </span>
          <span className="preloader-inner-right">
            <span className="preloader-inner-half-circle" />
          </span>
        </span>
      );
    }
    return (
      <span id={id} style={preloaderStyle} className={classes}>
        {innerEl}
      </span>
    );
  },
  computed: {
    classes() {
      return Utils.classNames(
        this.props.className,
        'preloader',
        Mixins.colorClasses(this),
      );
    },
    sizeComputed() {
      let s = this.props.size;
      if (s && typeof s === 'string' && s.indexOf('px') >= 0) {
        s = s.replace('px', '');
      }
      return s;
    },
  },
};

// src/vue/components/preloader.vue
<template>
  <div :class="classes">
    <span v-if="theme && theme.md" class="preloader-inner">
      <span class="preloader-inner-gap" />
      <span class="preloader-inner-left">
        <span class="preloader-inner-half-circle" />
      </span>
      <span class="preloader-inner-right">
        <span class="preloader-inner-half-circle" />
      </span>
    </span>
    <span v-else-if="theme && theme.ios" class="preloader-inner">
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
      <span class="preloader-inner-line"></span>
    </span>
    <span v-else-if="theme && theme.aurora" class="preloader-inner">
      <span class="preloader-inner-circle"></span>
    </span>
    <span v-else-if="!theme" class="preloader-inner"></span>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';
import { useTheme } from '../shared/use-theme';

export default {
  name: 'f7-preloader',
  props: {
    size: [Number, String],
    ...colorProps,
  },
  setup(props) {
    const theme = useTheme();
    const classes = computed(() => classNames('preloader', colorClasses(props)));
    const style = computed(() => {
      const preloaderStyle = {};
      let sizeComputed = props.size;
      if (sizeComputed && typeof sizeComputed === 'string' && sizeComputed.indexOf('px') >= 0) {
        sizeComputed = sizeComputed.replace('px', '');
      }
      if (sizeComputed) {
        preloaderStyle.width = `${sizeComputed}px`;
        preloaderStyle.height = `${sizeComputed}px`;
        preloaderStyle['--f7-preloader-size'] = `${sizeComputed}px`;
      }
      return preloaderStyle;
    });
    return { classes, style, theme };
  },
};
</script>
