// packages/svelte/components/searchbar.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';
  import f7 from '../utils/f7';

  const dispatch = createEventDispatcher();

  let className = undefined;
  export { className as class };

  export let noShadow = false;
  export let noHairline = false;
  export let form = true;
  export let placeholder = 'Search';
  export let spellcheck = undefined;
  export let disableButton = true;
  export let disableButtonText = 'Cancel';
  export let clearButton = true;
  // Input Value
  export let value = undefined;

  // SB Params
  export let inputEvents = 'change input compositionend';
  export let expandable = false;
  export let inline = false;
  export let searchContainer = undefined;
  export let searchIn = '.item-title';
  export let searchItem = 'li';
  export let searchGroup = '.list-group';
  export let searchGroupTitle = '.item-divider, .list-group-title';
  export let foundEl = '.searchbar-found';
  export let notFoundEl = '.searchbar-not-found';
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let hideOnEnableEl = '.searchbar-hide-on-enable';
  export let hideOnSearchEl = '.searchbar-hide-on-search';
  export let ignore = '.searchbar-ignore';
  export let customSearch = false;
  export let removeDiacritics = false;
  export let hideDividers = true;
  export let hideGroups = true;
  export let init = true;

  export let f7Slot = 'fixed';

  let el;
  let f7Searchbar;

  export function instance() {
    return f7Searchbar;
  }
  export function search(query) {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.search(query);
  }
  export function enable() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.enable();
  }
  export function disable() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.disable();
  }
  export function toggle() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.toggle();
  }
  export function clear() {
    if (!f7Searchbar) return undefined;
    return f7Searchbar.clear();
  }

  $: classes = Utils.classNames(
    className,
    'searchbar',
    {
      'searchbar-inline': inline,
      'no-shadow': noShadow,
      'no-hairline': noHairline,
      'searchbar-expandable': expandable,
    },
    Mixins.colorClasses($$props),
  );

  function onChange(event) {
    dispatch('change', [event]);
    if (typeof $$props.onChange === 'function') $$props.onChange(event);
  }

  function onInput(event) {
    dispatch('input', [event]);
    if (typeof $$props.onInput === 'function') $$props.onInput(event);
  }

  function onFocus(event) {
    dispatch('focus', [event]);
    if (typeof $$props.onFocus === 'function') $$props.onFocus(event);
  }

  function onBlur(event) {
    dispatch('blur', [event]);
    if (typeof $$props.onBlur === 'function') $$props.onBlur(event);
  }

  function onSubmit(event) {
    dispatch('submit', [event]);
    if (typeof $$props.onSubmit === 'function') $$props.onSubmit(event);
  }

  function onClearButtonClick(event) {
    dispatch('click:clear', [event]);
  }

  function onDisableButtonClick(event) {
    dispatch('click:disable', [event]);
  }

  onMount(() => {
    if (!init) return;
    f7.ready(() => {
      const params = Utils.noUndefinedProps({
        el,
        inputEvents,
        searchContainer,
        searchIn,
        searchItem,
        searchGroup,
        searchGroupTitle,
        hideOnEnableEl,
        hideOnSearchEl,
        foundEl,
        notFoundEl,
        backdrop,
        backdropEl,
        disableButton,
        ignore,
        customSearch,
        removeDiacritics,
        hideDividers,
        hideGroups,
        expandable,
        inline,
        on: {
          search(searchbar, query, previousQuery) {
            dispatch('searchbarSearch', [searchbar, query, previousQuery]);
            if (typeof $$props.onSearchbarSearch === 'function') $$props.onSearchbarSearch(searchbar, query, previousQuery);
          },
          clear(searchbar, previousQuery) {
            dispatch('searchbarClear', [searchbar, previousQuery]);
            if (typeof $$props.onSearchbarClear === 'function') $$props.onSearchbarClear(searchbar, previousQuery);
          },
          enable(searchbar) {
            dispatch('searchbarEnable', [searchbar]);
            if (typeof $$props.onSearchbarEnable === 'function') $$props.onSearchbarEnable(searchbar);
          },
          disable(searchbar) {
            dispatch('searchbarDisable', [searchbar]);
            if (typeof $$props.onSearchbarDisable === 'function') $$props.onSearchbarDisable(searchbar);
          },
        },
      });
      Object.keys(params).forEach((key) => {
        if (params[key] === '') {
          delete params[key];
        }
      });
      f7Searchbar = f7.instance.searchbar.create(params);
    });
  });

  onDestroy(() => {
    if (f7Searchbar && f7Searchbar.destroy) {
      f7Searchbar.destroy();
    }
  });
</script>
{#if form}
  <form bind:this={el} class={classes} on:submit={onSubmit} data-f7-slot={f7Slot} {...restProps($$restProps)}>
    <slot name="before-inner" />
    <div class="searchbar-inner">
      <slot name="inner-start" />
      <div class="searchbar-input-wrap">
        <slot name="input-wrap-start" />
        <input
          value={typeof value === 'undefined' ? '' : value}
          placeholder={placeholder}
          spellcheck={spellcheck}
          type="search"
          on:input={onInput}
          on:change={onChange}
          on:focus={onFocus}
          on:blur={onBlur}
        />
        <i class="searchbar-icon" />
        {#if clearButton}
          <span on:click={onClearButtonClick} class="input-clear-button" />
        {/if}
        <slot name="input-wrap-end" />
      </div>
      {#if disableButton}
        <span on:click={onDisableButtonClick} class="searchbar-disable-button">{disableButtonText}</span>
      {/if}
      <slot name="inner-end" />
      <slot />
    </div>
    <slot name="after-inner" />
  </form>
{:else}
  <div bind:this={el} class={classes} data-f7-slot={f7Slot} {...restProps($$restProps)}>
    <slot name="before-inner" />
    <div class="searchbar-inner">
      <slot name="inner-start" />
      <div class="searchbar-input-wrap">
        <slot name="input-wrap-start" />
        <input
          value={typeof value === 'undefined' ? '' : value}
          placeholder={placeholder}
          spellcheck={spellcheck}
          type="search"
          on:input={onInput}
          on:change={onChange}
          on:focus={onFocus}
          on:blur={onBlur}
        />
        <i class="searchbar-icon" />
        {#if clearButton}
          <span on:click={onClearButtonClick} class="input-clear-button" />
        {/if}
        <slot name="input-wrap-end" />
      </div>
      {#if disableButton}
        <span on:click={onDisableButtonClick} class="searchbar-disable-button">{disableButtonText}</span>
      {/if}
      <slot name="inner-end" />
      <slot />
    </div>
    <slot name="after-inner" />
  </div>
{/if}

// src/vue/components/searchbar.vue
<template>
  <component :is="tag" ref="elRef" :class="classes" @submit="onSubmit">
    <slot name="before-inner" />
    <div class="searchbar-inner">
      <slot name="inner-start" />
      <div class="searchbar-input-wrap">
        <slot name="input-wrap-start" />
        <input
          :value="value"
          :placeholder="placeholder"
          :spellcheck="spellcheck"
          type="search"
          @input="onInput"
          @change="onChange"
          @focus="onFocus"
          @blur="onBlur"
        />
        <i class="searchbar-icon" />
        <span v-if="clearButton" class="input-clear-button" @click="onClearButtonClick" />
        <slot name="input-wrap-end" />
      </div>
      <span v-if="disableButton" class="searchbar-disable-button" @click="onDisableButtonClick">
        {{ disableButtonText }}
      </span>
      <slot name="inner-end" />
      <slot />
    </div>
    <slot name="after-inner" />
  </component>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount } from 'vue';
import { classNames, noUndefinedProps } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';
import { f7ready, f7 } from '../shared/f7';

export default {
  name: 'f7-searchbar',
  props: {
    noShadow: Boolean,
    noHairline: Boolean,
    form: {
      type: Boolean,
      default: true,
    },
    placeholder: {
      type: String,
      default: 'Search',
    },
    spellcheck: {
      type: Boolean,
      default: undefined,
    },
    disableButton: {
      type: Boolean,
      default: true,
    },
    disableButtonText: {
      type: String,
      default: 'Cancel',
    },
    clearButton: {
      type: Boolean,
      default: true,
    },
    // Input Value
    value: [String, Number, Array],

    // SB Params
    inputEvents: {
      type: String,
      default: 'change input compositionend',
    },
    expandable: Boolean,
    inline: Boolean,
    searchContainer: [String, Object],
    searchIn: {
      type: String,
      default: '.item-title',
    },
    searchItem: {
      type: String,
      default: 'li',
    },
    searchGroup: {
      type: String,
      default: '.list-group',
    },
    searchGroupTitle: {
      type: String,
      default: '.item-divider, .list-group-title',
    },
    foundEl: {
      type: [String, Object],
      default: '.searchbar-found',
    },
    notFoundEl: {
      type: [String, Object],
      default: '.searchbar-not-found',
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    backdropEl: [String, Object],
    hideOnEnableEl: {
      type: [String, Object],
      default: '.searchbar-hide-on-enable',
    },
    hideOnSearchEl: {
      type: [String, Object],
      default: '.searchbar-hide-on-search',
    },
    ignore: {
      type: String,
      default: '.searchbar-ignore',
    },
    customSearch: {
      type: Boolean,
      default: false,
    },
    removeDiacritics: {
      type: Boolean,
      default: false,
    },
    hideDividers: {
      type: Boolean,
      default: true,
    },
    hideGroups: {
      type: Boolean,
      default: true,
    },
    init: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  emits: [
    'change',
    'input',
    'focus',
    'blur',
    'submit',
    'click:clear',
    'click:disable',
    'searchbar:search',
    'searchbar:clear',
    'searchbar:enable',
    'searchbar:disable',
  ],
  setup(props, { emit }) {
    const f7Searchbar = ref(null);
    const elRef = ref(null);

    const search = (query) => {
      if (!f7Searchbar.value) return undefined;
      return f7Searchbar.value.search(query);
    };
    const enable = () => {
      if (!f7Searchbar.value) return undefined;
      return f7Searchbar.value.enable();
    };
    const disable = () => {
      if (!f7Searchbar.value) return undefined;
      return f7Searchbar.value.disable();
    };
    const toggle = () => {
      if (!f7Searchbar.value) return undefined;
      return f7Searchbar.value.toggle();
    };
    const clear = () => {
      if (!f7Searchbar.value) return undefined;
      return f7Searchbar.value.clear();
    };
    const onChange = (event) => {
      emit('change', event);
    };
    const onInput = (event) => {
      emit('input', event);
    };
    const onFocus = (event) => {
      emit('focus', event);
    };
    const onBlur = (event) => {
      emit('blur', event);
    };
    const onSubmit = (event) => {
      emit('submit', event);
    };
    const onClearButtonClick = (event) => {
      emit('click:clear', event);
    };
    const onDisableButtonClick = (event) => {
      emit('click:disable', event);
    };

    onMounted(() => {
      if (!props.init) return;

      f7ready(() => {
        const params = noUndefinedProps({
          el: elRef.value,
          inputEvents: props.inputEvents,
          searchContainer: props.searchContainer,
          searchIn: props.searchIn,
          searchItem: props.searchItem,
          searchGroup: props.searchGroup,
          searchGroupTitle: props.searchGroupTitle,
          hideOnEnableEl: props.hideOnEnableEl,
          hideOnSearchEl: props.hideOnSearchEl,
          foundEl: props.foundEl,
          notFoundEl: props.notFoundEl,
          backdrop: props.backdrop,
          backdropEl: props.backdropEl,
          disableButton: props.disableButton,
          ignore: props.ignore,
          customSearch: props.customSearch,
          removeDiacritics: props.removeDiacritics,
          hideDividers: props.hideDividers,
          hideGroups: props.hideGroups,
          expandable: props.expandable,
          inline: props.inline,
          on: {
            search(searchbar, query, previousQuery) {
              emit('searchbar:search', searchbar, query, previousQuery);
            },
            clear(searchbar, previousQuery) {
              emit('searchbar:clear', searchbar, previousQuery);
            },
            enable(searchbar) {
              emit('searchbar:enable', searchbar);
            },
            disable(searchbar) {
              emit('searchbar:disable', searchbar);
            },
          },
        });
        Object.keys(params).forEach((key) => {
          if (params[key] === '') {
            delete params[key];
          }
        });
        f7Searchbar.value = f7.searchbar.create(params);
      });
    });

    onBeforeUnmount(() => {
      if (f7Searchbar.value && f7Searchbar.value.destroy) f7Searchbar.value.destroy();
      f7Searchbar.value = null;
    });

    const classes = computed(() =>
      classNames(
        'searchbar',
        {
          'searchbar-inline': props.inline,
          'no-shadow': props.noShadow,
          'no-hairline': props.noHairline,
          'searchbar-expandable': props.expandable,
        },
        colorClasses(props),
      ),
    );

    const tag = computed(() => (props.form ? 'form' : 'div'));

    return {
      elRef,
      tag,
      classes,
      search,
      enable,
      disable,
      toggle,
      clear,
      onChange,
      onInput,
      onFocus,
      onBlur,
      onSubmit,
      onClearButtonClick,
      onDisableButtonClick,
    };
  },
};
</script>
