// src/phenome/components/swipeout-button.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-swipeout-button',
  props: {
    id: [String, Number],
    text: String,
    confirmText: String,
    overswipe: Boolean,
    close: Boolean,
    delete: Boolean,
    href: String,
    ...Mixins.colorProps,
  },
  render() {
    this.onClick = this.onClick.bind(this);
    return (
      <a
        href={this.props.href || '#'}
        id={this.props.id}
        style={this.props.style}
        data-confirm={this.props.confirmText || undefined}
        className={this.classes}
        onClick={this.onClick}
      >
        <slot>{this.props.text}</slot>
      </a>
    );
  },
  computed: {
    classes() {
      return Utils.classNames(
        this.props.className,
        {
          'swipeout-overswipe': this.props.overswipe,
          'swipeout-delete': this.props.delete,
          'swipeout-close': this.props.close,
        },
        Mixins.colorClasses(this),
      );
    },
  },
  methods: {
    onClick(event) {
      this.dispatchEvent('click', event);
    },
  },
};

// src/vue/components/swipeout-button.vue
<template>
  <a
    :href="href || '#'"
    :data-confirm="confirmText || undefined"
    :data-confirm-title="confirmTitle || undefined"
    :class="classes"
    @click="onClick"
  >
    {{ text }}
    <slot />
  </a>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-swipeout-button',
  props: {
    text: String,
    confirmTitle: String,
    confirmText: String,
    overswipe: Boolean,
    close: Boolean,
    delete: Boolean,
    href: String,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const onClick = (e) => {
      emit('click', e);
    };
    const classes = computed(() =>
      classNames(
        {
          'swipeout-overswipe': props.overswipe,
          'swipeout-delete': props.delete,
          'swipeout-close': props.close,
        },
        colorClasses(props),
      ),
    );
    return {
      classes,
      onClick,
    };
  },
};
</script>
