// src/phenome/components/tabs.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-tabs',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    animated: Boolean,
    swipeable: Boolean,
    routable: Boolean,
    swiperParams: {
      type: Object,
      default: undefined,
    },
    ...Mixins.colorProps,
  },
  render() {
    const self = this;
    const props = self.props;
    const { animated, swipeable, id, style, className, routable } = props;

    const classes = Utils.classNames(
      className,
      Mixins.colorClasses(props),
    );
    const wrapClasses = Utils.classNames({
      'tabs-animated-wrap': animated,
      'tabs-swipeable-wrap': swipeable,
    });
    const tabsClasses = Utils.classNames({
      tabs: true,
      'tabs-routable': routable,
    });

    if (animated || swipeable) {
      return (
        <div id={id} style={style} className={Utils.classNames(wrapClasses, classes)} ref="wrapEl">
          <div className={tabsClasses}>
            <slot />
          </div>
        </div>
      );
    }

    return (
      <div id={id} style={style} className={Utils.classNames(tabsClasses, classes)}>
        <slot />
      </div>
    );
  },
  componentDidMount() {
    const self = this;
    const { swipeable, swiperParams } = self.props;
    if (!swipeable || !swiperParams) return;
    const wrapEl = self.refs.wrapEl;
    if (!wrapEl) return;
    wrapEl.f7SwiperParams = swiperParams;
  },
};

// src/vue/components/tabs.vue
<template>
  <div v-if="animated || swipeable" ref="elRef" :class="classNames(wrapClasses, classes)">
    <div :class="tabsClasses">
      <slot />
    </div>
  </div>
  <div v-else ref="elRef" :class="classNames(tabsClasses, classes)">
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-tabs',
  props: {
    animated: Boolean,
    swipeable: Boolean,
    routable: Boolean,
    swiperParams: {
      type: Object,
      default: undefined,
    },
    ...colorProps,
  },
  setup(props) {
    const elRef = ref(null);

    onMounted(() => {
      if (!props.swipeable || !props.swiperParams) return;
      if (!elRef.value) return;
      elRef.value.f7SwiperParams = props.swiperParams;
    });

    const classes = computed(() => classNames(colorClasses(props)));
    const wrapClasses = computed(() =>
      classNames({
        'tabs-animated-wrap': props.animated,
        'tabs-swipeable-wrap': props.swipeable,
      }),
    );
    const tabsClasses = computed(() =>
      classNames({
        tabs: true,
        'tabs-routable': props.routable,
      }),
    );

    return {
      elRef,
      classes,
      wrapClasses,
      tabsClasses,
      classNames,
    };
  },
};
</script>
