// src/svelte/components/toolbar-pane.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';

  let { className, id, style, ref, children, ...restProps } = $props();

  let el = $state(undefined);

  const classes = $derived(classNames(className, 'toolbar-pane', colorClasses(restProps)));
</script>

<div bind:this={el} class={classes} {...restProps}>
  {@render children?.()}
</div>

// src/vue/components/toolbar-pane.vue
<template>
  <div ref="elRef" :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';

export default {
  name: 'f7-toolbar-pane',
  props: {},
  setup(props) {
    const classes = computed(() => {
      return classNames('toolbar-pane');
    });

    return { classes };
  },
};
</script>
