// src/vue/components/treeview-item.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { useIsomorphicLayoutEffect } from '../shared/use-isomorphic-layout-effect';
import { classNames, getExtraAttrs, getSlots, emit } from '../shared/utils';
import {
  colorClasses,
  actionsAttrs,
  actionsClasses,
  routerAttrs,
  routerClasses,
} from '../shared/mixins';
import { useIcon } from '../shared/use-icon';
import { f7ready, f7 } from '../shared/f7';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  toggle? : boolean
  itemToggle? : boolean
  selectable? : boolean
  selected? : boolean
  opened? : boolean
  label? : string
  loadChildren? : boolean
  link? : boolean | string
  COLOR_PROPS
  ACTIONS_PROPS
  ROUTER_PROPS
  ICON_PROPS
  onClick? : (event?: any) => void
  onTreeviewOpen? : (el?: HTMLElement) => void
  onTreeviewClose? : (el?: HTMLElement) => void
  onTreeviewLoadChildren? : (el?: HTMLElement, done?: any) => void
*/

const TreeviewItem = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    toggle,
    itemToggle,
    selectable,
    selected,
    opened,
    label,
    loadChildren,
    link,
  } = props;

  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'click', event);
  };
  const onOpen = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewOpen', el);
  };
  const onClose = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewClose', el);
  };
  const onLoadChildren = (el, done) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewLoadChildren', el, done);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const attachEvents = () => {
    if (!elRef.current) return;
    f7ready(() => {
      f7.on('treeviewOpen', onOpen);
      f7.on('treeviewClose', onClose);
      f7.on('treeviewLoadChildren', onLoadChildren);
    });
  };

  const detachEvents = () => {
    if (!f7) return;
    f7.off('treeviewOpen', onOpen);
    f7.off('treeviewClose', onClose);
    f7.off('treeviewLoadChildren', onLoadChildren);
  };

  useIsomorphicLayoutEffect(() => {
    attachEvents();
    return detachEvents;
  });

  const slots = getSlots(props);
  const hasChildren =
    (slots.default && slots.default.length) ||
    (slots.children && slots.children.length) ||
    (slots['children-start'] && slots['children-start'].length);
  const needToggle = typeof toggle === 'undefined' ? hasChildren : toggle;

  const iconEl = useIcon(props);

  const TreeviewRootTag = link || link === '' ? 'a' : 'div';

  const classes = classNames(
    className,
    'treeview-item',
    {
      'treeview-item-opened': opened,
      'treeview-load-children': loadChildren,
    },
    colorClasses(props),
  );

  const itemRootClasses = classNames(
    'treeview-item-root',
    {
      'treeview-item-selectable': selectable,
      'treeview-item-selected': selected,
      'treeview-item-toggle': itemToggle,
    },
    routerClasses(props),
    actionsClasses(props),
  );

  let href = link;
  if (link === true) href = '#';
  if (link === false) href = undefined; // no href attribute
  const itemRootAttrs = {
    href,
    ...routerAttrs(props),
    ...actionsAttrs(props),
  };

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      <TreeviewRootTag onClick={onClick} className={itemRootClasses} {...itemRootAttrs}>
        {slots['root-start']}
        {needToggle && <div className="treeview-toggle"></div>}
        <div className="treeview-item-content">
          {slots['content-start']}
          {iconEl}
          {slots.media}
          <div className="treeview-item-label">
            {slots['label-start']}
            {label}
            {slots.label}
          </div>
          {slots.content}
          {slots['content-end']}
        </div>
        {slots.root}
        {slots['root-end']}
      </TreeviewRootTag>
      {hasChildren && (
        <div className="treeview-item-children">
          {slots['children-start']}
          {slots.default}
          {slots.children}
        </div>
      )}
    </div>
  );
});

TreeviewItem.displayName = 'f7-treeview-item';

export default TreeviewItem;

// src/vue/components/treeview-item.vue
<template>
  <div ref="elRef" :class="classes">
    <component :is="itemRootTag" :class="itemRootClasses" v-bind="itemRootAttrs" @click="onClick">
      <slot name="root-start" />
      <div v-if="needToggle" className="treeview-toggle" />
      <div className="treeview-item-content">
        <slot name="content-start" />
        <f7-use-icon v-if="icon" :icon="icon" />
        <slot name="media" />
        <div className="treeview-item-label">
          <slot name="label-start" />
          {{ label }}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </component>
    <div v-if="hasChildren" className="treeview-item-children">
      <slot name="children-start" />
      <slot />
      <slot name="children" />
    </div>
  </div>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount } from 'vue';
import { classNames } from '../shared/utils';
import {
  colorClasses,
  colorProps,
  actionsAttrs,
  actionsProps,
  actionsClasses,
  routerAttrs,
  routerProps,
  routerClasses,
  iconProps,
} from '../shared/mixins';
import { useIcon } from '../shared/use-icon';
import { f7ready, f7 } from '../shared/f7';

import f7UseIcon from './use-icon';

export default {
  name: 'f7-treeview-item',
  components: {
    f7UseIcon,
  },
  props: {
    toggle: {
      type: Boolean,
      default: undefined,
    },
    itemToggle: Boolean,
    selectable: Boolean,
    selected: Boolean,
    opened: Boolean,
    label: String,
    loadChildren: Boolean,
    link: {
      type: [Boolean, String],
      default: undefined,
    },
    ...colorProps,
    ...actionsProps,
    ...iconProps,
    ...routerProps,
  },
  emits: ['click', 'treeview:open', 'treeview:close', 'treeview:loadchildren'],
  setup(props, { slots, emit }) {
    const elRef = ref(null);

    const hasChildren = computed(() => {
      return slots.default || slots.children || slots['children-start'];
    });

    const needToggle = computed(() =>
      typeof props.toggle === 'undefined' ? hasChildren.value : props.toggle,
    );

    const icon = computed(() => useIcon(props));

    const onClick = (event) => {
      emit('click', event);
    };
    const onOpen = (el) => {
      if (elRef.value !== el) return;
      emit('treeview:open', el);
    };
    const onClose = (el) => {
      if (elRef.value !== el) return;
      emit('treeview:close', el);
    };
    const onLoadChildren = (el, done) => {
      if (elRef.value !== el) return;
      emit('treeview:loadchildren', el, done);
    };

    const attachEvents = () => {
      if (!elRef.value) return;
      f7ready(() => {
        f7.on('treeviewOpen', onOpen);
        f7.on('treeviewClose', onClose);
        f7.on('treeviewLoadChildren', onLoadChildren);
      });
    };

    const detachEvents = () => {
      if (!f7) return;
      f7.off('treeviewOpen', onOpen);
      f7.off('treeviewClose', onClose);
      f7.off('treeviewLoadChildren', onLoadChildren);
    };

    onMounted(() => attachEvents());
    onBeforeUnmount(() => detachEvents());

    const classes = computed(() =>
      classNames(
        'treeview-item',
        {
          'treeview-item-opened': props.opened,
          'treeview-load-children': props.loadChildren,
        },
        colorClasses(props),
      ),
    );

    const itemRootClasses = computed(() =>
      classNames(
        'treeview-item-root',
        {
          'treeview-item-selectable': props.selectable,
          'treeview-item-selected': props.selected,
          'treeview-item-toggle': props.itemToggle,
        },
        routerClasses(props),
        actionsClasses(props),
      ),
    );

    const itemRootTag = computed(() => (props.link || props.link === '' ? 'a' : 'div'));

    const itemRootAttrs = computed(() => {
      let href = props.link;
      if (props.link === true) href = '#';
      if (props.link === false) href = undefined; // no href attribute
      return {
        href,
        ...routerAttrs(props),
        ...actionsAttrs(props),
      };
    });

    return {
      itemRootTag,
      itemRootAttrs,
      itemRootClasses,
      classes,
      icon,
      onClick,
      hasChildren,
      needToggle,
      elRef,
    };
  },
};
</script>
