// src/vue/components/card-content.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-card-content',
  props: {
    padding: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'card-content',
        {
          'card-content-padding': props.padding,
        },
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>

// src/svelte/components/card-content.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  export let padding = true;

  $: classes = classNames(
    className,
    'card-content',
    {
      'card-content-padding': padding,
    },
    colorClasses($$props),
  );
</script>

<div class={classes} {...restProps($$restProps)}>
  <slot />
</div>
