// src/react/components/messagebar-attachment.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  image? : string
  deletable? : boolean
  COLOR_PROPS
  onAttachmentClick? : (event?: any) => void
  onAttachmentDelete? : (event?: any) => void
*/

const MessagebarAttachment = forwardRef((props, ref) => {
  const { className, id, style, children, image, deletable = true } = props;
  const dataAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'attachmentClick', event);
  };
  const onDeleteClick = (event) => {
    emit(props, 'attachmentDelete', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(className, 'messagebar-attachment', colorClasses(props));

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...dataAttrs} onClick={onClick}>
      {image && <img src={image} />}
      {deletable && <span className="messagebar-attachment-delete" onClick={onDeleteClick} />}
      {children}
    </div>
  );
});

MessagebarAttachment.displayName = 'f7-messagebar-attachment';

export default MessagebarAttachment;

// src/svelte/components/messagebar-attachment.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { colorClasses } from '../shared/mixins';
  import { classNames } from '../shared/utils';
  import { restProps } from '../shared/rest-props';

  const dispatch = createEventDispatcher();

  let className = undefined;
  export { className as class };

  export let image = undefined;
  export let deletable = true;

  $: classes = classNames(className, 'messagebar-attachment', colorClasses($$props));

  function onClick(event) {
    dispatch('attachmentClick', [event]);
    if (typeof $$props.onAttachmentClick === 'function') $$props.onAttachmentClick(event);
  }

  function onDeleteClick(event) {
    dispatch('attachmentDelete', [event]);
    if (typeof $$props.onAttachmentDelete === 'function') $$props.onAttachmentDelete(event);
  }
</script>

<!-- svelte-ignore a11y-missing-attribute -->
<div on:click={onClick} class={classes} {...restProps($$restProps)}>
  {#if image}
    <img src={image} />
  {/if}
  {#if deletable}
    <span on:click={onDeleteClick}  class="messagebar-attachment-delete" />
  {/if}
  <slot />
</div>
