// src/vue/components/nav-left.vue
<template>
  <div :class="classes">
    <f7-link
      v-if="backLink"
      :href="backLinkUrl || '#'"
      back
      icon="icon-back"
      :force="backLinkForce || undefined"
      :class="!text ? 'icon-only' : undefined"
      :text="text"
      @click="onBackClick"
    />
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

import f7Link from './link.js';

export default {
  name: 'f7-nav-left',
  components: {
    f7Link,
  },
  props: {
    backLink: [Boolean, String],
    backLinkUrl: String,
    backLinkForce: Boolean,
    backLinkShowText: {
      type: Boolean,
      default: undefined,
    },
    ...colorProps,
  },
  emits: ['back:click', 'click:back'],
  setup(props, { emit }) {
    const onBackClick = (event) => {
      emit('back:click', event);
      emit('click:back', event);
    };

    const text = computed(() => {
      if (props.backLink) {
        return props.backLink !== true && props.backLinkShowText ? props.backLink : undefined;
      }
      return undefined;
    });

    const classes = computed(() => classNames('left', {}, colorClasses(props)));
    return { classes, onBackClick, text };
  },
};
</script>

// src/svelte/components/nav-left.svelte
<script>
  import { createEventDispatcher } from 'svelte';
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  import Link from './link.svelte';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let backLink = undefined;
  export let backLinkUrl = undefined;
  export let backLinkForce = undefined;
  export let backLinkShowText = undefined;

  $: classes = classNames(
    className,
    'left',
    {},
    colorClasses($$props),
  );

  $: backLinkText = backLink !== true && backLinkShowText ? backLink : undefined;


  function onBackClick() {
    emit('clickBack');
    emit('backClick');
  }
</script>

<div class={classes} {...restProps($$restProps)}>
  {#if backLink}
    <Link
      href={backLinkUrl || '#'}
      back
      icon="icon-back"
      force={backLinkForce || undefined}
      class={!backLinkText ? 'icon-only' : undefined}
      text={backLinkText}
      onClick={onBackClick}
    />
  {/if}
  <slot />
</div>
