// src/vue/components/nav-title.vue
<template>
  <div :class="classes">
    <slot />
    {{ title }}
    <span v-if="subtitle" class="subtitle">{{ subtitle }}</span>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-nav-title',
  props: {
    title: String,
    subtitle: String,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('title', {}, colorClasses(props)));
    return { classes };
  },
};
</script>

// src/svelte/components/nav-title.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames, plainText } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  let className = undefined;
  export { className as class };

  export let title = undefined;
  export let subtitle = undefined;

  $: classes = classNames(
    className,
    'title',
    {},
    colorClasses($$props),
  );
</script>

<div class={classes} {...restProps($$restProps)}>
  {#if typeof title !== 'undefined'}{plainText(title)}{/if}
  {#if typeof subtitle !== 'undefined'}<span class="subtitle">{plainText(subtitle)}</span>{/if}
  <slot />
</div>
