// src/react/components/_old/skeleton-block.jsx
import Utils from '../shared/utils';
import Mixins from '../shared/mixins';

export default {
  name: 'f7-skeleton-block',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    width: [Number, String],
    height: [Number, String],
    tag: {
      type: String,
      default: 'div',
    },
    ...Mixins.colorProps,
  },
  render() {
    const props = this.props;
    const {
      className,
      id,
      style,
      width,
      height,
      tag,
    } = props;

    const classes = Utils.classNames(
      'skeleton-block',
      className,
      Mixins.colorClasses(props),
    );

    let styleAttribute = style;
    if (width) {
      const widthValue = typeof width === 'number' ? `${width}px` : width;
      if (!styleAttribute) {
        styleAttribute = { width: widthValue };
      } else if (typeof styleAttribute === 'object') {
        styleAttribute = Object.assign({ width: widthValue }, styleAttribute);
      } else if (typeof styleAttribute === 'string') {
        styleAttribute = `width: ${widthValue}; ${styleAttribute}`;
      }
    }
    if (height) {
      const heightValue = typeof height === 'number' ? `${height}px` : height;
      if (!styleAttribute) {
        styleAttribute = { height: heightValue };
      } else if (typeof styleAttribute === 'object') {
        styleAttribute = Object.assign({ height: heightValue }, styleAttribute);
      } else if (typeof styleAttribute === 'string') {
        styleAttribute = `height: ${heightValue}; ${styleAttribute}`;
      }
    }
    const Tag = tag;
    return (
      <Tag id={id} style={styleAttribute} className={classes}>
        <slot />
      </Tag>
    );
  },
};

// src/svelte/components/skeleton-block.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let width = undefined;
  export let height = undefined;
  export let tag = 'div';

  $: classes = Utils.classNames(
    'skeleton-block',
    className,
    Mixins.colorClasses($$props),
  );

  $: styleAttribute = (() => {
    let s = style || '';
    if (width) {
      const widthValue = typeof width === 'number' ? `${width}px` : width;
      s = `width: ${widthValue}; ${s}`;
    }
    if (height) {
      const heightValue = typeof height === 'number' ? `${height}px` : height;
      s = `height: ${heightValue}; ${s}`;
    }
    return s;
  })();

</script>
{#if tag === 'div'}
<div id={id} style={styleAttribute} class={classes}>
  <slot />
</div>
{:else if tag === 'span'}
<span id={id} style={styleAttribute} class={classes}>
  <slot />
</span>
{/if}
