// src/react/components/toolbar-pane.jsx
import React, { useRef } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { setRef } from '../shared/set-ref.js';
/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
*/

const ToolbarPane = (props) => {
  const { className, id, style, ref, children } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const classes = classNames('toolbar-pane', className, colorClasses(props));

  return (
    <div
      id={id}
      style={style}
      className={classes}
      ref={(el) => {
        elRef.current = el;
        setRef(ref, el);
      }}
      {...extraAttrs}
    >
      {children}
    </div>
  );
};

ToolbarPane.displayName = 'f7-toolbar-pane';

export default ToolbarPane;

// src/svelte/components/toolbar-pane.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';

  let { className, id, style, ref, children, ...restProps } = $props();

  let el = $state(undefined);

  const classes = $derived(classNames(className, 'toolbar-pane', colorClasses(restProps)));
</script>

<div bind:this={el} class={classes} {...restProps}>
  {@render children?.()}
</div>
