// src/react/components/treeview-item.jsx
import React, { forwardRef, useRef, useImperativeHandle, useEffect } from 'react';
import { classNames, getDataAttrs, getSlots, emit } from '../shared/utils';
import {
  colorClasses,
  actionsAttrs,
  actionsClasses,
  routerAttrs,
  routerClasses,
} from '../shared/mixins';
import { useIcon } from '../shared/use-icon';
import { f7ready, f7 } from '../shared/f7';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  toggle? : boolean
  itemToggle? : boolean
  selectable? : boolean
  selected? : boolean
  opened? : boolean
  label? : string
  loadChildren? : boolean
  link? : boolean | string
  COLOR_PROPS
  ACTIONS_PROPS
  ROUTER_PROPS
  ICON_PROPS
  onClick? : (event?: any) => void
  onTreeviewOpen? : (el?: HTMLElement) => void
  onTreeviewClose? : (el?: HTMLElement) => void
  onTreeviewLoadChildren? : (el?: HTMLElement, done?: any) => void
*/

const TreeviewItem = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    toggle,
    itemToggle,
    selectable,
    selected,
    opened,
    label,
    loadChildren,
    link,
  } = props;

  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'click', event);
  };
  const onOpen = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewOpen', el);
  };
  const onClose = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewClose', el);
  };
  const onLoadChildren = (el, done) => {
    if (elRef.current !== el) return;
    emit(props, 'treeviewLoadChildren', el, done);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const onMount = () => {
    if (!elRef.current) return;
    f7ready(() => {
      f7.on('treeviewOpen', onOpen);
      f7.on('treeviewClose', onClose);
      f7.on('treeviewLoadChildren', onLoadChildren);
    });
  };

  const onDestroy = () => {
    if (!f7) return;
    f7.off('treeviewOpen', onOpen);
    f7.off('treeviewClose', onClose);
    f7.off('treeviewLoadChildren', onLoadChildren);
  };

  useEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  const slots = getSlots(props);
  const hasChildren =
    (slots.default && slots.default.length) ||
    (slots.children && slots.children.length) ||
    (slots['children-start'] && slots['children-start'].length);
  const needToggle = typeof toggle === 'undefined' ? hasChildren : toggle;

  const iconEl = useIcon(props);

  const TreeviewRootTag = link || link === '' ? 'a' : 'div';

  const classes = classNames(
    className,
    'treeview-item',
    {
      'treeview-item-opened': opened,
      'treeview-load-children': loadChildren,
    },
    colorClasses(props),
  );

  const itemRootClasses = classNames(
    'treeview-item-root',
    {
      'treeview-item-selectable': selectable,
      'treeview-item-selected': selected,
      'treeview-item-toggle': itemToggle,
    },
    routerClasses(props),
    actionsClasses(props),
  );

  let href = link;
  if (link === true) href = '#';
  if (link === false) href = undefined; // no href attribute
  const itemRootAttrs = {
    href,
    ...routerAttrs(props),
    ...actionsAttrs(props),
  };

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...dataAttrs}>
      <TreeviewRootTag onClick={onClick} className={itemRootClasses} {...itemRootAttrs}>
        <slot name="root-start" />
        {needToggle && <div className="treeview-toggle"></div>}
        <div className="treeview-item-content">
          <slot name="content-start" />
          {iconEl}
          <slot name="media" />
          <div className="treeview-item-label">
            <slot name="label-start" />
            {label}
            <slot name="label" />
          </div>
          <slot name="content" />
          <slot name="content-end" />
        </div>
        <slot name="root" />
        <slot name="root-end" />
      </TreeviewRootTag>
      {hasChildren && (
        <div className="treeview-item-children">
          <slot name="children-start" />
          <slot />
          <slot name="children" />
        </div>
      )}
    </div>
  );
});

TreeviewItem.displayName = 'f7-treeview-item';

export default TreeviewItem;

// src/svelte/components/treeview-item.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import {
    colorClasses,
    routerAttrs,
    routerClasses,
    actionsClasses,
    actionsAttrs,
  } from '../shared/mixins';
  import { classNames, extend, plainText, createEmitter } from '../shared/utils';
  import { restProps } from '../shared/rest-props';
  import { f7, f7ready } from '../shared/f7';
  import { hasSlots } from '../shared/has-slots';
  import { useIcon } from '../shared/use-icon';

  import UseIconComponent from './use-icon-component';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let toggle = undefined;
  export let itemToggle = false;
  export let selectable = false;
  export let selected = false;
  export let opened = false;
  export let label = undefined;
  export let loadChildren = false;
  export let link = undefined;

  let el;

  $: classes = classNames(
    className,
    'treeview-item',
    {
      'treeview-item-opened': opened,
      'treeview-load-children': loadChildren,
    },
    colorClasses($$props),
  );

  $: itemRootClasses = classNames(
    'treeview-item-root',
    {
      'treeview-item-selectable': selectable,
      'treeview-item-selected': selected,
      'treeview-item-toggle': itemToggle,
    },
    routerClasses($$props),
    actionsClasses($$props),
  );

  $: itemRootAttrs = extend(
    {
      href: link === true ? '#' : link || undefined,
    },
    routerAttrs($$props),
    actionsAttrs($$props),
  );

  /* eslint-disable no-undef */
  $: hasChildren =
    hasSlots(arguments, 'default') ||
    hasSlots(arguments, 'children') ||
    hasSlots(arguments, 'children-start');
  /* eslint-enable no-undef */

  $: needToggle = typeof toggle === 'undefined' ? hasChildren : toggle;

  $: icon = useIcon($$props);

  $: treeviewRootTag = link || link === '' ? 'a' : 'div';

  function onClick(e) {
    emit('click', [e]);
  }
  function onOpen(itemEl) {
    if (itemEl !== el) return;
    emit('treeviewOpen', [el]);
  }
  function onClose(itemEl) {
    if (itemEl !== el) return;
    emit('treeviewClose', [el]);
  }
  function onLoadChildren(itemEl, done) {
    if (itemEl !== el) return;
    emit('treeviewLoadChildren', [el, done]);
  }

  onMount(() => {
    if (!el) return;
    f7ready(() => {
      f7.on('treeviewOpen', onOpen);
      f7.on('treeviewClose', onClose);
      f7.on('treeviewLoadChildren', onLoadChildren);
    });
  });

  onDestroy(() => {
    if (!el || !f7) return;
    f7.off('treeviewOpen', onOpen);
    f7.off('treeviewClose', onClose);
    f7.off('treeviewLoadChildren', onLoadChildren);
  });
</script>

<!-- svelte-ignore a11y-missing-attribute -->
<div bind:this={el} class={classes} {...restProps($$restProps)}>
  {#if treeviewRootTag === 'div'}
    <div
      on:click={onClick}
      class={itemRootClasses}
      {...itemRootAttrs}
    >
      <slot name="root-start" />
      {#if needToggle}
        <div class="treeview-toggle"></div>
      {/if}
      <div class="treeview-item-content">
        <slot name="content-start" />
        {#if icon}
          <UseIconComponent {icon} />
        {/if}
        <slot name="media" />
        <div class="treeview-item-label">
          <slot name="label-start" />
          {plainText(label)}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </div>
  {:else}
    <a
      on:click={onClick}
      class={itemRootClasses}
      {...itemRootAttrs}
    >
      <slot name="root-start" />
      {#if needToggle}
        <div class="treeview-toggle"></div>
      {/if}
      <div class="treeview-item-content">
        <slot name="content-start" />
        {#if icon}
          <UseIconComponent {icon} />
        {/if}
        <slot name="media" />
        <div class="treeview-item-label">
          <slot name="label-start" />
          {plainText(label)}
          <slot name="label" />
        </div>
        <slot name="content" />
        <slot name="content-end" />
      </div>
      <slot name="root" />
      <slot name="root-end" />
    </a>
  {/if}
  {#if hasChildren}
    <div class="treeview-item-children">
      <slot name="children-start" />
      <slot />
      <slot name="children" />
    </div>
  {/if}
</div>
