// kitchen-sink/vue/src/pages/breadcrumbs.vue
<template>
  <f7-page>
    <f7-navbar sliding back-link="Back" title="Breadcrumbs" />
    <f7-block strong>
      <p>
        Breadcrumbs allow users to keep track and maintain awareness of their locations within the
        app or website. They should be used for large sites and apps with hierarchically arranged
        pages.
      </p>
    </f7-block>

    <f7-block-title>Basic</f7-block-title>
    <f7-block strong>
      <f7-breadcrumbs>
        <f7-breadcrumbs-item>
          <f7-link>Home</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link>Catalog</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item active>Phones</f7-breadcrumbs-item>
      </f7-breadcrumbs>
    </f7-block>

    <f7-block-title>Scrollable</f7-block-title>
    <f7-block-header>Breadcrumbs will be scrollable if they don't fit the screen</f7-block-header>
    <f7-block strong>
      <f7-breadcrumbs>
        <f7-breadcrumbs-item>
          <f7-link>Home</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link>Catalog</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link>Phones</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link>Apple</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
      </f7-breadcrumbs>
    </f7-block>

    <f7-block-title>Collapsed</f7-block-title>
    <f7-block strong>
      <f7-breadcrumbs>
        <f7-breadcrumbs-item>
          <f7-link>Home</f7-link>
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-collapsed class="popover-open" data-popover=".breadcrumbs-popover">
          <f7-popover class="breadcrumbs-popover" style="width: 120px">
            <f7-list>
              <f7-list-item link title="Catalog" popover-close />
              <f7-list-item link title="Phones" popover-close />
              <f7-list-item link title="Apple" popover-close />
            </f7-list>
          </f7-popover>
        </f7-breadcrumbs-collapsed>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
      </f7-breadcrumbs>
    </f7-block>

    <f7-block-title>With Icons</f7-block-title>
    <f7-block strong>
      <f7-breadcrumbs>
        <f7-breadcrumbs-item>
          <f7-link icon-ios="f7:house_fill" icon-md="material:home" text="Home" />
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link icon-ios="f7:square_list_fill" icon-md="material:list_alt" text="Catalog" />
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link
            icon-ios="f7:device_phone_portrait"
            icon-md="material:smartphone"
            text="Phones"
          />
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item>
          <f7-link icon-f7="logo_apple" text="Apple" />
        </f7-breadcrumbs-item>
        <f7-breadcrumbs-separator />
        <f7-breadcrumbs-item active>iPhone 12</f7-breadcrumbs-item>
      </f7-breadcrumbs>
    </f7-block>
  </f7-page>
</template>
<script>
import {
  f7Navbar,
  f7Page,
  f7Link,
  f7Block,
  f7BlockTitle,
  f7BlockHeader,
  f7Breadcrumbs,
  f7BreadcrumbsItem,
  f7BreadcrumbsSeparator,
  f7BreadcrumbsCollapsed,
  f7Popover,
  f7List,
  f7ListItem,
} from 'framework7-vue';

export default {
  components: {
    f7Navbar,
    f7Page,
    f7Link,
    f7Block,
    f7BlockTitle,
    f7BlockHeader,
    f7Breadcrumbs,
    f7BreadcrumbsItem,
    f7BreadcrumbsSeparator,
    f7BreadcrumbsCollapsed,
    f7Popover,
    f7List,
    f7ListItem,
  },
};
</script>

// kitchen-sink/svelte/src/pages/breadcrumbs.svelte
<script>
  import {
    Navbar,
    Page,
    BlockTitle,
    BlockHeader,
    Block,
    Breadcrumbs,
    BreadcrumbsItem,
    BreadcrumbsSeparator,
    BreadcrumbsCollapsed,
    Popover,
    List,
    ListItem,
    Link,
  } from 'framework7-svelte';
</script>

<Page>
  <Navbar sliding backLink="Back" title="Breadcrumbs" />
  <Block strong>
    <p>
      Breadcrumbs allow users to keep track and maintain awareness of their locations within the app
      or website. They should be used for large sites and apps with hierarchically arranged pages.
    </p>
  </Block>

  <BlockTitle>Basic</BlockTitle>
  <Block strong>
    <Breadcrumbs>
      <BreadcrumbsItem>
        <Link>Home</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link>Catalog</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem active>Phones</BreadcrumbsItem>
    </Breadcrumbs>
  </Block>

  <BlockTitle>Scrollable</BlockTitle>
  <BlockHeader>Breadcrumbs will be scrollable if they don't fit the screen</BlockHeader>
  <Block strong>
    <Breadcrumbs>
      <BreadcrumbsItem>
        <Link>Home</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link>Catalog</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link>Phones</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link>Apple</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
    </Breadcrumbs>
  </Block>

  <BlockTitle>Collapsed</BlockTitle>
  <Block strong>
    <Breadcrumbs>
      <BreadcrumbsItem>
        <Link>Home</Link>
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsCollapsed class="popover-open" data-popover=".breadcrumbs-popover">
        <Popover class="breadcrumbs-popover" style="width: 120px">
          <List>
            <ListItem link title="Catalog" popoverClose />
            <ListItem link title="Phones" popoverClose />
            <ListItem link title="Apple" popoverClose />
          </List>
        </Popover>
      </BreadcrumbsCollapsed>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
    </Breadcrumbs>
  </Block>

  <BlockTitle>With Icons</BlockTitle>
  <Block strong>
    <Breadcrumbs>
      <BreadcrumbsItem>
        <Link iconIos="f7:house_fill" iconMd="material:home" text="Home" />
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link iconIos="f7:square_list_fill" iconMd="material:list_alt" text="Catalog" />
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link iconIos="f7:device_phone_portrait" iconMd="material:smartphone" text="Phones" />
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem>
        <Link iconF7="logo_apple" text="Apple" />
      </BreadcrumbsItem>
      <BreadcrumbsSeparator />
      <BreadcrumbsItem active>iPhone 12</BreadcrumbsItem>
    </Breadcrumbs>
  </Block>
</Page>
