// kitchen-sink/svelte/src/pages/404.svelte
<Page>
  <div slot="fixed" class="navbar">
    <div class="navbar-bg"></div>
    <div class="navbar-inner sliding">
      <div class="left">
        <a href="#" class="link back">
          <i class="icon icon-back"></i>
          <span class="if-not-md">Back</span>
        </a>
      </div>
      <div class="title">Not found</div>
    </div>
  </div>

  <Block strong>
    <p>Sorry</p>
    <p>Requested content not found.</p>
  </Block>
</Page>

<script>
  import { Page, Block } from 'framework7-svelte';
</script>

// kitchen-sink/vue/src/pages/404.vue
<template>
  <f7-page>
    <f7-navbar title="Not found" back-link="Back"></f7-navbar>
    <f7-block strong>
      <p>Sorry</p>
      <p>Requested content not found.</p>
    </f7-block>
  </f7-page>
</template>

<script>
import { f7Page, f7Navbar, f7Block } from 'framework7-vue';

export default {
  components: {
    f7Page,
    f7Navbar,
    f7Block,
  },
};
</script>
