// src/vue/components/accordion-toggle.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-accordion-toggle',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = classNames('accordion-item-toggle', colorClasses(props));
    return { classes };
  },
};
</script>

// src/phenome/components/accordion-toggle.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  props: Mixins.colorProps,
  name: 'f7-accordion-toggle',
  render() {
    const classes = Utils.classNames(
      this.props.className,
      {
        'accordion-item-toggle': true,
      },
      Mixins.colorClasses(this),
    );
    return (
      <div id={this.props.id} style={this.props.style} className={classes}>
        <slot />
      </div>
    );
  },
};
