// src/vue/components/actions-label.vue
<template>
  <div :class="classes" @click="onClick">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils.js';
import { colorClasses, colorProps } from '../shared/mixins.js';

export default {
  name: 'f7-actions-label',
  props: {
    bold: Boolean,
    ...colorProps,
  },
  emits: ['click'],
  setup(props, { emit }) {
    const onClick = (e) => {
      emit('click', e);
    };
    const classes = computed(() =>
      classNames(
        'actions-label',
        {
          'actions-button-bold': props.bold,
        },
        colorClasses(props),
      ),
    );
    return { classes, onClick };
  },
};
</script>

// src/phenome/components/actions-label.jsx
import Mixins from '../utils/mixins';
import Utils from '../utils/utils';

export default {
  name: 'f7-actions-label',
  props: {
    bold: Boolean,
    ...Mixins.colorProps,
  },
  render() {
    const self = this;

    const classes = Utils.classNames(
      self.props.className,
      {
        'actions-label': true,
        'actions-button-bold': self.props.bold,
      },
      Mixins.colorClasses(self),
    );
    return (
      <div id={self.props.id} style={self.props.style} className={classes} onClick={self.onClick.bind(self)}>
        <slot />
      </div>
    );
  },
  methods: {
    onClick(event) {
      this.dispatchEvent('click', event);
    },
  },
};
