// src/vue/components/actions-group.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-actions-group',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('actions-group', colorClasses(props)));
    return { classes };
  },
};
</script>

// src/phenome/components/actions-group.jsx
import Mixins from '../utils/mixins';
import Utils from '../utils/utils';

export default {
  name: 'f7-actions-group',
  props: Mixins.colorProps,
  render() {
    const self = this;

    const classes = Utils.classNames(
      self.props.className,
      { 'actions-group': true },
    );

    return (
      <div id={self.props.id} style={self.props.style} className={classes}>
        <slot />
      </div>
    );
  },
};
