// src/svelte/components/block-header.svelte
<script>
  import Utils from '../utils/utils';
  import Mixins from '../utils/mixins';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  $: classes = Utils.classNames(
    className,
    'block-header',
    Mixins.colorClasses($$props),
  );
</script>

<div id={id} style={style} class={classes}><slot /></div>

// src/phenome/components/block-header.jsx
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

export default {
  name: 'f7-block-header',
  props: Mixins.colorProps,
  render() {
    const classes = Utils.classNames(
      this.props.className,
      'block-header',
      Mixins.colorClasses(this),
    );
    return (<div id={this.props.id} style={this.props.style} className={classes}><slot /></div>);
  },
};
