// src/vue/components/card.vue
<template>
  <div
    ref="elRef"
    :class="classes"
    :data-animate="typeof animate === 'undefined' ? animate : animate.toString()"
    :data-hide-navbar-on-open="
      typeof hideNavbarOnOpen === 'undefined' ? hideNavbarOnOpen : hideNavbarOnOpen.toString()
    "
    :data-hide-toolbar-on-open="
      typeof hideToolbarOnOpen === 'undefined' ? hideToolbarOnOpen : hideToolbarOnOpen.toString()
    "
    :data-hide-statusbar-on-open="
      typeof hideStatusbarOnOpen === 'undefined'
        ? hideStatusbarOnOpen
        : hideStatusbarOnOpen.toString()
    "
    :data-scrollable-el="scrollableEl"
    :data-swipe-to-close="
      typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()
    "
    :data-close-by-backdrop-click="
      typeof closeByBackdropClick === 'undefined'
        ? closeByBackdropClick
        : closeByBackdropClick.toString()
    "
    :data-backdrop="typeof backdrop === 'undefined' ? backdrop : backdrop.toString()"
    :data-backdrop-el="backdropEl"
  >
    <f7-card-header v-if="hasHeader">
      {{ title }}
      <slot name="header" />
    </f7-card-header>
    <f7-card-content v-if="hasContent" :padding="padding">
      {{ content }}
      <slot name="content" />
    </f7-card-content>
    <f7-card-footer v-if="hasFooter">
      {{ footer }}
      <slot name="footer" />
    </f7-card-footer>
    <slot />
  </div>
</template>
<script>
import { computed, ref, onMounted, onBeforeUnmount, watch } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';
import { f7, f7ready } from '../shared/f7';

import f7CardHeader from './card-header';
import f7CardContent from './card-content';
import f7CardFooter from './card-footer';

export default {
  name: 'f7-card',
  components: {
    f7CardHeader,
    f7CardContent,
    f7CardFooter,
  },
  props: {
    title: [String, Number],
    content: [String, Number],
    footer: [String, Number],
    outline: Boolean,
    expandable: Boolean,
    expandableAnimateWidth: Boolean,
    expandableOpened: Boolean,
    animate: {
      type: Boolean,
      default: undefined,
    },
    hideNavbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    hideToolbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    hideStatusbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    scrollableEl: {
      type: String,
      default: undefined,
    },
    swipeToClose: {
      type: Boolean,
      default: undefined,
    },
    closeByBackdropClick: {
      type: Boolean,
      default: undefined,
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    backdropEl: {
      type: String,
      default: undefined,
    },
    noShadow: Boolean,
    noBorder: Boolean,
    padding: {
      type: Boolean,
      default: true,
    },
    ...colorProps,
  },
  emits: [
    'card:beforeopen',
    'card:open',
    'card:opened',
    'card:close',
    'card:closed',
    'update:expandableOpened',
  ],
  setup(props, { emit, slots }) {
    const elRef = ref(null);

    const open = () => {
      if (!elRef.value) return;
      f7.card.open(elRef.value);
    };
    const close = () => {
      if (!elRef.value) return;
      f7.card.close(elRef.value);
    };
    const onBeforeOpen = (el, prevent) => {
      if (elRef.value !== el) return;
      emit('card:beforeopen', el, prevent);
    };
    const onOpen = (el) => {
      if (elRef.value !== el) return;
      emit('card:open', el);
      emit('update:expandableOpened', true);
    };
    const onOpened = (el, pageEl) => {
      if (elRef.value !== el) return;
      emit('card:opened', el, pageEl);
    };
    const onClose = (el) => {
      if (elRef.value !== el) return;
      emit('card:close', el);
    };
    const onClosed = (el, pageEl) => {
      if (elRef.value !== el) return;
      emit('card:closed', el, pageEl);
      emit('update:expandableOpened', false);
    };

    onMounted(() => {
      if (!props.expandable || !elRef.value) return;
      f7ready(() => {
        if (props.expandable && props.expandableOpened) {
          f7.card.open(elRef.value, false);
        }
        f7.on('cardBeforeOpen', onBeforeOpen);
        f7.on('cardOpen', onOpen);
        f7.on('cardOpened', onOpened);
        f7.on('cardClose', onClose);
        f7.on('cardClosed', onClosed);
      });
    });

    onBeforeUnmount(() => {
      f7.off('cardBeforeOpen', onBeforeOpen);
      f7.off('cardOpen', onOpen);
      f7.off('cardOpened', onOpened);
      f7.off('cardClose', onClose);
      f7.off('cardClosed', onClosed);
    });

    watch(
      () => props.expandableOpened,
      (value) => {
        if (value) {
          open();
        } else {
          close();
        }
      },
    );

    const hasHeader = computed(() => props.title || slots.header);
    const hasContent = computed(() => props.content || slots.content);
    const hasFooter = computed(() => props.footer || slots.footer);

    const classes = computed(() =>
      classNames(
        'card',
        {
          'card-outline': props.outline,
          'card-expandable': props.expandable,
          'card-expandable-animate-width': props.expandableAnimateWidth,
          'no-shadow': props.noShadow,
          'no-border': props.noBorder,
        },
        colorClasses(props),
      ),
    );
    return {
      elRef,
      classes,
      hasHeader,
      hasContent,
      hasFooter,
    };
  },
};
</script>

// src/phenome/components/card.jsx
/* eslint import/no-unresolved: ["off"] */
/* eslint import/extensions: ["off"] */
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';

import F7CardHeader from './card-header';
import F7CardContent from './card-content';
import F7CardFooter from './card-footer';

export default {
  name: 'f7-card',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    title: [String, Number],
    content: [String, Number],
    footer: [String, Number],
    outline: Boolean,
    expandable: Boolean,
    expandableAnimateWidth: Boolean,
    expandableOpened: Boolean,
    animate: {
      type: Boolean,
      default: undefined,
    },
    hideNavbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    hideToolbarOnOpen: {
      type: Boolean,
      default: undefined,
    },
    swipeToClose: {
      type: Boolean,
      default: undefined,
    },
    closeByBackdropClick: {
      type: Boolean,
      default: undefined,
    },
    backdrop: {
      type: Boolean,
      default: undefined,
    },
    noShadow: Boolean,
    noBorder: Boolean,
    padding: {
      type: Boolean,
      default: true,
    },
    ...Mixins.colorProps,
  },
  watch: {
    'props.expandableOpened': function watchOpened(expandableOpened) {
      const self = this;
      if (expandableOpened) {
        self.open();
      } else {
        self.close();
      }
    },
  },
  componentDidCreate() {
    Utils.bindMethods(this, 'onBeforeOpen onOpen onOpened onClose onClosed'.split(' '));
  },
  componentDidMount() {
    const self = this;
    if (!self.props.expandable) return;
    const el = self.refs.el;
    if (!el) return;
    el.addEventListener('card:beforeopen', self.onBeforeOpen);
    el.addEventListener('card:open', self.onOpen);
    el.addEventListener('card:opened', self.onOpened);
    el.addEventListener('card:close', self.onClose);
    el.addEventListener('card:closed', self.onClosed);
    if (self.props.expandable && self.props.expandableOpened) {
      self.$f7ready(() => {
        self.$f7.card.open(el, false);
      });
    }
  },
  componentWillUnmount() {
    const self = this;
    if (!self.props.expandable) return;
    const el = self.refs.el;
    if (!el) return;
    el.removeEventListener('card:beforeopen', self.onBeforeOpen);
    el.removeEventListener('card:open', self.onOpen);
    el.removeEventListener('card:opened', self.onOpened);
    el.removeEventListener('card:close', self.onClose);
    el.removeEventListener('card:closed', self.onClosed);
  },
  render() {
    const self = this;
    const props = self.props;
    const {
      className,
      id,
      style,
      title,
      content,
      footer,
      padding,
      outline,
      expandable,
      expandableAnimateWidth,
      animate,
      hideNavbarOnOpen,
      hideToolbarOnOpen,
      swipeToClose,
      closeByBackdropClick,
      backdrop,
      noShadow,
      noBorder,
    } = props;

    let headerEl;
    let contentEl;
    let footerEl;

    const classes = Utils.classNames(
      className,
      'card',
      {
        'card-outline': outline,
        'card-expandable': expandable,
        'card-expandable-animate-width': expandableAnimateWidth,
        'no-shadow': noShadow,
        'no-border': noBorder,
      },
      Mixins.colorClasses(props),
    );

    if (title || (self.slots && self.slots.header)) {
      headerEl = (
        <F7CardHeader>
          {title}
          <slot name="header" />
        </F7CardHeader>
      );
    }
    if (content || (self.slots && self.slots.content)) {
      contentEl = (
        <F7CardContent padding={padding}>
          {content}
          <slot name="content" />
        </F7CardContent>
      );
    }
    if (footer || (self.slots && self.slots.footer)) {
      footerEl = (
        <F7CardFooter>
          {footer}
          <slot name="footer" />
        </F7CardFooter>
      );
    }

    return (
      <div
        id={id}
        style={style}
        className={classes}
        ref="el"
        data-animate={typeof animate === 'undefined' ? animate : animate.toString()}
        data-hide-navbar-on-open={typeof hideNavbarOnOpen === 'undefined' ? hideNavbarOnOpen : hideNavbarOnOpen.toString()}
        data-hide-toolbar-on-open={typeof hideToolbarOnOpen === 'undefined' ? hideToolbarOnOpen : hideToolbarOnOpen.toString()}
        data-swipe-to-close={typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()}
        data-close-by-backdrop-click={typeof closeByBackdropClick === 'undefined' ? closeByBackdropClick : closeByBackdropClick.toString()}
        data-backdrop={typeof backdrop === 'undefined' ? backdrop : backdrop.toString()}
      >
        {headerEl}
        {contentEl}
        {footerEl}
        <slot />
      </div>
    );
  },
  methods: {
    open() {
      const self = this;
      if (!self.refs.el) return;
      self.$f7.card.open(self.refs.el);
    },
    close() {
      const self = this;
      if (!self.refs.el) return;
      self.$f7.card.close(self.refs.el);
    },
    onBeforeOpen(e) {
      this.dispatchEvent('cardBeforeOpen card:beforeopen', e, e.detail.prevent);
    },
    onOpen(e) {
      this.dispatchEvent('cardOpen card:open', e);
    },
    onOpened(e) {
      this.dispatchEvent('cardOpened card:opened', e);
    },
    onClose(e) {
      this.dispatchEvent('cardClose card:close', e);
    },
    onClosed(e) {
      this.dispatchEvent('cardClosed card:closed', e);
    },
  },
};
