// src/vue/components/fab-backdrop.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-fab-backdrop',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('fab-backdrop', colorClasses(props)));
    return { classes };
  },
};
</script>

// src/phenome/components/fab-backdrop.jsx
import Utils from '../utils/utils';

export default {
  name: 'f7-fab-backdrop',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
  },
  render() {
    const self = this;
    const props = self.props;
    const {
      className,
      id,
      style,
    } = props;

    const classes = Utils.classNames(
      className,
      'fab-backdrop',
    );
    return (
      <div
        id={id}
        style={style}
        className={classes}
      />
    );
  },
};
