// packages/svelte/components/menu-item.svelte
<script>
  import { createEventDispatcher, onMount, afterUpdate, onDestroy } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import f7 from '../utils/f7';
  import hasSlots from '../utils/has-slots';

  import Icon from './icon.svelte';

  const dispatch = createEventDispatcher();

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let text = undefined;
  export let iconOnly = undefined;
  export let href = undefined;
  export let link = undefined;
  export let target = undefined;
  export let dropdown = undefined;

  let el;

  $: hrefComputed = typeof href === 'undefined' && link ? '#' : href;

  $: attrs = Utils.extend(
    {
      href: hrefComputed,
      target,
    },
    Mixins.linkRouterAttrs($$props),
    Mixins.linkActionsAttrs($$props),
  );

  // eslint-disable-next-line
  $: hasDefaultSlots = hasSlots(arguments, 'default');
  // eslint-disable-next-line
  $: hasTextSlots = hasSlots(arguments, 'text');

  $: iconOnlyComputed = iconOnly || (!text && !hasTextSlots);

  $: classes = Utils.classNames(
    {
      'menu-item': true,
      'menu-item-dropdown': dropdown || dropdown === '',
      'icon-only': iconOnlyComputed,
    },
    className,
    Mixins.colorClasses($$props),
    Mixins.linkRouterClasses($$props),
    Mixins.linkActionsClasses($$props),
  );

  $: hasIcon = $$props.icon || $$props.iconMaterial || $$props.iconF7 || $$props.iconMd || $$props.iconIos || $$props.iconAurora;

  $: isLink = (link || href || href === '');

  function onClick(e) {
    dispatch('click', [e]);
    if (typeof $$props.onClick === 'function') $$props.onClick(e);
  }

  function onOpened(itemEl) {
    if (itemEl !== el) return;
    dispatch('menuOpened', [el]);
    if (typeof $$props.onMenuOpened === 'function') $$props.onMenuOpened(el);
  }
  function onClosed(itemEl) {
    if (itemEl !== el) return;
    dispatch('menuClosed', [el]);
    if (typeof $$props.onMenuClosed === 'function') $$props.onMenuClosed(el);
  }

  onMount(() => {
    if ($$props.routeProps) {
      el.f7RouteProps = $$props.routeProps;
    }
    f7.ready(() => {
      f7.instance.on('menuOpened', onOpened);
      f7.instance.on('menuClosed', onClosed);
    });
  });
  afterUpdate(() => {
    if ($$props.routeProps) {
      el.f7RouteProps = $$props.routeProps;
    }
  });
  onDestroy(() => {
    if (!el || !f7.instance) return;
    delete el.f7RouteProps;
    f7.instance.off('menuOpened', onOpened);
    f7.instance.off('menuClosed', onClosed);
  });

</script>
<!-- svelte-ignore a11y-missing-attribute -->
{#if isLink}
  <a on:click={onClick} bind:this={el} class={classes} id={id} style={style} {...attrs}>
    {#if typeof text !== 'undefined' || hasTextSlots || hasIcon}
      <div class="menu-item-content">
        {Utils.text(text)}
        {#if hasIcon}
        <Icon
          material={$$props.iconMaterial}
          f7={$$props.iconF7}
          icon={$$props.icon}
          md={$$props.iconMd}
          ios={$$props.iconIos}
          aurora={$$props.iconAurora}
          color={$$props.iconColor}
          size={$$props.iconSize}
        />
        {/if}
        <slot name="text" />
      </div>
    {/if}
    <slot />
  </a>
{:else}
  <div on:click={onClick} bind:this={el} class={classes} id={id} style={style} {...attrs}>
    {#if typeof text !== 'undefined' || hasTextSlots || hasIcon}
      <div class="menu-item-content">
        {Utils.text(text)}
        {#if hasIcon}
        <Icon
          material={$$props.iconMaterial}
          f7={$$props.iconF7}
          icon={$$props.icon}
          md={$$props.iconMd}
          ios={$$props.iconIos}
          aurora={$$props.iconAurora}
          color={$$props.iconColor}
          size={$$props.iconSize}
        />
        {/if}
        <slot name="text" />
      </div>
    {/if}
    <slot />
  </div>
{/if}

// src/phenome/components/menu-item.jsx
/* eslint import/no-unresolved: ["off"] */
/* eslint import/extensions: ["off"] */
import Utils from '../utils/utils';
import Mixins from '../utils/mixins';
import F7Icon from './icon';

export default {
  name: 'f7-menu-item',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    text: String,
    iconOnly: Boolean,
    href: String,
    link: Boolean,
    target: String,
    dropdown: Boolean,
    ...Mixins.colorProps,
    ...Mixins.linkIconProps,
    ...Mixins.linkRouterProps,
    ...Mixins.linkActionsProps,
  },
  render() {
    const self = this;
    const props = self.props;
    const {
      id,
      className,
      style,
      link,
      href,
      text,
      dropdown,
      iconOnly,
      icon,
      iconColor,
      iconSize,
      iconMaterial,
      iconF7,
      iconMd,
      iconIos,
      iconAurora,
    } = props;

    const slots = self.slots;

    let iconEl;
    let iconOnlyComputed;
    if (icon || iconMaterial || iconF7 || iconMd || iconIos || iconAurora) {
      iconEl = (
        <F7Icon
          material={iconMaterial}
          f7={iconF7}
          icon={icon}
          md={iconMd}
          ios={iconIos}
          aurora={iconAurora}
          color={iconColor}
          size={iconSize}
        />
      );
    }
    if (
      iconOnly
      || (!text && slots.text && slots.text.length === 0)
      || (!text && !slots.text)
    ) {
      iconOnlyComputed = true;
    } else {
      iconOnlyComputed = false;
    }

    const isLink = link || href || href === '';
    const Tag = isLink ? 'a' : 'div';

    const isDropdown = dropdown || dropdown === '';

    const classes = Utils.classNames(
      {
        'menu-item': true,
        'menu-item-dropdown': isDropdown,
        'icon-only': iconOnlyComputed,
      },
      className,
      Mixins.colorClasses(props),
      Mixins.linkRouterClasses(props),
      Mixins.linkActionsClasses(props),
    );

    return (
      <Tag ref="el" className={classes} id={id} style={style} {...self.attrs}>
        {(text || (slots.text && slots.text.length) || iconEl) && (
          <div className="menu-item-content">
            {text}
            {iconEl}
            <slot name="text" />
          </div>
        )}
        <slot />
      </Tag>
    );
  },
  componentDidCreate() {
    Utils.bindMethods(this, ['onClick', 'onOpened', 'onClosed']);
  },
  componentDidMount() {
    const self = this;
    const el = self.refs.el;
    if (!el) return;
    self.eventTargetEl = el;
    el.addEventListener('click', self.onClick);
    const { routeProps } = self.props;
    if (routeProps) el.f7RouteProps = routeProps;
    self.$f7ready((f7) => {
      f7.on('menuOpened', self.onOpened);
      f7.on('menuClosed', self.onClosed);
    });
  },
  componentDidUpdate() {
    const self = this;
    const el = self.refs.el;
    if (!el) return;
    const { routeProps } = self.props;
    if (routeProps) el.f7RouteProps = routeProps;
  },
  componentWillUnmount() {
    const self = this;
    const el = self.refs.el;
    if (!el || !self.$f7) return;
    el.removeEventListener('click', self.onClick);
    self.$f7.off('menuOpened', self.onOpened);
    self.$f7.off('menuClosed', self.onOpened);
    self.eventTargetEl = null;
    delete el.f7RouteProps;
    delete self.eventTargetEl;
  },
  computed: {
    attrs() {
      const self = this;
      const props = self.props;
      const { href, link, target } = props;
      let hrefComputed = href;
      if (typeof hrefComputed === 'undefined' && link) hrefComputed = '#';
      return Utils.extend(
        {
          href: hrefComputed,
          target,
        },
        Mixins.linkRouterAttrs(props),
        Mixins.linkActionsAttrs(props),
      );
    },
  },
  methods: {
    onClick(e) {
      this.dispatchEvent('click', e);
    },
    onOpened(el) {
      if (this.eventTargetEl !== el) return;
      this.dispatchEvent('menuOpened menu:opened', el);
    },
    onClosed(el) {
      if (this.eventTargetEl !== el) return;
      this.dispatchEvent('menuClosed menu:closed', el);
    },
  },
};
