// packages/svelte/components/swiper-slide.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let zoom = undefined;

  $: classes = Utils.classNames(
    className,
    'swiper-slide',
    Mixins.colorClasses($$props),
  );

</script>

<div id={id} style={style} class={classes}>
  {#if zoom}
    <div class="swiper-zoom-container">
      <slot />
    </div>
  {:else}
    <slot />
  {/if}
</div>

// src/phenome/components/swiper-slide.jsx
import Utils from '../utils/utils';

export default {
  name: 'f7-swiper-slide',
  render() {
    const classes = Utils.classNames(
      this.props.className,
      'swiper-slide',
    );

    return (
      <div id={this.props.id} style={this.props.style} className={classes}>
        {this.props.zoom ? (
          <div className="swiper-zoom-container">
            <slot />
          </div>
        ) : (
          <slot />
        )}
      </div>
    );
  },
  props: {
    zoom: Boolean,
  },
};
