// src/svelte/components/block.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';
  import { useTab } from '../shared/use-tab.js';

  let {
    class: className,
    inset = false,
    insetIos = false,
    insetMd = false,
    xsmallInset = false,
    xsmallInsetIos = false,
    xsmallInsetMd = false,
    smallInset = false,
    smallInsetIos = false,
    smallInsetMd = false,
    mediumInset = false,
    mediumInsetIos = false,
    mediumInsetMd = false,
    largeInset = false,
    largeInsetIos = false,
    largeInsetMd = false,
    xlargeInset = false,
    xlargeInsetIos = false,
    xlargeInsetMd = false,
    strong = false,
    strongIos = false,
    strongMd = false,
    tabs = false,
    tab = false,
    tabActive = false,
    accordionList = false,
    accordionOpposite = false,
    outline = false,
    outlineMd = false,
    outlineIos = false,
    children,
    ...restProps
  } = $props();

  let el = $state(null);

  const classes = $derived(
    classNames(
      className,
      'block',
      {
        inset,
        'inset-ios': insetIos,
        'inset-md': insetMd,
        'xsmall-inset': xsmallInset,
        'xsmall-inset-ios': xsmallInsetIos,
        'xsmall-inset-md': xsmallInsetMd,
        'small-inset': smallInset,
        'small-inset-ios': smallInsetIos,
        'small-inset-md': smallInsetMd,
        'medium-inset': mediumInset,
        'medium-inset-ios': mediumInsetIos,
        'medium-inset-md': mediumInsetMd,
        'large-inset': largeInset,
        'large-inset-ios': largeInsetIos,
        'large-inset-md': largeInsetMd,
        'xlarge-inset': xlargeInset,
        'xlarge-inset-ios': xlargeInsetIos,
        'xlarge-inset-md': xlargeInsetMd,
        'block-strong': strong,
        'block-strong-ios': strongIos,
        'block-strong-md': strongMd,
        'accordion-list': accordionList,
        'accordion-opposite': accordionOpposite,
        tabs,
        tab,
        'tab-active': tabActive,
        'block-outline': outline,
        'block-outline-md': outlineMd,
        'block-outline-ios': outlineIos,
      },
      colorClasses(restProps),
    ),
  );

  useTab(() => el, restProps);
</script>

<div class={classes} bind:this={el} {...restProps}>
  {@render children?.()}
</div>

// src/react/components/block.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils.js';
import { colorClasses } from '../shared/mixins.js';
import { useTab } from '../shared/use-tab.js';

/* dts-props
  id: string | number;
  className: string;
  style: React.CSSProperties;
  inset?: boolean
  insetIos?: boolean
  insetMd?: boolean
  xsmallInset?: boolean
  xsmallInsetIos?: boolean
  xsmallInsetMd?: boolean
  smallInset?: boolean
  smallInsetIos?: boolean
  smallInsetMd?: boolean
  mediumInset?: boolean
  mediumInsetIos?: boolean
  mediumInsetMd?: boolean
  largeInset?: boolean
  largeInsetIos?: boolean
  largeInsetMd?: boolean
  xlargeInset?: boolean
  xlargeInsetIos?: boolean
  xlargeInsetMd?: boolean
  strong?: boolean
  strongIos?: boolean
  strongMd?: boolean
  outline?: boolean
  outlineIos?: boolean
  outlineMd?: boolean
  tabs?: boolean
  tab?: boolean
  tabActive?: boolean
  accordionList?: boolean
  accordionOpposite?: boolean
  onTabShow?: (el?: HTMLElement) => void
  onTabHide?: (el?: HTMLElement) => void
  ref?: React.MutableRefObject<{el: HTMLElement | null}>;
  children?: React.ReactNode;
  COLOR_PROPS
*/

const Block = forwardRef((props, ref) => {
  const {
    className,
    inset,
    insetIos,
    insetMd,
    xsmallInset,
    xsmallInsetIos,
    xsmallInsetMd,
    smallInset,
    smallInsetIos,
    smallInsetMd,
    mediumInset,
    mediumInsetIos,
    mediumInsetMd,
    largeInset,
    largeInsetIos,
    largeInsetMd,
    xlargeInset,
    xlargeInsetIos,
    xlargeInsetMd,
    strong,
    strongIos,
    strongMd,
    outline,
    outlineIos,
    outlineMd,
    accordionList,
    accordionOpposite,

    tabs,
    tab,
    tabActive,
    id,
    style,
    children,
  } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);
  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  useTab(elRef, props);

  const classes = classNames(
    className,
    'block',
    {
      inset,
      'inset-ios': insetIos,
      'inset-md': insetMd,
      'xsmall-inset': xsmallInset,
      'xsmall-inset-ios': xsmallInsetIos,
      'xsmall-inset-md': xsmallInsetMd,
      'small-inset': smallInset,
      'small-inset-ios': smallInsetIos,
      'small-inset-md': smallInsetMd,
      'medium-inset': mediumInset,
      'medium-inset-ios': mediumInsetIos,
      'medium-inset-md': mediumInsetMd,
      'large-inset': largeInset,
      'large-inset-ios': largeInsetIos,
      'large-inset-md': largeInsetMd,
      'xlarge-inset': xlargeInset,
      'xlarge-inset-ios': xlargeInsetIos,
      'xlarge-inset-md': xlargeInsetMd,
      'block-strong': strong,
      'block-strong-ios': strongIos,
      'block-strong-md': strongMd,
      'block-outline': outline,
      'block-outline-ios': outlineIos,
      'block-outline-md': outlineMd,
      'accordion-list': accordionList,
      'accordion-opposite': accordionOpposite,
      tabs,
      tab,
      'tab-active': tabActive,
    },
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      {children}
    </div>
  );
});

Block.displayName = 'f7-block';

export default Block;
