// packages/svelte/components/card.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import f7 from '../utils/f7';
  import hasSlots from '../utils/has-slots';

  import CardHeader from './card-header.svelte';
  import CardContent from './card-content.svelte';
  import CardFooter from './card-footer.svelte';

  const dispatch = createEventDispatcher();

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let title = undefined;
  export let content = undefined;
  export let footer = undefined;
  export let outline = false;
  export let expandable = false;
  export let expandableAnimateWidth = false;
  export let expandableOpened = false;
  export let animate = undefined;
  export let hideNavbarOnOpen = undefined;
  export let hideToolbarOnOpen = undefined;
  export let hideStatusbarOnOpen = undefined;
  export let scrollableEl = undefined;
  export let swipeToClose = undefined;
  export let closeByBackdropClick = undefined;
  export let backdrop = undefined;
  export let backdropEl = undefined;
  export let noShadow = false;
  export let noBorder = false;
  export let padding = true;

  let el;

  $: classes = Utils.classNames(
    className,
    'card',
    {
      'card-outline': outline,
      'card-expandable': expandable,
      'card-expandable-animate-width': expandableAnimateWidth,
      'no-shadow': noShadow,
      'no-border': noBorder,
    },
    Mixins.colorClasses($$props),
  );

  /* eslint-disable no-undef */
  $: hasHeaderSlots = hasSlots(arguments, 'header');
  $: hasContentSlots = hasSlots(arguments, 'content');
  $: hasFooterSlots = hasSlots(arguments, 'footer');
  /* eslint-enable no-undef */

  function open() {
    f7.instance.card.open(el);
  }

  function close() {
    f7.instance.card.close(el);
  }

  let initialWatched = false;
  function watchOpened(openedPassed) {
    if (!initialWatched) {
      initialWatched = true;
      return;
    }
    if (openedPassed) {
      open();
    } else {
      close();
    }
  }

  $: watchOpened(expandableOpened);

  function onBeforeOpen(cardEl, prevent) {
    if (cardEl !== el) return;
    dispatch('cardBeforeOpen', [el, prevent]);
    if (typeof $$props.onCardBeforeOpen === 'function') $$props.onCardBeforeOpen(el, prevent);
  }
  function onOpen(cardEl) {
    if (cardEl !== el) return;
    dispatch('cardOpen', [el]);
    if (typeof $$props.onCardOpen === 'function') $$props.onCardOpen(el);
  }
  function onOpened(cardEl, pageEl) {
    if (cardEl !== el) return;
    dispatch('cardOpened', [el, pageEl]);
    if (typeof $$props.onCardOpened === 'function') $$props.onCardOpened(el, pageEl);
  }
  function onClose(cardEl) {
    if (cardEl !== el) return;
    dispatch('cardClose', [el]);
    if (typeof $$props.onCardClose === 'function') $$props.onCardClose(el);
  }
  function onClosed(cardEl, pageEl) {
    if (cardEl !== el) return;
    dispatch('cardClosed', [el, pageEl]);
    if (typeof $$props.onCardClosed === 'function') $$props.onCardClosed(el, pageEl);
  }

  onMount(() => {
    if (!expandable) return;
    f7.ready(() => {
      f7.instance.on('cardBeforeOpen', onBeforeOpen);
      f7.instance.on('cardOpen', onOpen);
      f7.instance.on('cardOpened', onOpened);
      f7.instance.on('cardClose', onClose);
      f7.instance.on('cardClosed', onClosed);
      if (expandable && expandableOpened && el) {
        f7.instance.card.open(el, false);
      }
    });
  });

  onDestroy(() => {
    if (!expandable) return;
    if (!f7.instance || !el) return;
    f7.instance.off('cardBeforeOpen', onBeforeOpen);
    f7.instance.off('cardOpen', onOpen);
    f7.instance.off('cardOpened', onOpened);
    f7.instance.off('cardClose', onClose);
    f7.instance.off('cardClosed', onClosed);
  });

</script>

<div
  bind:this={el}
  id={id}
  style={style}
  class={classes}
  data-animate={typeof animate === 'undefined' ? animate : animate.toString()}
  data-hide-navbar-on-open={typeof hideNavbarOnOpen === 'undefined' ? hideNavbarOnOpen : hideNavbarOnOpen.toString()}
  data-hide-toolbar-on-open={typeof hideToolbarOnOpen === 'undefined' ? hideToolbarOnOpen : hideToolbarOnOpen.toString()}
  data-hide-statusbar-on-open={typeof hideStatusbarOnOpen === 'undefined' ? hideStatusbarOnOpen : hideStatusbarOnOpen.toString()}
  data-scrollable-el={scrollableEl}
  data-swipe-to-close={typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()}
  data-close-by-backdrop-click={typeof closeByBackdropClick === 'undefined' ? closeByBackdropClick : closeByBackdropClick.toString()}
  data-backdrop={typeof backdrop === 'undefined' ? backdrop : backdrop.toString()}
  data-backdrop-el={backdropEl}
>
  {#if typeof title !== 'undefined' || hasHeaderSlots}
    <CardHeader>
      {Utils.text(title)}
      <slot name="header" />
    </CardHeader>
  {/if}
  {#if typeof content !== 'undefined' || hasContentSlots}
    <CardContent padding={padding}>
      {Utils.text(content)}
      <slot name="content" />
    </CardContent>
  {/if}
  {#if typeof footer !== 'undefined' || hasFooterSlots}
    <CardFooter>
      {Utils.text(footer)}
      <slot name="footer" />
    </CardFooter>
  {/if}
  <slot />
</div>

// src/react/components/card.jsx
import React, { forwardRef, useRef, useImperativeHandle, useEffect } from 'react';

import CardHeader from './card-header';
import CardContent from './card-content';
import CardFooter from './card-footer';

import { classNames, getDataAttrs, getSlots, emit } from '../utils/utils';
import { colorClasses } from '../utils/mixins';
import { f7, f7ready } from '../utils/f7';
import { watchProp } from '../utils/watch-prop';

/* dts-props
  id: string | number;
  className: string;
  style: React.CSSProperties;
  title? : string | number
  content? : string | number
  footer? : string | number
  outline? : boolean
  expandable? : boolean
  expandableAnimateWidth? : boolean
  expandableOpened? : boolean
  animate? : boolean
  hideNavbarOnOpen? : boolean
  hideToolbarOnOpen? : boolean
  hideStatusbarOnOpen? : boolean
  scrollableEl? : string
  swipeToClose? : boolean
  closeByBackdropClick? : boolean
  backdrop? : boolean
  backdropEl? : string
  noShadow? : boolean
  noBorder? : boolean
  padding? : boolean
  color? : string
  colorTheme? : string
  textColor? : string
  bgColor? : string
  borderColor? : string
  rippleColor? : string
  themeDark? : boolean
  onCardBeforeOpen? : (el?: HTMLElement, prevent?: any) => void
  onCardOpen? : (el?: HTMLElement) => void
  onCardOpened? : (el?: HTMLElement, pageEl?: HTMLElement) => void
  onCardClose? : (el?: HTMLElement) => void
  onCardClosed? : (el?: HTMLElement, pageEl?: HTMLElement) => void
  COLOR_PROPS
*/

const Card = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    title,
    content,
    footer,
    padding,
    outline,
    expandable,
    expandableAnimateWidth,
    expandableOpened,
    animate,
    hideNavbarOnOpen,
    hideToolbarOnOpen,
    hideStatusbarOnOpen,
    scrollableEl,
    swipeToClose,
    closeByBackdropClick,
    backdrop,
    backdropEl,
    noShadow,
    noBorder,
  } = props;
  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);

  const open = () => {
    if (!elRef.current) return;
    f7.card.open(elRef.current);
  };
  const close = () => {
    if (!elRef.current) return;
    f7.card.close(elRef.current);
  };
  const onBeforeOpen = (el, prevent) => {
    if (elRef.current !== el) return;
    emit(props, 'cardBeforeOpen', el, prevent);
  };
  const onOpen = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'cardOpen', el);
  };
  const onOpened = (el, pageEl) => {
    if (elRef.current !== el) return;
    emit(props, 'cardOpened', el, pageEl);
  };
  const onClose = (el) => {
    if (elRef.current !== el) return;
    emit(props, 'cardClose', el);
  };
  const onClosed = (el, pageEl) => {
    if (elRef.current !== el) return;
    emit(props, 'cardClosed', el, pageEl);
  };

  const onMount = () => {
    if (!expandable) return;
    if (!elRef.current) return;
    f7ready(() => {
      f7.on('cardBeforeOpen', onBeforeOpen);
      f7.on('cardOpen', onOpen);
      f7.on('cardOpened', onOpened);
      f7.on('cardClose', onClose);
      f7.on('cardClosed', onClosed);
      if (expandable && expandableOpened) {
        f7.card.open(elRef.current, false);
      }
    });
  };

  const onDestroy = () => {
    if (!expandable) return;
    if (!f7) return;
    f7.off('cardBeforeOpen', onBeforeOpen);
    f7.off('cardOpen', onOpen);
    f7.off('cardOpened', onOpened);
    f7.off('cardClose', onClose);
    f7.off('cardClosed', onClosed);
  };

  useEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  watchProp(expandableOpened, (value) => {
    if (value) {
      open();
    } else {
      close();
    }
  });

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    open,
    close,
  }));

  let headerEl;
  let contentEl;
  let footerEl;

  const classes = classNames(
    className,
    'card',
    {
      'card-outline': outline,
      'card-expandable': expandable,
      'card-expandable-animate-width': expandableAnimateWidth,
      'no-shadow': noShadow,
      'no-border': noBorder,
    },
    colorClasses(props),
  );

  const slots = getSlots(props);

  if (title || (slots && slots.header)) {
    headerEl = (
      <CardHeader>
        {title}
        {slots.header}
      </CardHeader>
    );
  }
  if (content || (slots && slots.content)) {
    contentEl = (
      <CardContent padding={padding}>
        {content}
        {slots.content}
      </CardContent>
    );
  }
  if (footer || (slots && slots.footer)) {
    footerEl = (
      <CardFooter>
        {footer}
        {slots.fooer}
      </CardFooter>
    );
  }

  return (
    <div
      id={id}
      style={style}
      className={classes}
      data-animate={typeof animate === 'undefined' ? animate : animate.toString()}
      data-hide-navbar-on-open={
        typeof hideNavbarOnOpen === 'undefined' ? hideNavbarOnOpen : hideNavbarOnOpen.toString()
      }
      data-hide-toolbar-on-open={
        typeof hideToolbarOnOpen === 'undefined' ? hideToolbarOnOpen : hideToolbarOnOpen.toString()
      }
      data-hide-statusbar-on-open={
        typeof hideStatusbarOnOpen === 'undefined'
          ? hideStatusbarOnOpen
          : hideStatusbarOnOpen.toString()
      }
      data-scrollable-el={scrollableEl}
      data-swipe-to-close={
        typeof swipeToClose === 'undefined' ? swipeToClose : swipeToClose.toString()
      }
      data-close-by-backdrop-click={
        typeof closeByBackdropClick === 'undefined'
          ? closeByBackdropClick
          : closeByBackdropClick.toString()
      }
      data-backdrop={typeof backdrop === 'undefined' ? backdrop : backdrop.toString()}
      data-backdrop-el={backdropEl}
      ref={elRef}
      {...dataAttrs}
    >
      {headerEl}
      {contentEl}
      {footerEl}
      <slot />
    </div>
  );
});

Card.displayName = 'f7-card';

export default Card;
