// src/svelte/components/list-item-content.svelte
<script>
  import { createEventDispatcher, onMount, afterUpdate } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import hasSlots from '../utils/has-slots';

  import Badge from './badge.svelte';

  const dispatch = createEventDispatcher();

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let title = undefined;
  export let text = undefined;
  export let media = undefined;
  export let subtitle = undefined;
  export let header = undefined;
  export let footer = undefined;
  export let after = undefined;
  export let badge = undefined;
  export let badgeColor = undefined;
  export let mediaList = false;
  export let mediaItem = false;

  export let checkbox = false;
  export let checked = false;
  // export let defaultChecked = false;
  export let indeterminate = false;
  export let radio = false;
  export let name = undefined;
  export let value = undefined;
  export let readonly = false;
  export let required = false;
  export let disabled = false;

  export let sortableOpposite = false;

  let el;
  let inputEl;
  let innerEl;

  $: classes = Utils.classNames(
    className,
    'item-content',
    {
      'item-checkbox': checkbox,
      'item-radio': radio,
    },
    Mixins.colorClasses($$props),
  );

  /* eslint-disable no-undef */
  $: hasMedia = media || hasSlots(arguments, 'media');
  $: hasTitle = title || hasSlots(arguments, 'title');
  $: hasHeader = header || hasSlots(arguments, 'header');
  $: hasFooter = footer || hasSlots(arguments, 'footer');
  $: hasSubtitle = subtitle || hasSlots(arguments, 'subtitle');
  $: hasText = text || hasSlots(arguments, 'text');
  $: hasAfter = after || badge || hasSlots(arguments, 'after');
  /* eslint-enable no-undef */

  $: isMedia = mediaList || mediaItem;

  function onClick(event) {
    dispatch('click', [event]);
  }

  function onChange(event) {
    dispatch('change', [event]);
  }

  onMount(() => {
    if (indeterminate && inputEl) {
      inputEl.indeterminate = true;
    }
  });

  afterUpdate(() => {
    if (inputEl) {
      inputEl.indeterminate = indeterminate;
    }
  });

</script>
<!-- svelte-ignore a11y-missing-attribute -->
{#if checkbox || radio}
  <label
    bind:this={el}
    id={id}
    style={style}
    class={classes}
    on:click={onClick}
  >
    <slot name="content-start" />
    {#if sortableOpposite}
      <div class="sortable-handler" />
    {/if}
    <input
      bind:this={inputEl}
      value={value || ''}
      name={name}
      checked={checked}
      readonly={readonly}
      disabled={disabled}
      required={required}
      type={radio ? 'radio' : 'checkbox'}
      on:change={onChange}
    />
    <i class={`icon icon-${radio ? 'radio' : 'checkbox'}`} />
    {#if hasMedia}
      <div class="item-media">
        {#if media}
          <img src={media} />
        {/if}
        <slot name="media" />
      </div>
    {/if}
    <div bind:this={innerEl} class="item-inner">
      <slot name="inner-start" />
      {#if isMedia}
        {#if hasHeader}
          <div class="item-header">
            {header}
            <slot name="header" />
          </div>
        {/if}
        <div class="item-title-row">
          <slot name="before-title" />
          {#if (hasTitle)}
            <div class="item-title">
              {title}
              <slot name="title" />
            </div>
          {/if}
          <slot name="after-title" />
          {#if hasAfter}
            <div class="item-after">
              <slot name="after-start" />
              <span>{after}</span>
              {#if badge}
                <Badge color={badgeColor}>{badge}</Badge>
              {/if}
              <slot name="after" />
              <slot name="after-end" />
            </div>
          {/if}
        </div>
        {#if hasSubtitle}
          <div class="item-subtitle">
            {subtitle}
            <slot name="subtitle" />
          </div>
        {/if}
        {#if hasText}
          <div class="item-text">
            {text}
            <slot name="text" />
          </div>
        {/if}
        <slot name="inner" />
        <slot/>
        {#if hasFooter}
          <div class="item-footer">
            {footer}
            <slot name="footer" />
          </div>
        {/if}
      {:else}
        <slot name="before-title" />
        {#if (hasTitle || hasHeader || hasFooter)}
          <div class="item-title">
            {#if hasHeader}
              <div class="item-header">
                {header}
                <slot name="header" />
              </div>
            {/if}
            {title}
            <slot name="title" />
            {#if hasFooter}
              <div class="item-footer">
                {footer}
                <slot name="footer" />
              </div>
            {/if}
          </div>
        {/if}
        <slot name="after-title" />
        {#if hasAfter}
          <div class="item-after">
            <slot name="after-start" />
            <span>{after}</span>
            {#if badge}
              <Badge color={badgeColor}>{badge}</Badge>
            {/if}
            <slot name="after" />
            <slot name="after-end" />
          </div>
        {/if}
        <slot name="inner" />
        <slot />
      {/if}
      <slot name="inner-end" />
    </div>
    <slot name="content" />
    <slot name="content-end" />
  </label>
{:else}
  <div
    bind:this={el}
    id={id}
    style={style}
    class={classes}
    on:click={onClick}
  >
    <slot name="content-start" />
    {#if sortableOpposite}
      <div class="sortable-handler" />
    {/if}
    {#if hasMedia}
      <div class="item-media">
        {#if media}
          <img src={media} />
        {/if}
        <slot name="media" />
      </div>
    {/if}
    <div bind:this={innerEl} class="item-inner">
      <slot name="inner-start" />
      {#if isMedia}
        {#if hasHeader}
          <div class="item-header">
            {header}
            <slot name="header" />
          </div>
        {/if}
        <div class="item-title-row">
          <slot name="before-title" />
          {#if (hasTitle)}
            <div class="item-title">
              {title}
              <slot name="title" />
            </div>
          {/if}
          <slot name="after-title" />
          {#if hasAfter}
            <div class="item-after">
              <slot name="after-start" />
              <span>{after}</span>
              {#if badge}
                <Badge color={badgeColor}>{badge}</Badge>
              {/if}
              <slot name="after" />
              <slot name="after-end" />
            </div>
          {/if}
        </div>
        {#if hasSubtitle}
          <div class="item-subtitle">
            {subtitle}
            <slot name="subtitle" />
          </div>
        {/if}
        {#if hasText}
          <div class="item-text">
            {text}
            <slot name="text" />
          </div>
        {/if}
        <slot name="inner" />
        <slot/>
        {#if hasFooter}
          <div class="item-footer">
            {footer}
            <slot name="footer" />
          </div>
        {/if}
      {:else}
        <slot name="before-title" />
        {#if (hasTitle || hasHeader || hasFooter)}
          <div class="item-title">
            {#if hasHeader}
              <div class="item-header">
                {header}
                <slot name="header" />
              </div>
            {/if}
            {title}
            <slot name="title" />
            {#if hasFooter}
              <div class="item-footer">
                {footer}
                <slot name="footer" />
              </div>
            {/if}
          </div>
        {/if}
        <slot name="after-title" />
        {#if hasAfter}
          <div class="item-after">
            <slot name="after-start" />
            <span>{after}</span>
            {#if badge}
              <Badge color={badgeColor}>{badge}</Badge>
            {/if}
            <slot name="after" />
            <slot name="after-end" />
          </div>
        {/if}
        <slot name="inner" />
        <slot />
      {/if}
      <slot name="inner-end" />
    </div>
    <slot name="content" />
    <slot name="content-end" />
  </div>
{/if}

// src/react/components/list-item-content.jsx
import React, { useRef, useEffect } from 'react';
import { classNames } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

import Badge from './badge';

const ListItemContent = (props) => {
  const {
    indeterminate,
    radio,
    checkbox,
    value,
    name,
    readonly,
    disabled,
    checked,
    defaultChecked,
    required,
    media,
    header,
    footer,
    title,
    subtitle,
    text,
    after,
    badge,
    badgeColor,
    radioIcon,
    swipeout,
    sortable,
    accordionItem,
    onChange,
    onClick,
    isMediaComputed,
    isSortableComputed,
    isSortableOppositeComputed,
    slots,
  } = props;
  const inputElRef = useRef(null);

  useEffect(() => {
    if (inputElRef.current) {
      inputElRef.current.indeterminate = !!indeterminate;
    }
  }, [indeterminate]);

  let titleEl;
  let afterWrapEl;
  let afterEl;
  let badgeEl;
  let innerEl;
  let titleRowEl;
  let subtitleEl;
  let textEl;
  let mediaEl;
  let inputEl;
  let inputIconEl;
  let headerEl;
  let footerEl;

  // Input
  if (radio || checkbox) {
    inputEl = (
      <input
        ref={inputElRef}
        value={value}
        name={name}
        checked={checked}
        defaultChecked={defaultChecked}
        readOnly={readonly}
        disabled={disabled}
        required={required}
        type={radio ? 'radio' : 'checkbox'}
        onChange={onChange}
      />
    );
    inputIconEl = <i className={`icon icon-${radio ? 'radio' : 'checkbox'}`} />;
  }
  // Media
  if (media || slots.media) {
    let mediaImgEl;
    if (media) {
      mediaImgEl = <img src={media} />;
    }
    mediaEl = (
      <div className="item-media">
        {mediaImgEl}
        {slots.media}
      </div>
    );
  }
  // Inner Elements
  if (header || slots.header) {
    headerEl = (
      <div className="item-header">
        {header}
        {slots.header}
      </div>
    );
  }
  if (footer || slots.footer) {
    footerEl = (
      <div className="item-footer">
        {footer}
        {slots.footer}
      </div>
    );
  }
  if (title || slots.title || (!isMediaComputed && headerEl) || (!isMediaComputed && footerEl)) {
    titleEl = (
      <div className="item-title">
        {!isMediaComputed && headerEl}
        {title}
        {slots.title}
        {!isMediaComputed && footerEl}
      </div>
    );
  }
  if (subtitle || slots.subtitle) {
    subtitleEl = (
      <div className="item-subtitle">
        {subtitle}
        {slots.subtitle}
      </div>
    );
  }
  if (text || slots.text) {
    textEl = (
      <div className="item-text">
        {text}
        {slots.text}
      </div>
    );
  }
  if (after || badge || slots.after) {
    if (after) {
      afterEl = <span>{after}</span>;
    }
    if (badge) {
      badgeEl = <Badge color={badgeColor}>{badge}</Badge>;
    }
    afterWrapEl = (
      <div className="item-after">
        {slots['after-start']}
        {afterEl}
        {badgeEl}
        {slots.after}
        {slots['after-end']}
      </div>
    );
  }
  if (isMediaComputed) {
    titleRowEl = (
      <div className="item-title-row">
        {slots['before-title']}
        {titleEl}
        {slots['after-title']}
        {afterWrapEl}
      </div>
    );
    innerEl = (
      <div className="item-inner">
        {slots['inner-start']}
        {headerEl}
        {titleRowEl}
        {subtitleEl}
        {textEl}
        {swipeout || accordionItem ? null : slots.default}
        {slots.inner}
        {footerEl}
        {slots['inner-end']}
      </div>
    );
  } else {
    innerEl = (
      <div className="item-inner">
        {slots['inner-start']}
        {slots['before-title']}
        {titleEl}
        {slots['after-title']}
        {afterWrapEl}
        {swipeout || accordionItem ? null : slots.default}
        {slots.inner}
        {slots['inner-end']}
      </div>
    );
  }

  const ItemContentTag = checkbox || radio ? 'label' : 'div';

  const classes = classNames(
    'item-content',
    {
      'item-checkbox': checkbox,
      'item-radio': radio,
      'item-radio-icon-start': radio && radioIcon === 'start',
      'item-radio-icon-end': radio && radioIcon === 'end',
    },
    colorClasses(props),
  );
  return (
    <ItemContentTag className={classes} onClick={onClick}>
      {isSortableComputed && sortable !== false && isSortableOppositeComputed && (
        <div className="sortable-handler" />
      )}
      {slots['content-start']}
      {inputEl}
      {inputIconEl}
      {mediaEl}
      {innerEl}
      {slots.content}
      {slots['content-end']}
    </ItemContentTag>
  );
};

ListItemContent.displayName = 'f7-list-item-content';

export default ListItemContent;
