// src/svelte/components/message.svelte
<script>
  /* eslint-disable no-undef */
  import { createEventDispatcher } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import hasSlots from '../utils/has-slots';

  const dispatch = createEventDispatcher();

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let text = undefined;
  export let htmlText = undefined;
  export let name = undefined;
  export let avatar = undefined;
  export let type = 'sent';
  export let image = undefined;
  export let header = undefined;
  export let footer = undefined;
  export let textHeader = undefined;
  export let textFooter = undefined;
  export let first = undefined;
  export let last = undefined;
  export let tail = undefined;
  export let sameName = undefined;
  export let sameHeader = undefined;
  export let sameFooter = undefined;
  export let sameAvatar = undefined;
  export let typing = undefined;

  $: classes = Utils.classNames(
    className,
    'message',
    {
      'message-sent': type === 'sent' || !type,
      'message-received': type === 'received',
      'message-typing': typing,
      'message-first': first,
      'message-last': last,
      'message-tail': tail,
      'message-same-name': sameName,
      'message-same-header': sameHeader,
      'message-same-footer': sameFooter,
      'message-same-avatar': sameAvatar,
    },
    Mixins.colorClasses($$props),
  );

  $: hasAvatarSlots = hasSlots(arguments, 'avatar');
  $: hasNameSlots = hasSlots(arguments, 'name');
  $: hasHeaderSlots = hasSlots(arguments, 'header');
  $: hasImageSlots = hasSlots(arguments, 'image');
  $: hasTextHeaderSlots = hasSlots(arguments, 'text-header');
  $: hasTextFooterSlots = hasSlots(arguments, 'text-footer');
  $: hasTextSlots = hasSlots(arguments, 'text');
  $: hasFooterSlots = hasSlots(arguments, 'footer');

  function onClick() {
    dispatch('click');
    if (typeof $$props.onClick === 'function') $$props.onClick();
  }

  function onNameClick() {
    dispatch('clickName');
    if (typeof $$props.onClickName === 'function') $$props.onClickName();
  }

  function onTextClick() {
    dispatch('clickText');
    if (typeof $$props.onClickText === 'function') $$props.onClickText();
  }

  function onAvatarClick() {
    dispatch('clickAvatar');
    if (typeof $$props.onClickAvatar === 'function') $$props.onClickAvatar();
  }

  function onHeaderClick() {
    dispatch('clickHeader');
    if (typeof $$props.onClickHeader === 'function') $$props.onClickHeader();
  }

  function onFooterClick() {
    dispatch('clickFooter');
    if (typeof $$props.onClickFooter === 'function') $$props.onClickFooter();
  }

  function onBubbleClick() {
    dispatch('clickBubble');
    if (typeof $$props.onClickBubble === 'function') $$props.onClickBubble();
  }

</script>
<!-- svelte-ignore a11y-missing-attribute -->
<div id={id} style={style} class={classes} on:click={onClick}>
  <slot name="start"/>
  {#if (avatar || hasAvatarSlots)}
    <div
      on:click={onAvatarClick}
      class="message-avatar"
      style={ avatar ? `background-image: url(${avatar})` : undefined }
    >
      <slot name="avatar"/>
    </div>
  {/if}
  <div class="message-content">
    <slot name="content-start"/>
    {#if (hasNameSlots || name)}
      <div class="message-name" on:click={onNameClick}>
        {Utils.text(name)}
        <slot name="name"/>
      </div>
    {/if}
    {#if (hasHeaderSlots || header)}
      <div class="message-header" on:click={onHeaderClick}>
        {Utils.text(header)}
        <slot name="header"/>
      </div>
    {/if}
    <div class="message-bubble" on:click={onBubbleClick}>
      <slot name="bubble-start"/>
      {#if (hasImageSlots || image)}
        <div class="message-image">
          {#if image}
            <img src={image} />
          {/if}
          <slot name="image"/>
        </div>
      {/if}
      {#if (hasTextHeaderSlots || textHeader)}
        <div class="message-text-header">
          {Utils.text(textHeader)}
          <slot name="text-header"/>
        </div>
      {/if}
      {#if (hasTextSlots || text || htmlText || typing)}
        <div class="message-text" on:click={onTextClick}>
          {Utils.text(text)}
          {#if htmlText}{@html htmlText}{/if}
          <slot name="text"/>
          {#if typing}
            <div class="message-typing-indicator">
              <div />
              <div />
              <div />
            </div>
          {/if}
        </div>
      {/if}
      {#if (hasTextFooterSlots || textFooter)}
        <div class="message-text-footer">
          {Utils.text(textFooter)}
          <slot name="text-footer"/>
        </div>
      {/if}
      <slot name="bubble-end"/>
      <slot />
    </div>
    {#if (hasFooterSlots || footer)}
      <div class="message-footer" on:click={onFooterClick}>
        {Utils.text(footer)}
        <slot name="footer"/>
      </div>
    {/if}
    <slot name="content-end"/>
  </div>
  <slot name="end"/>
</div>

// src/react/components/message.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getDataAttrs, getSlots, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  text? : string
  name? : string
  avatar? : string
  type? : string
  image? : string
  header? : string
  footer? : string
  textHeader? : string
  textFooter? : string
  first? : boolean
  last? : boolean
  tail? : boolean
  sameName? : boolean
  sameHeader? : boolean
  sameFooter? : boolean
  sameAvatar? : boolean
  typing? : boolean
  COLOR_PROPS
  onClick? : (event?: any) => void
  onClickName? : (event?: any) => void
  onClickText? : (event?: any) => void
  onClickAvatar? : (event?: any) => void
  onClickHeader? : (event?: any) => void
  onClickFooter? : (event?: any) => void
  onClickBubble? : (event?: any) => void
*/

const Message = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    text,
    name,
    avatar,
    type = 'sent',
    image,
    header,
    footer,
    textHeader,
    textFooter,
    first,
    last,
    tail,
    sameName,
    sameHeader,
    sameFooter,
    sameAvatar,
    typing,
  } = props;
  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);

  const onClick = (event) => {
    emit(props, 'click', event);
  };
  const onNameClick = (event) => {
    emit(props, 'click:name clickName', event);
  };
  const onTextClick = (event) => {
    emit(props, 'click:text clickText', event);
  };
  const onAvatarClick = (event) => {
    emit(props, 'click:avatar clickAvatar', event);
  };
  const onHeaderClick = (event) => {
    emit(props, 'click:header clickHeader', event);
  };
  const onFooterClick = (event) => {
    emit(props, 'click:footer clickFooter', event);
  };
  const onBubbleClick = (event) => {
    emit(props, 'click:bubble clickBubble', event);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const slots = getSlots(props);

  const classes = classNames(
    className,
    'message',
    {
      'message-sent': type === 'sent',
      'message-received': type === 'received',
      'message-typing': typing,
      'message-first': first,
      'message-last': last,
      'message-tail': tail,
      'message-same-name': sameName,
      'message-same-header': sameHeader,
      'message-same-footer': sameFooter,
      'message-same-avatar': sameAvatar,
    },
    colorClasses(props),
  );

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...dataAttrs} onClick={onClick}>
      {slots.start}
      {(avatar || slots.avatar) && (
        <div
          className="message-avatar"
          style={{ backgroundImage: avatar && `url(${avatar})` }}
          onClick={onAvatarClick}
        >
          {slots.avatar}
        </div>
      )}
      <div className="message-content">
        {slots['content-start']}
        {(slots.name || name) && (
          <div className="message-name" onClick={onNameClick}>
            {slots.name || name}
          </div>
        )}
        {(slots.header || header) && (
          <div className="message-header" onClick={onHeaderClick}>
            {slots.header || header}
          </div>
        )}
        <div className="message-bubble" onClick={onBubbleClick}>
          {slots['bubble-start']}
          {(slots.image || image) && (
            <div className="message-image">{slots.image || <img src={image} />}</div>
          )}
          {(slots['text-header'] || textHeader) && (
            <div className="message-text-header">{slots['text-header'] || textHeader}</div>
          )}
          {(slots.text || text || typing) && (
            <div className="message-text" onClick={onTextClick}>
              {slots.text || text}
              {typing && (
                <div className="message-typing-indicator">
                  <div />
                  <div />
                  <div />
                </div>
              )}
            </div>
          )}
          {(slots['text-footer'] || textFooter) && (
            <div className="message-text-footer">{slots['text-footer'] || textFooter}</div>
          )}
          {slots['bubble-end']}
          {slots.default}
        </div>
        {(slots.footer || footer) && (
          <div className="message-footer" onClick={onFooterClick}>
            {slots.footer || footer}
          </div>
        )}
        {slots['content-end']}
      </div>
      {slots.end}
    </div>
  );
});

Message.displayName = 'f7-message';

export default Message;
