// src/svelte/components/nav-title-large.svelte
<script>
  import { colorClasses } from '../shared/mixins.js';
  import { classNames } from '../shared/utils.js';

  let { class: className, children, ...restProps } = $props();

  const classes = $derived(classNames(className, 'title-large', colorClasses(restProps)));
</script>

<div class={classes} {...restProps}>
  <div class="title-large-text">
    {@render children?.()}
  </div>
</div>

// src/react/components/nav-title-large.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  COLOR_PROPS
*/

const NavTitleLarge = forwardRef((props, ref) => {
  const { className, id, style, children } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(className, 'title-large', colorClasses(props));

  return (
    <div id={id} style={style} className={classes} ref={elRef} {...extraAttrs}>
      <div className="title-large-text">{children}</div>
    </div>
  );
});

NavTitleLarge.displayName = 'f7-nav-title-large';

export default NavTitleLarge;
