// src/vue/components/photo-browser.vue
<script>
import { ref, watch, onMounted, onBeforeUnmount } from 'vue';
import { extend } from '../shared/utils';
import { f7ready, f7 } from '../shared/f7';

export default {
  name: 'f7-photo-browser',

  props: {
    init: {
      type: Boolean,
      default: true,
    },
    params: Object,
    photos: Array,
    exposition: {
      type: Boolean,
      default: true,
    },
    expositionHideCaptions: {
      type: Boolean,
      default: false,
    },
    type: {
      type: String,
    },
    navbar: {
      type: Boolean,
      default: true,
    },
    toolbar: {
      type: Boolean,
      default: true,
    },
    theme: {
      type: String,
    },
    captionsTheme: {
      type: String,
    },
    iconsColor: {
      type: String,
    },
    swipeToClose: {
      type: Boolean,
      default: true,
    },
    pageBackLinkText: {
      type: String,
      default: undefined,
    },
    popupCloseLinkText: {
      type: String,
      default: undefined,
    },
    navbarOfText: {
      type: String,
      default: undefined,
    },
    navbarShowCount: {
      type: Boolean,
      default: undefined,
    },
    swiper: {
      type: Object,
    },
    url: {
      type: String,
    },
    routableModals: {
      type: Boolean,
      default: true,
    },
    virtualSlides: {
      type: Boolean,
      default: true,
    },
    view: [String, Object],
    renderNavbar: Function,
    renderToolbar: Function,
    renderCaption: Function,
    renderObject: Function,
    renderLazyPhoto: Function,
    renderPhoto: Function,
    renderPage: Function,
    renderPopup: Function,
    renderStandalone: Function,
  },
  emits: [
    'photobrowser:open',
    'photobrowser:close',
    'photobrowser:opened',
    'photobrowser:closed',
    'photobrowser:swipetoclose',
  ],
  setup(props, { emit }) {
    const f7PhotoBrowser = ref(null);

    const open = (index) => {
      return f7PhotoBrowser.value.open(index);
    };
    const close = () => {
      return f7PhotoBrowser.value.close();
    };
    const expositionToggle = () => {
      return f7PhotoBrowser.value.expositionToggle();
    };
    const expositionEnable = () => {
      return f7PhotoBrowser.value.expositionEnable();
    };
    const expositionDisable = () => {
      return f7PhotoBrowser.value.expositionDisable();
    };
    watch(
      () => props.photos,
      (value) => {
        const pb = f7PhotoBrowser.value;
        if (!pb) return;
        pb.params.photos = value;
        if (pb.opened && pb.swiper) {
          pb.swiper.update();
        }
      },
    );
    onMounted(() => {
      if (!props.init) return;
      f7ready(() => {
        let paramsComputed;

        if (typeof props.params !== 'undefined') {
          paramsComputed = props.params;
        } else {
          paramsComputed = { ...props };
          delete paramsComputed.params;
        }

        Object.keys(paramsComputed).forEach((param) => {
          if (typeof paramsComputed[param] === 'undefined' || paramsComputed[param] === '')
            delete paramsComputed[param];
        });

        paramsComputed = extend({}, paramsComputed, {
          on: {
            open() {
              emit('photobrowser:open');
            },
            close() {
              emit('photobrowser:close');
            },
            opened() {
              emit('photobrowser:opened');
            },
            closed() {
              emit('photobrowser:closed');
            },
            swipeToClose() {
              emit('photobrowser:swipetoclose');
            },
          },
        });

        f7PhotoBrowser.value = f7.photoBrowser.create(paramsComputed);
      });
    });

    onBeforeUnmount(() => {
      if (f7PhotoBrowser.value && f7PhotoBrowser.value.destroy) f7PhotoBrowser.value.destroy();
      f7PhotoBrowser.value = null;
    });

    return {
      open,
      close,
      expositionToggle,
      expositionEnable,
      expositionDisable,
    };
  },
  render() {
    return null;
  },
};
</script>

// src/react/components/photo-browser.jsx
import { forwardRef, useRef, useImperativeHandle, useEffect } from 'react';
import { extend, emit } from '../shared/utils';
import { watchProp } from '../shared/watch-prop';
import { f7ready, f7 } from '../shared/f7';

/* dts-props
  init? : boolean
  params? : Object
  photos? : Array<any>
  exposition? : boolean
  expositionHideCaptions? : boolean
  type? : string
  navbar? : boolean
  toolbar? : boolean
  theme? : string
  captionsTheme? : string
  iconsColor? : string
  swipeToClose? : boolean
  pageBackLinkText? : string
  popupCloseLinkText? : string
  navbarOfText? : string
  navbarShowCount? : boolean
  swiper? : Object
  url? : string
  routableModals? : boolean
  virtualSlides? : boolean
  view? : string | Object
  renderNavbar? : Function
  renderToolbar? : Function
  renderCaption? : Function
  renderObject? : Function
  renderLazyPhoto? : Function
  renderPhoto? : Function
  renderPage? : Function
  renderPopup? : Function
  renderStandalone? : Function
  onPhotoBrowserOpen? : (...args: any[]) => void
  onPhotoBrowserClose? : (...args: any[]) => void
  onPhotoBrowserOpened? : (...args: any[]) => void
  onPhotoBrowserClosed? : (...args: any[]) => void
  onPhotoBrowserSwipeToClose? : (...args: any[]) => void
*/

const PhotoBrowser = forwardRef((props, ref) => {
  const f7PhotoBrowser = useRef(null);
  const {
    init = true,
    params,
    photos,
    exposition = true,
    expositionHideCaptions = false,
    type,
    navbar = true,
    toolbar = true,
    theme,
    captionsTheme,
    iconsColor,
    swipeToClose = true,
    pageBackLinkText,
    popupCloseLinkText,
    navbarOfText,
    navbarShowCount,
    swiper,
    url,
    routableModals = true,
    virtualSlides = true,
    view,
    renderNavbar,
    renderToolbar,
    renderCaption,
    renderObject,
    renderLazyPhoto,
    renderPhoto,
    renderPage,
    renderPopup,
    renderStandalone,
  } = props;

  const open = (index) => {
    return f7PhotoBrowser.current.open(index);
  };
  const close = () => {
    return f7PhotoBrowser.current.close();
  };
  const expositionToggle = () => {
    return f7PhotoBrowser.current.expositionToggle();
  };
  const expositionEnable = () => {
    return f7PhotoBrowser.current.expositionEnable();
  };
  const expositionDisable = () => {
    return f7PhotoBrowser.current.expositionDisable();
  };

  useImperativeHandle(ref, () => ({
    f7PhotoBrowser: f7PhotoBrowser.current,
    open,
    close,
    expositionToggle,
    expositionEnable,
    expositionDisable,
  }));

  watchProp(photos, (newValue) => {
    const pb = f7PhotoBrowser.current;
    if (!pb) return;
    pb.params.photos = newValue;
    if (pb.opened && pb.swiper) {
      pb.swiper.update();
    }
  });

  const onMount = () => {
    if (!init) return;
    f7ready(() => {
      let paramsComputed;

      if (typeof params !== 'undefined') {
        paramsComputed = params;
      } else {
        paramsComputed = {
          photos,
          exposition,
          expositionHideCaptions,
          type,
          navbar,
          toolbar,
          theme,
          captionsTheme,
          iconsColor,
          swipeToClose,
          pageBackLinkText,
          popupCloseLinkText,
          navbarOfText,
          navbarShowCount,
          swiper,
          url,
          routableModals,
          virtualSlides,
          view,
          renderNavbar,
          renderToolbar,
          renderCaption,
          renderObject,
          renderLazyPhoto,
          renderPhoto,
          renderPage,
          renderPopup,
          renderStandalone,
        };
      }

      Object.keys(paramsComputed).forEach((param) => {
        if (typeof paramsComputed[param] === 'undefined' || paramsComputed[param] === '')
          delete paramsComputed[param];
      });

      paramsComputed = extend({}, paramsComputed, {
        on: {
          open() {
            emit(props, 'photoBrowserOpen');
          },
          close() {
            emit(props, 'photoBrowserClose');
          },
          opened() {
            emit(props, 'photoBrowserOpened');
          },
          closed() {
            emit(props, 'photoBrowserClosed');
          },
          swipeToClose() {
            emit(props, 'photoBrowserSwipeToClose');
          },
        },
      });

      f7PhotoBrowser.current = f7.photoBrowser.create(params);
    });
  };

  const onDestroy = () => {
    if (f7PhotoBrowser.current && f7PhotoBrowser.current.destroy) f7PhotoBrowser.current.destroy();
    f7PhotoBrowser.current = null;
  };

  useEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  return null;
});

PhotoBrowser.displayName = 'f7-photo-browser';

export default PhotoBrowser;
