// src/svelte/components/swipeout-button.svelte
<script>
  import { createEventDispatcher } from 'svelte';

  import { colorClasses } from '../shared/mixins.js';
  import { classNames, plainText, createEmitter } from '../shared/utils.js';
  import { restProps } from '../shared/rest-props.js';

  const emit = createEmitter(createEventDispatcher, $$props);

  let className = undefined;
  export { className as class };

  export let text = undefined;
  export let confirmTitle = undefined;
  export let confirmText = undefined;
  export let overswipe = undefined;
  export let close = undefined;
  let deleteProp = undefined;
  export { deleteProp as delete };
  export let href = undefined;

  $: classes = classNames(
    className,
    {
      'swipeout-overswipe': overswipe,
      'swipeout-delete': deleteProp,
      'swipeout-close': close,
    },
    colorClasses($$props),
  );

  function onClick() {
    emit('click');
  }
</script>

<a
  href={href || '#'}
  data-confirm={confirmText || undefined}
  data-confirm-title={confirmTitle || undefined}
  class={classes}
  on:click={onClick}
  {...restProps($$restProps)}
>
  {plainText(text)}
  <slot />
</a>

// src/react/components/swipeout-button.jsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';
import { classNames, getExtraAttrs, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  text? : string
  confirmTitle? : string
  confirmText? : string
  overswipe? : boolean
  close? : boolean
  delete? : boolean
  href? : string
  COLOR_PROPS
  onClick? : (event?: any) => void
*/

const SwipeoutButton = forwardRef((props, ref) => {
  const {
    className,
    id,
    style,
    children,
    text,
    confirmTitle,
    confirmText,
    overswipe,
    close,
    delete: deleteProp,
    href,
  } = props;
  const extraAttrs = getExtraAttrs(props);

  const elRef = useRef(null);

  const onClick = (e) => {
    emit(props, 'click', e);
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
  }));

  const classes = classNames(
    className,
    {
      'swipeout-overswipe': overswipe,
      'swipeout-delete': deleteProp,
      'swipeout-close': close,
    },
    colorClasses(props),
  );

  return (
    <a
      ref={elRef}
      href={href || '#'}
      id={id}
      style={style}
      data-confirm={confirmText || undefined}
      data-confirm-title={confirmTitle || undefined}
      className={classes}
      {...extraAttrs}
      onClick={onClick}
    >
      {children}
      {text}
    </a>
  );
});

SwipeoutButton.displayName = 'f7-swipeout-button';

export default SwipeoutButton;
