// src/svelte/components/text-editor.svelte
<script>
  import { createEventDispatcher, onMount, onDestroy } from 'svelte';
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';
  import f7 from '../utils/f7';

  const dispatch = createEventDispatcher();

  let className = undefined;
  export { className as class };

  export let mode = undefined;
  export let value = undefined;
  export let buttons = undefined;
  export let customButtons = undefined;
  export let dividers = undefined;
  export let imageUrlText = undefined;
  export let linkUrlText = undefined;
  export let placeholder = undefined;
  export let clearFormattingOnPaste = undefined;
  export let resizable = false;

  let el;
  let f7TextEditor;

  export function instance() {
    return f7TextEditor;
  }

  $: classes = Utils.classNames(
    className,
    'text-editor',
    resizable && 'text-editor-resizable',
    Mixins.colorClasses($$props),
  );

  function watchValue(newValue) {
    if (f7TextEditor) {
      f7TextEditor.setValue(newValue);
    }
  }

  $: watchValue(value);

  function onChange(editor, editorValue) {
    dispatch('textEditorChange', [editorValue]);
    if (typeof $$props.onTextEditorChange === 'function') $$props.onTextEditorChange(editorValue);
  }
  function onInput() {
    dispatch('textEditorChange');
    if (typeof $$props.onTextEditorChange === 'function') $$props.onTextEditorChange();
  }
  function onFocus() {
    dispatch('textEditorFocus');
    if (typeof $$props.onTextEditorFocus === 'function') $$props.onTextEditorFocus();
  }
  function onBlur() {
    dispatch('textEditorBlur');
    if (typeof $$props.onTextEditorBlur === 'function') $$props.onTextEditorBlur();
  }
  function onButtonClick(editor, button) {
    dispatch('textEditorButtonClick', [button]);
    if (typeof $$props.onTextEditorButtonClick === 'function') $$props.onTextEditorButtonClick(button);
  }
  function onKeyboardOpen() {
    dispatch('textEditorKeyboardOpen');
    if (typeof $$props.onTextEditorKeyboardOpen === 'function') $$props.onTextEditorKeyboardOpen();
  }
  function onKeyboardClose() {
    dispatch('textEditorKeyboardClose');
    if (typeof $$props.onTextEditorKeyboardClose === 'function') $$props.onTextEditorKeyboardClose();
  }
  function onPopoverOpen() {
    dispatch('textEditorPopoverOpen');
    if (typeof $$props.onTextEditorPopoverOpen === 'function') $$props.onTextEditorPopoverOpen();
  }
  function onPopoverClose() {
    dispatch('textEditorPopoverClose');
    if (typeof $$props.onTextEditorPopoverClose === 'function') $$props.onTextEditorPopoverClose();
  }

  onMount(() => {
    const params = Utils.noUndefinedProps({
      el,
      mode,
      value,
      buttons,
      customButtons,
      dividers,
      imageUrlText,
      linkUrlText,
      placeholder,
      clearFormattingOnPaste,
      on: {
        change: onChange,
        input: onInput,
        focus: onFocus,
        blur: onBlur,
        buttonClick: onButtonClick,
        keyboardOpen: onKeyboardOpen,
        keyboardClose: onKeyboardClose,
        popoverOpen: onPopoverOpen,
        popoverClose: onPopoverClose,
      },
    });
    f7.ready(() => {
      f7TextEditor = f7.instance.textEditor.create(params);
    });
  });

  onDestroy(() => {
    if (f7TextEditor && f7TextEditor.destroy) {
      f7TextEditor.destroy();
    }
  });
</script>

<div bind:this={el} class={classes} {...restProps($$restProps)}>
  <slot name="root-start" />
  <div class="text-editor-content" contenteditable><slot /></div>
  <slot name="root-end" />
  <slot name="root" />
</div>

// src/react/components/text-editor.jsx
import React, { forwardRef, useRef, useImperativeHandle, useLayoutEffect } from 'react';
import { classNames, getDataAttrs, getSlots, noUndefinedProps, emit } from '../shared/utils';
import { colorClasses } from '../shared/mixins';
import { f7ready, f7 } from '../shared/f7';
import { watchProp } from '../shared/watch-prop';

/* dts-props
  id?: string | number;
  className?: string;
  style?: React.CSSProperties;
  COLOR_PROPS
  mode? : string
  value? : string
  buttons? : Array<any>
  customButtons? : Object
  dividers? : boolean
  imageUrlText? : string
  linkUrlText? : string
  placeholder? : string
  clearFormattingOnPaste? : boolean
  resizable? : boolean
  onTextEditorChange? : (value?: any) => void
  onTextEditorFocus? : (...args: any[]) => void
  onTextEditorBlur? : (...args: any[]) => void
  onTextEditorButtonClick? : (button?: any) => void
  onTextEditorKeyboardOpen? : (...args: any[]) => void
  onTextEditorKeyboardClose? : (...args: any[]) => void
  onTextEditorPopoverOpen? : (...args: any[]) => void
  onTextEditorPopoverClose? : (...args: any[]) => void
*/

const TextEditor = forwardRef((props, ref) => {
  const f7TextEditor = useRef(null);
  const {
    className,
    id,
    style,
    mode,
    value,
    buttons,
    customButtons,
    dividers,
    imageUrlText,
    linkUrlText,
    placeholder,
    clearFormattingOnPaste,
    resizable = false,
  } = props;
  const dataAttrs = getDataAttrs(props);

  const elRef = useRef(null);

  const onChange = (editor, editorValue) => {
    emit(props, 'textEditorChange', editorValue);
  };
  const onInput = () => {
    emit(props, 'textEditorChange');
  };
  const onFocus = () => {
    emit(props, 'textEditorFocus');
  };
  const onBlur = () => {
    emit(props, 'textEditorBlur');
  };
  const onButtonClick = (editor, button) => {
    emit(props, 'textEditorButtonClick', button);
  };
  const onKeyboardOpen = () => {
    emit(props, 'textEditorKeyboardOpen');
  };
  const onKeyboardClose = () => {
    emit(props, 'textEditorKeyboardClose');
  };
  const onPopoverOpen = () => {
    emit(props, 'textEditorPopoverOpen');
  };
  const onPopoverClose = () => {
    emit(props, 'textEditorPopoverClose');
  };

  useImperativeHandle(ref, () => ({
    el: elRef.current,
    f7TextEditor: () => f7TextEditor.current,
  }));

  watchProp(value, (newValue) => {
    if (f7TextEditor.current) {
      f7TextEditor.current.setValue(newValue);
    }
  });

  const onMount = () => {
    const params = noUndefinedProps({
      el: elRef.current,
      mode,
      value,
      buttons,
      customButtons,
      dividers,
      imageUrlText,
      linkUrlText,
      placeholder,
      clearFormattingOnPaste,
      on: {
        change: onChange,
        input: onInput,
        focus: onFocus,
        blur: onBlur,
        buttonClick: onButtonClick,
        keyboardOpen: onKeyboardOpen,
        keyboardClose: onKeyboardClose,
        popoverOpen: onPopoverOpen,
        popoverClose: onPopoverClose,
      },
    });
    f7ready(() => {
      f7TextEditor.current = f7.textEditor.create(params);
    });
  };

  const onDestroy = () => {
    if (f7TextEditor.current && f7TextEditor.current.destroy) {
      f7TextEditor.current.destroy();
    }
    f7TextEditor.current = null;
  };

  useLayoutEffect(() => {
    onMount();
    return onDestroy;
  }, []);

  const slots = getSlots(props);

  const classes = classNames(
    className,
    'text-editor',
    resizable && 'text-editor-resizable',
    colorClasses(props),
  );
  return (
    <div ref={elRef} id={id} style={style} className={classes} {...dataAttrs}>
      {slots['root-start']}
      <div className="text-editor-content" contentEditable>
        {slots.default}
      </div>
      {slots['root-end']}
      {slots.root}
    </div>
  );
});

TextEditor.displayName = 'f7-text-editor';

export default TextEditor;
