// kitchen-sink/vue/src/app.vue
<template>
  <f7-app :params="f7Params">
    <f7-statusbar></f7-statusbar>
    <f7-panel left cover>
      <f7-view url="/panel-left/" links-view=".view-main"></f7-view>
    </f7-panel>
    <f7-panel right reveal>
      <f7-view url="/panel-right/"></f7-view>
    </f7-panel>
    <f7-view url="/" :main="true" class="ios-edges"></f7-view>
  </f7-app>
</template>
<script>
  import { f7App, f7Panel, f7View, f7Statusbar } from 'framework7-vue';
  import routes from './routes';

  export default {
    components: {
      f7App,
      f7Panel,
      f7View,
      f7Statusbar,
    },
    data() {
      // Demo Theme
      let theme = 'auto';
      if (document.location.search.indexOf('theme=') >= 0) {
        [theme] = document.location.search.split('theme=')[1].split('&');
      }

      return {
        f7Params: {
          theme,
          routes,
          id: 'io.framework7.testapp',
        },
      };
    },
  };
</script>

// react/kitchen-sink/src/app.jsx
import React from 'react';
import { App, Panel, View, Statusbar } from 'framework7-react';
import routes from './routes';

export default function (props) {
  let theme = 'auto';
  if (document.location.search.indexOf('theme=') >= 0) {
    theme = document.location.search.split('theme=')[1].split('&')[0];
  }
  return (
    <App params={{ theme, routes }}>
      <Statusbar />
      <Panel left cover>
        <View url="/panel-left/" linksView=".view-main" />
      </Panel>
      <Panel right reveal>
        <View url="/panel-right/"/>
      </Panel>
      <View url="/" main className="ios-edges"/>
    </App>
  );
};
