// src/vue/components/menu.vue
<template>
  <div :class="classes">
    <div class="menu-inner">
      <slot />
    </div>
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-menu',
  props: {
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() => classNames('menu', colorClasses(props)));
    return { classes };
  },
};
</script>

// packages/svelte/components/menu.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  $: classes = Utils.classNames(
    className,
    'menu',
    Mixins.colorClasses($$props),
  );

</script>

<div id={id} style={style} class={classes}>
  <div class="menu-inner">
    <slot />
  </div>
</div>
