// src/vue/components/nav-right.vue
<template>
  <div :class="classes">
    <slot />
  </div>
</template>
<script>
import { computed } from 'vue';
import { classNames } from '../shared/utils';
import { colorClasses, colorProps } from '../shared/mixins';

export default {
  name: 'f7-nav-right',
  props: {
    sliding: Boolean,
    ...colorProps,
  },
  setup(props) {
    const classes = computed(() =>
      classNames(
        'right',
        {
          sliding: props.sliding,
        },
        colorClasses(props),
      ),
    );
    return { classes };
  },
};
</script>

// packages/svelte/components/nav-right.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';
  import restProps from '../utils/rest-props';

  let className = undefined;
  export { className as class };

  export let sliding = undefined;

  $: classes = Utils.classNames(
    className,
    'right',
    {
      sliding,
    },
    Mixins.colorClasses($$props),
  );
</script>
<div
  class={classes}
  {...restProps($$restProps)}
>
  <slot />
</div>
