// src/react/components/_old/swiper-slide.jsx
import Utils from '../utils/utils';

export default {
  name: 'f7-swiper-slide',
  props: {
    id: [String, Number],
    className: String, // phenome-react-line
    style: Object, // phenome-react-line
    zoom: Boolean,
  },
  render() {
    const props = this.props;
    const {
      className,
      id,
      style,
      zoom,
    } = props;

    const classes = Utils.classNames(
      className,
      'swiper-slide',
    );

    return (
      <div id={id} style={style} className={classes}>
        {zoom ? (
          <div className="swiper-zoom-container">
            <slot />
          </div>
        ) : (
          <slot />
        )}
      </div>
    );
  },

};

// packages/svelte/components/swiper-slide.svelte
<script>
  import Mixins from '../utils/mixins';
  import Utils from '../utils/utils';

  export let id = undefined;
  export let style = undefined;

  let className = undefined;
  export { className as class };

  export let zoom = undefined;

  $: classes = Utils.classNames(
    className,
    'swiper-slide',
    Mixins.colorClasses($$props),
  );

</script>

<div id={id} style={style} class={classes}>
  {#if zoom}
    <div class="swiper-zoom-container">
      <slot />
    </div>
  {:else}
    <slot />
  {/if}
</div>
