// kitchen-sink/vue/src/pages/contacts-list.vue
<template>
  <f7-page>
    <f7-navbar title="Contacts List" back-link="Back"></f7-navbar>
    <f7-list contacts-list>
      <f7-list-group>
        <f7-list-item title="A" group-title />
        <f7-list-item title="Aaron " />
        <f7-list-item title="Abbie" />
        <f7-list-item title="Adam" />
        <f7-list-item title="Adele" />
        <f7-list-item title="Agatha" />
        <f7-list-item title="Agnes" />
        <f7-list-item title="Albert" />
        <f7-list-item title="Alexander" />
      </f7-list-group>
      <f7-list-group>
        <f7-list-item title="B" group-title />
        <f7-list-item title="Bailey" />
        <f7-list-item title="Barclay" />
        <f7-list-item title="Bartolo" />
        <f7-list-item title="Bellamy" />
        <f7-list-item title="Belle" />
        <f7-list-item title="Benjamin" />
      </f7-list-group>
      <f7-list-group>
        <f7-list-item title="C" group-title />
        <f7-list-item title="Caiden" />
        <f7-list-item title="Calvin" />
        <f7-list-item title="Candy" />
        <f7-list-item title="Carl" />
        <f7-list-item title="Cherilyn" />
        <f7-list-item title="Chester" />
        <f7-list-item title="Chloe" />
      </f7-list-group>
      <f7-list-group>
        <f7-list-item title="V" group-title />
        <f7-list-item title="Vladimir" />
      </f7-list-group>
    </f7-list>
  </f7-page>
</template>
<script>
import { f7Navbar, f7Page, f7List, f7ListGroup, f7ListItem } from 'framework7-vue';

export default {
  components: {
    f7Navbar,
    f7Page,
    f7List,
    f7ListGroup,
    f7ListItem,
  },
};
</script>

// kitchen-sink/react/src/pages/contacts-list.jsx
import React from 'react';
import { Navbar, Page, List, ListGroup, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Contacts List" backLink="Back"></Navbar>
    <List contactsList>
      <ListGroup>
        <ListItem title="A" groupTitle />
        <ListItem title="Aaron" />
        <ListItem title="Abbie" />
        <ListItem title="Adam" />
        <ListItem title="Adele" />
        <ListItem title="Agatha" />
        <ListItem title="Agnes" />
        <ListItem title="Albert" />
        <ListItem title="Alexander" />
      </ListGroup>
      <ListGroup>
        <ListItem title="B" groupTitle />
        <ListItem title="Bailey" />
        <ListItem title="Barclay" />
        <ListItem title="Bartolo" />
        <ListItem title="Bellamy" />
        <ListItem title="Belle" />
        <ListItem title="Benjamin" />
      </ListGroup>
      <ListGroup>
        <ListItem title="C" groupTitle />
        <ListItem title="Caiden" />
        <ListItem title="Calvin" />
        <ListItem title="Candy" />
        <ListItem title="Carl" />
        <ListItem title="Cherilyn" />
        <ListItem title="Chester" />
        <ListItem title="Chloe" />
      </ListGroup>
      <ListGroup>
        <ListItem title="V" groupTitle />
        <ListItem title="Vladimir" />
      </ListGroup>
    </List>
  </Page>
);
