// kitchen-sink/vue/src/pages/tabs.vue
<template>
  <f7-page>
    <f7-navbar title="Tabs" back-link="Back"></f7-navbar>
    <f7-list>
      <f7-list-item link="/tabs-static/" title="Static Tabs"></f7-list-item>
      <f7-list-item link="/tabs-animated/" title="Animated Tabs"></f7-list-item>
      <f7-list-item link="/tabs-swipeable/" title="Swipeable Tabs"></f7-list-item>
      <f7-list-item link="/tabs-routable/" title="Routable Tabs"></f7-list-item>
    </f7-list>
  </f7-page>
</template>
<script>
  import { f7Navbar, f7Page, f7List, f7ListItem } from 'framework7-vue';

  export default {
    components: {
      f7Navbar,
      f7Page,
      f7List,
      f7ListItem,
    },
  };
</script>

// kitchen-sink/react/src/pages/tabs.jsx
import React from 'react';
import { Navbar, Page, List, ListItem } from 'framework7-react';

export default () => (
  <Page>
    <Navbar title="Tabs" backLink="Back"></Navbar>
    <List>
      <ListItem link="/tabs-static/" title="Static Tabs" />
      <ListItem link="/tabs-animated/" title="Animated Tabs" />
      <ListItem link="/tabs-swipeable/" title="Swipeable Tabs" />
      <ListItem link="/tabs-routable/" title="Routable Tabs" />
    </List>
  </Page>
);
